from pathlib import Path

path = Path('community_ui.py')
text = path.read_text(encoding='utf-8')
start = text.index('_PUBLIC_MAP_TEMPLATE = r"""')
end = text.index('def language_panel', start)

new_block = r'''_PUBLIC_MAP_TEMPLATE = r"""
<link href="https://unpkg.com/maplibre-gl@5.24.0/dist/maplibre-gl.css" rel="stylesheet">
<style>
.defect-map-view{display:grid;gap:16px;min-width:0}.defect-overview{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(280px,.75fr);gap:16px;padding:20px;border:1px solid var(--line);border-radius:24px;background:linear-gradient(145deg,#fff,#f5f8f1);box-shadow:var(--shadow-soft)}.defect-overview h2{margin:6px 0 7px;color:var(--forest);font-size:clamp(22px,5vw,32px)}.defect-overview p{margin:0;color:var(--muted);line-height:1.55}.defect-total{display:inline-flex;align-items:center;gap:7px;margin-top:13px;padding:7px 10px;border-radius:999px;background:#edf4e9;color:var(--forest);font-size:12px;font-weight:850}.defect-stats{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.defect-stat{appearance:none;border:1px solid var(--line);border-radius:17px;background:#fff;padding:13px 9px;text-align:left;color:inherit;box-shadow:0 7px 20px rgba(25,64,45,.05)}.defect-stat span{display:flex;align-items:center;gap:6px;color:var(--muted);font-size:11px;font-weight:800}.defect-stat strong{display:block;margin-top:5px;font-size:27px;color:var(--forest)}.defect-stat i{width:9px;height:9px;border-radius:50%;display:inline-block}.defect-stat[data-stat="open"] i{background:#b64a42}.defect-stat[data-stat="progress"] i{background:#d49324}.defect-stat[data-stat="done"] i{background:#287052}.defect-stat.active{outline:2px solid var(--forest);outline-offset:1px}
.defect-filter-card{min-width:0;padding:14px;border:1px solid var(--line);border-radius:20px;background:#fff;box-shadow:0 8px 24px rgba(25,64,45,.05);overflow:hidden}.defect-filter-row{display:flex;align-items:center;gap:8px;overflow-x:auto;scrollbar-width:none;padding:1px;max-width:100%}.defect-filter-row+.defect-filter-row{margin-top:9px;padding-top:10px;border-top:1px solid #edf0e9}.defect-filter-row::-webkit-scrollbar{display:none}.defect-filter-label{flex:0 0 auto;color:var(--muted);font-size:11px;font-weight:900;text-transform:uppercase;letter-spacing:.06em;margin-right:2px}.defect-filter{flex:0 0 auto;border:1px solid #dce4d8;border-radius:999px;background:#f8faf6;color:#4a5e52;padding:8px 11px;font-size:12px;font-weight:850}.defect-filter.active{border-color:var(--forest);background:var(--forest);color:#fff}
.defect-map-card{position:relative;isolation:isolate;contain:layout paint;min-width:0;overflow:hidden;border:1px solid var(--line);border-radius:24px;background:#fff;box-shadow:0 13px 34px rgba(25,64,45,.08)}.defect-map-toolbar{position:relative;z-index:5;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:13px 14px;border-bottom:1px solid var(--line);background:#fff}.defect-map-toolbar strong{display:block;color:var(--forest)}.defect-map-toolbar small{display:block;margin-top:2px;color:var(--muted)}.defect-map-actions{display:flex;gap:7px;flex-wrap:wrap;justify-content:flex-end}.defect-map-action{border:1px solid #d8e2d4;border-radius:12px;background:#f7faf5;color:var(--forest);padding:8px 10px;font-size:12px;font-weight:850;min-height:42px}.defect-map-stage{position:relative;isolation:isolate;overflow:hidden;width:100%;height:clamp(390px,58vh,540px);background:#eaf0e7}.defect-map-stage #public-map{position:absolute;inset:0;width:100%;height:100%;min-width:0;overflow:hidden}.defect-map-stage .maplibregl-map,.defect-map-stage .maplibregl-canvas-container,.defect-map-stage .maplibregl-canvas{max-width:none!important}.defect-map-stage .maplibregl-map{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;overflow:hidden!important}.defect-map-stage .maplibregl-canvas{position:absolute!important;inset:0!important}.defect-map-stage .maplibregl-control-container{position:absolute;inset:0;pointer-events:none}.defect-map-stage .maplibregl-ctrl{pointer-events:auto}.defect-map-stage .maplibregl-ctrl-top-right{top:10px;right:10px}.defect-map-stage .maplibregl-ctrl-group{border-radius:12px;overflow:hidden;box-shadow:0 4px 14px rgba(20,42,30,.15)}.defect-map-stage .maplibregl-ctrl-attrib{font-size:9px;background:rgba(255,255,255,.9)}.defect-map-legend{position:absolute;z-index:4;left:10px;top:10px;display:flex;gap:5px;flex-wrap:wrap;max-width:calc(100% - 80px);pointer-events:none}.defect-map-legend span{display:inline-flex;align-items:center;gap:5px;padding:5px 8px;border:1px solid rgba(255,255,255,.78);border-radius:999px;background:rgba(255,255,255,.94);box-shadow:0 3px 12px rgba(0,0,0,.09);font-size:10px;font-weight:850;color:#425248}.defect-map-legend i{width:8px;height:8px;border-radius:50%}.defect-map-note{position:relative;z-index:5;padding:11px 14px;border-top:1px solid var(--line);background:#fbfcf9;color:var(--muted);font-size:11px;line-height:1.45}
.defect-detail{position:absolute;z-index:6;left:10px;right:10px;bottom:10px;max-height:55%;overflow:auto;padding:15px 16px;border:1px solid rgba(34,72,52,.14);border-radius:20px;background:rgba(255,255,255,.97);box-shadow:0 14px 36px rgba(19,48,32,.22);backdrop-filter:blur(10px)}.defect-detail[hidden]{display:none!important}.defect-detail-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.defect-detail h3{margin:3px 0 0;color:var(--forest);font-size:18px}.defect-detail-close{width:34px;height:34px;flex:0 0 34px;border:0;border-radius:11px;background:#edf2e9;color:var(--forest);font-size:19px}.defect-detail-meta{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0}.defect-detail p{margin:0;color:#526159;line-height:1.48;font-size:13px}.defect-status-chip,.defect-meta-chip{display:inline-flex;align-items:center;gap:5px;padding:5px 8px;border-radius:999px;font-size:10px;font-weight:900}.defect-status-chip.open{background:#f8e5e2;color:#8d332e}.defect-status-chip.progress{background:#fff0d2;color:#855c12}.defect-status-chip.done{background:#dff1e4;color:#226640}.defect-meta-chip{background:#eef3eb;color:#53655a}
.defect-list-card{min-width:0;padding:16px;border:1px solid var(--line);border-radius:22px;background:#fff;box-shadow:0 10px 28px rgba(25,64,45,.06)}.defect-list-head{display:flex;align-items:end;justify-content:space-between;gap:10px;margin-bottom:10px}.defect-list-head h2{margin:0;color:var(--forest);font-size:19px}.defect-list-head small{color:var(--muted)}.defect-list{display:grid;gap:8px}.defect-list-item{width:100%;display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:11px;align-items:center;padding:11px 12px;border:1px solid #e4e9e1;border-radius:15px;background:#fbfcfa;text-align:left;color:inherit}.defect-list-icon{width:39px;height:39px;display:grid;place-items:center;border-radius:13px;background:#edf3e9;font-size:18px}.defect-list-copy{min-width:0}.defect-list-copy strong{display:block;color:#294c39;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.defect-list-copy span{display:block;margin-top:2px;color:var(--muted);font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.defect-list-side{display:grid;justify-items:end;gap:5px}.defect-empty{padding:20px;border:1px dashed #d7dfd3;border-radius:16px;background:#fafbf8;text-align:center;color:var(--muted)}
@media(max-width:760px){.defect-overview{grid-template-columns:1fr;padding:16px}.defect-stats{grid-template-columns:repeat(3,minmax(0,1fr))}.defect-stat{padding:11px 8px}.defect-stat strong{font-size:23px}.defect-map-toolbar{align-items:flex-start;flex-direction:column}.defect-map-actions{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));width:100%;gap:7px}.defect-map-action{width:100%;padding:8px 6px}.defect-map-stage{height:min(52vh,470px);min-height:390px}.defect-list-item{grid-template-columns:auto minmax(0,1fr)}.defect-list-side{grid-column:2;justify-items:start;grid-auto-flow:column;justify-content:start}.defect-map-legend{right:58px;max-width:none}.defect-map-stage .maplibregl-ctrl-top-right{top:52px}.defect-detail{left:8px;right:8px;bottom:8px}}
@media(max-width:430px){.defect-map-stage{height:400px;min-height:400px}.defect-map-actions{grid-template-columns:1fr 1fr 1fr}.defect-map-action{font-size:11px}.defect-map-legend span{font-size:9px;padding:5px 7px}}
</style>
<section class="page-heading compact"><a class="back-link" href="/">← Zurück</a><span class="eyebrow">Bürger-Service</span><h1>Öffentliche Mängelkarte</h1><p>Anonymisierte Meldungen aus __MUNICIPALITY__ im Überblick. Positionen sind bewusst nur ungefähr dargestellt.</p></section>
<div class="defect-map-view">
  <section class="defect-overview">
    <div><span class="eyebrow">Aktueller Überblick</span><h2>Was ist gerade gemeldet?</h2><p>Filtere nach Bearbeitungsstand oder Kategorie und tippe eine Meldung auf der Karte oder in der Liste an.</p><span class="defect-total"><span id="defect-total">0</span> Meldungen mit Kartenposition</span></div>
    <div class="defect-stats" aria-label="Meldungen nach Status">
      <button class="defect-stat" type="button" data-stat="open"><span><i></i>Offen</span><strong id="stat-open">0</strong></button>
      <button class="defect-stat" type="button" data-stat="progress"><span><i></i>In Bearbeitung</span><strong id="stat-progress">0</strong></button>
      <button class="defect-stat" type="button" data-stat="done"><span><i></i>Erledigt</span><strong id="stat-done">0</strong></button>
    </div>
  </section>
  <section class="defect-filter-card" aria-label="Mängelkarte filtern">
    <div class="defect-filter-row"><span class="defect-filter-label">Status</span><button class="defect-filter active" type="button" data-status-filter="all">Alle</button><button class="defect-filter" type="button" data-status-filter="open">Offen</button><button class="defect-filter" type="button" data-status-filter="progress">In Bearbeitung</button><button class="defect-filter" type="button" data-status-filter="done">Erledigt</button></div>
    <div class="defect-filter-row" id="defect-category-filters"><span class="defect-filter-label">Kategorie</span></div>
  </section>
  <section class="defect-map-card">
    <div class="defect-map-toolbar"><div><strong>Karte __MUNICIPALITY__</strong><small id="defect-map-state">Öffentliche, gerundete Positionen</small></div><div class="defect-map-actions"><button class="defect-map-action" id="map-center" type="button">◎ Zentrieren</button><button class="defect-map-action" id="map-locate" type="button">⌖ Mein Standort</button><button class="defect-map-action" id="map-reload" type="button">↻ Neu laden</button></div></div>
    <div class="defect-map-stage"><div id="public-map" aria-label="Öffentliche Mängelkarte von __MUNICIPALITY__"></div><div class="defect-map-legend"><span><i style="background:#b64a42"></i>Offen</span><span><i style="background:#d49324"></i>In Bearbeitung</span><span><i style="background:#287052"></i>Erledigt</span></div><aside class="defect-detail" id="defect-detail" hidden aria-live="polite"><div class="defect-detail-head"><div><span class="eyebrow" id="detail-category">Meldung</span><h3 id="detail-title">Meldung</h3></div><button class="defect-detail-close" id="detail-close" type="button" aria-label="Detail schließen">×</button></div><div class="defect-detail-meta"><span class="defect-status-chip" id="detail-status"></span><span class="defect-meta-chip" id="detail-location"></span><span class="defect-meta-chip" id="detail-date"></span></div><p id="detail-description"></p></aside></div>
    <div class="defect-map-note">Datenschutz: GPS-Positionen werden vor der Veröffentlichung gerundet. Hausnummern, Namen, Kontaktdaten, interne Notizen und private Fotos werden nicht veröffentlicht. Der Marker zeigt daher keinen exakten Standort.</div>
  </section>
  <section class="defect-list-card"><div class="defect-list-head"><div><span class="eyebrow">Kartenausschnitt</span><h2>Sichtbare Meldungen</h2></div><small id="defect-visible-count">0 sichtbar</small></div><div class="defect-list" id="defect-list"><div class="defect-empty">Meldungen werden geladen …</div></div></section>
</div>
<script src="https://unpkg.com/maplibre-gl@5.24.0/dist/maplibre-gl.js"></script>
<script>
(() => {
  const rawPoints = __POINTS__.map((point,index)=>({...point,_key:String(point.id || `p-${index}`)}));
  const center = [__CENTER_LON__, __CENTER_LAT__];
  const defaultZoom = __CENTER_ZOOM__;
  const state = {status:'all',category:'all'};
  let userMarker = null;
  const userAccuracyId = 'user-location-accuracy';
  const esc = value => String(value ?? '').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const normal = value => String(value || '').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
  const statusKey = value => { const v=normal(value); if(v.includes('erledigt')||v.includes('geschlossen')||v.includes('behoben')) return 'done'; if(v.includes('bearbeit')||v.includes('pruf')||v.includes('weitergeleitet')) return 'progress'; return 'open'; };
  const statusLabel = key => key==='done'?'Erledigt':key==='progress'?'In Bearbeitung':'Offen';
  const glyph = category => { const v=normal(category); if(v.includes('licht')||v.includes('laterne')||v.includes('beleucht')) return '💡'; if(v.includes('mull')||v.includes('abfall')) return '♻'; if(v.includes('strasse')||v.includes('straße')||v.includes('schlagloch')||v.includes('gehweg')) return '◆'; if(v.includes('schild')||v.includes('verkehr')) return '△'; if(v.includes('grun')||v.includes('baum')||v.includes('hecke')) return '❧'; return '!'; };
  const pointDate = p => { const time=Date.parse(p.date||''); return Number.isFinite(time)?time:0; };
  const filtered = () => rawPoints.filter(p => (state.status==='all'||statusKey(p.status)===state.status) && (state.category==='all'||p.category===state.category));
  const geojson = items => ({type:'FeatureCollection',features:items.map(p=>({type:'Feature',id:p._key,properties:{key:p._key,status:statusKey(p.status),category:p.category||'Meldung',ort:p.ort||'__MUNICIPALITY__',date_label:p.date_label||'',glyph:glyph(p.category),date:p.date||''},geometry:{type:'Point',coordinates:[Number(p.lon),Number(p.lat)]}}))});

  if (typeof maplibregl === 'undefined') {
    document.getElementById('defect-map-state').textContent='Kartenmodul konnte nicht geladen werden';
    document.getElementById('public-map').innerHTML='<div class="defect-empty" style="margin:16px">Die Karte konnte nicht geladen werden. Bitte Internetverbindung prüfen und die Seite neu öffnen.</div>';
    return;
  }

  const map = new maplibregl.Map({container:'public-map',style:'https://tiles.openfreemap.org/styles/liberty',center,zoom:defaultZoom,minZoom:11,maxZoom:19,attributionControl:true,cooperativeGestures:true,pitchWithRotate:false,dragRotate:false,touchPitch:false,fadeDuration:0});
  map.addControl(new maplibregl.NavigationControl({showCompass:false,showZoom:true}),'top-right');

  const showDetailByKey = key => { const p=rawPoints.find(item=>item._key===String(key)); if(!p) return; const sk=statusKey(p.status); document.getElementById('detail-category').textContent=p.category||'Meldung'; document.getElementById('detail-title').textContent=p.category||'Meldung'; const status=document.getElementById('detail-status'); status.className=`defect-status-chip ${sk}`; status.textContent=statusLabel(sk); document.getElementById('detail-location').textContent=`📍 ${p.ort||'__MUNICIPALITY__'}`; document.getElementById('detail-date').textContent=p.date_label?`📅 ${p.date_label}`:'📅 Datum nicht verfügbar'; document.getElementById('detail-description').textContent='Der freie Meldetext bleibt aus Datenschutzgründen nicht öffentlich. Kategorie, Bearbeitungsstand, Datum und ungefährer Ort sind hier sichtbar.'; document.getElementById('defect-detail').hidden=false; };
  const hideDetail = () => { document.getElementById('defect-detail').hidden=true; };
  const boundsFor = items => { if(!items.length) return null; const bounds=new maplibregl.LngLatBounds(); items.forEach(p=>bounds.extend([Number(p.lon),Number(p.lat)])); return bounds; };
  const updateMapSource = (fit=false) => { const items=filtered(); const source=map.getSource('reports'); if(source) source.setData(geojson(items)); document.getElementById('defect-map-state').textContent=`${items.length} Meldung${items.length===1?'':'en'} im aktuellen Filter · Positionen gerundet`; if(fit && items.length){ const bounds=boundsFor(items); map.fitBounds(bounds,{padding:55,maxZoom:15,duration:450}); } renderVisibleList(); hideDetail(); };
  const renderVisibleList = () => { if(!map.loaded()) return; const bounds=map.getBounds(); const items=filtered().filter(p=>bounds.contains([Number(p.lon),Number(p.lat)])).sort((a,b)=>pointDate(b)-pointDate(a)); const list=document.getElementById('defect-list'); document.getElementById('defect-visible-count').textContent=`${items.length} sichtbar`; if(!items.length){ list.innerHTML='<div class="defect-empty"><strong>Keine Meldung im aktuellen Kartenausschnitt.</strong><br>Zoome heraus oder ändere den Filter.</div>'; return; } list.innerHTML=items.map(p=>{ const sk=statusKey(p.status); return `<button class="defect-list-item" type="button" data-point-key="${esc(p._key)}"><span class="defect-list-icon">${glyph(p.category)}</span><span class="defect-list-copy"><strong>${esc(p.category||'Meldung')}</strong><span>${esc(p.ort||'__MUNICIPALITY__')}</span></span><span class="defect-list-side"><span class="defect-status-chip ${sk}">${statusLabel(sk)}</span><span class="defect-meta-chip">${esc(p.date_label||'ohne Datum')}</span></span></button>`; }).join(''); list.querySelectorAll('[data-point-key]').forEach(button=>button.addEventListener('click',()=>focusPoint(button.dataset.pointKey))); };
  const focusPoint = key => { const p=rawPoints.find(item=>item._key===String(key)); if(!p) return; map.easeTo({center:[Number(p.lon),Number(p.lat)],zoom:Math.max(map.getZoom(),16),duration:450}); showDetailByKey(key); };
  const setStatus = key => { state.status=key; document.querySelectorAll('[data-status-filter]').forEach(b=>b.classList.toggle('active',b.dataset.statusFilter===key)); document.querySelectorAll('[data-stat]').forEach(b=>b.classList.toggle('active',key!=='all'&&b.dataset.stat===key)); updateMapSource(true); };
  const setCategory = category => { state.category=category; document.querySelectorAll('[data-category-filter]').forEach(b=>b.classList.toggle('active',b.dataset.categoryFilter===category)); updateMapSource(true); };

  const counts={open:0,progress:0,done:0}; rawPoints.forEach(p=>counts[statusKey(p.status)]++); document.getElementById('stat-open').textContent=counts.open; document.getElementById('stat-progress').textContent=counts.progress; document.getElementById('stat-done').textContent=counts.done; document.getElementById('defect-total').textContent=rawPoints.length;
  document.querySelectorAll('[data-status-filter]').forEach(button=>button.addEventListener('click',()=>setStatus(button.dataset.statusFilter))); document.querySelectorAll('[data-stat]').forEach(button=>button.addEventListener('click',()=>setStatus(state.status===button.dataset.stat?'all':button.dataset.stat)));
  const categoryWrap=document.getElementById('defect-category-filters'); const allCategory=document.createElement('button'); allCategory.className='defect-filter active'; allCategory.type='button'; allCategory.dataset.categoryFilter='all'; allCategory.textContent='Alle'; categoryWrap.appendChild(allCategory); [...new Set(rawPoints.map(p=>p.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'de')).forEach(category=>{ const button=document.createElement('button'); button.className='defect-filter'; button.type='button'; button.dataset.categoryFilter=category; button.textContent=category; categoryWrap.appendChild(button); }); categoryWrap.querySelectorAll('[data-category-filter]').forEach(button=>button.addEventListener('click',()=>setCategory(button.dataset.categoryFilter)));

  map.on('load',()=>{
    map.addSource('reports',{type:'geojson',data:geojson(filtered()),cluster:true,clusterMaxZoom:14,clusterRadius:46});
    map.addLayer({id:'report-clusters',type:'circle',source:'reports',filter:['has','point_count'],paint:{'circle-color':'#174936','circle-radius':['step',['get','point_count'],18,10,22,25,26],'circle-stroke-width':3,'circle-stroke-color':'#ffffff','circle-opacity':.94}});
    map.addLayer({id:'report-cluster-count',type:'symbol',source:'reports',filter:['has','point_count'],layout:{'text-field':['get','point_count_abbreviated'],'text-size':12},paint:{'text-color':'#ffffff'}});
    map.addLayer({id:'report-points',type:'circle',source:'reports',filter:['!', ['has','point_count']],paint:{'circle-radius':10,'circle-color':['match',['get','status'],'done','#287052','progress','#d49324','#b64a42'],'circle-stroke-width':3,'circle-stroke-color':'#ffffff'}});
    map.addLayer({id:'report-point-symbol',type:'symbol',source:'reports',filter:['!', ['has','point_count']],layout:{'text-field':['get','glyph'],'text-size':13,'text-allow-overlap':true},paint:{'text-color':'#ffffff'}});
    map.on('click','report-clusters',async e=>{ const feature=e.features&&e.features[0]; if(!feature) return; const clusterId=feature.properties.cluster_id; const source=map.getSource('reports'); try{ const zoom=await source.getClusterExpansionZoom(clusterId); map.easeTo({center:feature.geometry.coordinates,zoom,duration:350}); }catch(_){ } });
    map.on('click','report-points',e=>{ const feature=e.features&&e.features[0]; if(feature) showDetailByKey(feature.properties.key); });
    map.on('mouseenter','report-clusters',()=>map.getCanvas().style.cursor='pointer'); map.on('mouseleave','report-clusters',()=>map.getCanvas().style.cursor=''); map.on('mouseenter','report-points',()=>map.getCanvas().style.cursor='pointer'); map.on('mouseleave','report-points',()=>map.getCanvas().style.cursor='');
    if(rawPoints.length){ const bounds=boundsFor(rawPoints); map.fitBounds(bounds,{padding:55,maxZoom:15,duration:0}); }
    setTimeout(()=>{map.resize();renderVisibleList();},80);
  });
  map.on('moveend',renderVisibleList);
  map.on('click',e=>{ const features=map.queryRenderedFeatures(e.point,{layers:['report-points','report-clusters']}); if(!features.length) hideDetail(); });
  map.on('error',e=>{ if(e&&e.error) console.warn('MapLibre:',e.error); });

  const resizeMap=()=>requestAnimationFrame(()=>map.resize()); window.addEventListener('resize',resizeMap,{passive:true}); window.addEventListener('orientationchange',()=>setTimeout(resizeMap,180),{passive:true}); document.addEventListener('visibilitychange',()=>{if(!document.hidden)setTimeout(resizeMap,80);}); window.addEventListener('pageshow',()=>setTimeout(resizeMap,80));
  document.getElementById('detail-close').addEventListener('click',hideDetail); document.getElementById('map-center').addEventListener('click',()=>{map.easeTo({center,zoom:defaultZoom,duration:350});hideDetail();}); document.getElementById('map-reload').addEventListener('click',()=>window.location.reload());
  document.getElementById('map-locate').addEventListener('click',()=>{ const button=document.getElementById('map-locate'); if(!navigator.geolocation){button.textContent='Standort nicht verfügbar';return;} button.disabled=true; button.textContent='⌖ Wird ermittelt …'; navigator.geolocation.getCurrentPosition(position=>{ const lat=position.coords.latitude,lon=position.coords.longitude,accuracy=Math.min(Math.max(position.coords.accuracy||30,20),400); if(userMarker) userMarker.remove(); userMarker=new maplibregl.Marker({color:'#2767a6'}).setLngLat([lon,lat]).setPopup(new maplibregl.Popup({offset:18}).setText('Dein Standort')).addTo(map); const point={type:'Feature',geometry:{type:'Point',coordinates:[lon,lat]},properties:{}}; if(map.getSource(userAccuracyId)){map.getSource(userAccuracyId).setData(point);}else{ map.addSource(userAccuracyId,{type:'geojson',data:point}); map.addLayer({id:userAccuracyId+'-halo',type:'circle',source:userAccuracyId,paint:{'circle-radius':Math.max(10,Math.min(36,accuracy/6)),'circle-color':'#2767a6','circle-opacity':.12,'circle-stroke-width':1,'circle-stroke-color':'#2767a6'}}); } map.easeTo({center:[lon,lat],zoom:16,duration:450}); button.disabled=false;button.textContent='⌖ Mein Standort'; },()=>{button.disabled=false;button.textContent='⌖ Nicht verfügbar';setTimeout(()=>button.textContent='⌖ Mein Standort',2200);},{enableHighAccuracy:false,timeout:10000,maximumAge:60000}); });
})();
</script>
"""


def public_map_page(points: list[dict]) -> HTMLResponse:
    cfg = get_platform_snapshot()
    safe_points = json.dumps(points, ensure_ascii=False).replace("</", "<\\/")
    try:
        center_lat = float(cfg.get("map_lat") or 52.258)
        center_lon = float(cfg.get("map_lon") or 9.099)
        center_zoom = int(cfg.get("map_zoom") or 15)
    except (TypeError, ValueError):
        center_lat, center_lon, center_zoom = 52.258, 9.099, 15
    municipality = escape(cfg.get("municipality_name") or "Ahnsen")
    html = (
        _PUBLIC_MAP_TEMPLATE
        .replace("__POINTS__", safe_points)
        .replace("__MUNICIPALITY__", municipality)
        .replace("__CENTER_LAT__", f"{center_lat:.6f}")
        .replace("__CENTER_LON__", f"{center_lon:.6f}")
        .replace("__CENTER_ZOOM__", str(center_zoom))
    )
    return page("Mängelkarte", COMMUNITY_CSS + html, active="home", body_class="community-view")


'''

path.write_text(text[:start] + new_block + text[end:], encoding='utf-8')
