'use strict';
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(process.cwd(),'pantrypilot-production');
function patch(rel, fn){const p=path.join(root,rel);const before=fs.readFileSync(p,'utf8');const after=fn(before);if(after===before)throw new Error(`Patch produced no change: ${rel}`);fs.writeFileSync(p,after);console.log(`patched ${rel}`)}
function replaceOnce(s, from, to, label){if(!s.includes(from))throw new Error(`Patch target not found: ${label}`);return s.replace(from,to)}
patch('public/app.js',s=>{
  s=replaceOnce(s,`function bindCommon(){\n  $$('[data-nav]').forEach(b=>{b.onclick=()=>nav(b.dataset.nav)});\n}`,
`function bindCommon(){\n  $$('[data-nav]').forEach(b=>{b.onclick=()=>nav(b.dataset.nav)});\n  // Rezeptkarten koennen in mehreren Ansichten vorkommen, auch auf der Startseite.\n  bindRecipeCards();\n  bindAiRecipeCards();\n}`,'bindCommon recipe handlers');
  const oldBlock=`async function requestAiRecipes(mode){\n  if(aiBusy)return;\n  if(!cloud?.token){toast('Verbinde zuerst den Familienhaushalt in den Einstellungen, damit die Server-KI genutzt werden kann.');return}\n  if(!serverConfig.aiEnabled){toast('Für echte KI-Rezepte muss OPENAI_API_KEY bei Render gesetzt sein.');return}\n  aiBusy=true;const btn=$('#aiRecipeBtn');if(btn){btn.disabled=true;btn.textContent='✨ KI denkt …'}\n  try{\n    const request=$('#aiCookRequest')?.value?.trim()||'';\n    const inventory=activeItems().map(({photo,...i})=>i);\n    const data=await apiFetch('/api/ai/recipes',{method:'POST',body:JSON.stringify({mode,request,inventory,settings:state.settings})});\n    if(mode==='rescue')state.aiRecipesRescue=data.recipes||[];else state.aiRecipesCook=data.recipes||[];\n    await saveState();toast('Neue KI-Gerichte sind bereit.');render();\n  }catch(err){toast(err.status===503?'KI ist auf dem Server noch nicht aktiviert.':'KI-Gerichte konnten gerade nicht erstellt werden.');if(btn){btn.disabled=false;btn.textContent='✨ KI-Gerichte erstellen'}}\n  finally{aiBusy=false}\n}`;
  const newBlock=`async function requestAiRecipes(mode){\n  if(aiBusy)return;\n  if(!cloud?.token){toast('Verbinde zuerst den Familienhaushalt in den Einstellungen, damit die Server-KI genutzt werden kann.');return}\n  if(!serverConfig.aiEnabled){toast('Für echte KI-Rezepte muss OPENAI_API_KEY bei Render gesetzt sein.');return}\n  aiBusy=true;const btn=$('#aiRecipeBtn');const originalText=btn?.textContent||'✨ KI-Gerichte erstellen';if(btn){btn.disabled=true;btn.textContent='✨ KI denkt …'}\n  try{\n    const request=$('#aiCookRequest')?.value?.trim()||'';\n    const inventory=activeItems().map(({photo,...i})=>i);\n    const data=await apiFetch('/api/ai/recipes',{method:'POST',body:JSON.stringify({mode,request,inventory,settings:state.settings})});\n    if(mode==='rescue')state.aiRecipesRescue=data.recipes||[];else state.aiRecipesCook=data.recipes||[];\n    await saveState();toast('Neue KI-Gerichte sind bereit.');render();\n  }catch(err){\n    const code=err?.data?.error||'';\n    const messages={\n      ai_disabled:'KI ist auf dem Server noch nicht aktiviert.',\n      openai_auth:'Der OpenAI-API-Key wird abgelehnt. Bitte den Key bei Render prüfen.',\n      openai_quota:'OpenAI meldet kein verfügbares API-Guthaben/Kontingent. Bitte API-Billing prüfen.',\n      openai_forbidden:'Der API-Key hat keinen Zugriff auf das eingestellte KI-Modell.',\n      openai_bad_request:'Die KI-Anfrage wurde von OpenAI abgelehnt. PantryPilot hat den Fehler protokolliert.',\n      openai_timeout:'Die KI hat zu lange gebraucht. Bitte erneut versuchen.'\n    };\n    toast(messages[code]||err?.data?.message||'KI-Gerichte konnten gerade nicht erstellt werden.');\n    console.warn('KI-Rezeptfehler',err?.status,err?.data||err);\n    if(btn){btn.disabled=false;btn.textContent=originalText}\n  }finally{aiBusy=false}\n}`;
  return replaceOnce(s,oldBlock,newBlock,'AI recipe frontend errors');
});
patch('server.js',s=>{
  const oldBlock=`app.post('/api/ai/recipes', authRequired, aiLimiter, async (req, res) => {\n  try {\n    const mode = req.body?.mode === 'rescue' ? 'rescue' : 'cook';\n    const recipes = await generateRecipes({ inventory: req.body?.inventory, settings: req.body?.settings, mode, request: req.body?.request });\n    res.json({ recipes });\n  } catch (err) {\n    console.warn('AI recipes error', err?.message || err);\n    res.status(err.status || 502).json({ error: err.code || 'ai_recipe_failed', message: 'Die KI-Rezepte konnten gerade nicht erstellt werden.' });\n  }\n});`;
  const newBlock=`app.post('/api/ai/recipes', authRequired, aiLimiter, async (req, res) => {\n  try {\n    const mode = req.body?.mode === 'rescue' ? 'rescue' : 'cook';\n    const recipes = await generateRecipes({ inventory: req.body?.inventory, settings: req.body?.settings, mode, request: req.body?.request });\n    res.json({ recipes });\n  } catch (err) {\n    const status = Number(err?.status || 502);\n    const upstreamCode = String(err?.code || err?.error?.code || '');\n    let error = upstreamCode || 'ai_recipe_failed';\n    let message = 'Die KI-Rezepte konnten gerade nicht erstellt werden.';\n    if (status === 503 && upstreamCode === 'ai_disabled') { error='ai_disabled'; message='KI ist auf diesem Server noch nicht aktiviert.'; }\n    else if (status === 401) { error='openai_auth'; message='Der OpenAI-API-Key wurde abgelehnt.'; }\n    else if (status === 429) { error='openai_quota'; message='OpenAI meldet kein verfügbares API-Guthaben oder Kontingent.'; }\n    else if (status === 403) { error='openai_forbidden'; message='Der API-Key hat keinen Zugriff auf das eingestellte Modell.'; }\n    else if (status === 400) { error='openai_bad_request'; message='OpenAI hat die Rezeptanfrage als ungültig abgelehnt.'; }\n    else if (status === 408 || status === 504) { error='openai_timeout'; message='Die KI-Anfrage hat zu lange gedauert.'; }\n    console.warn('AI recipes error', { status, code: upstreamCode, type: err?.type, message: err?.message });\n    res.status(status >= 400 && status < 600 ? status : 502).json({ error, message });\n  }\n});`;
  return replaceOnce(s,oldBlock,newBlock,'AI recipe server errors');
});
patch('public/sw.js',s=>replaceOnce(s,"const CACHE='pantrypilot-v3';","const CACHE='pantrypilot-v4';",'service worker cache'));
patch('public/index.html',s=>{
  s=replaceOnce(s,'href="styles.css"','href="styles.css?v=4"','styles cache bust');
  return replaceOnce(s,'src="app.js"','src="app.js?v=4"','app cache bust');
});
