import { chromium } from 'playwright';
import assert from 'node:assert/strict';

const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:390,height:844},locale:'de-DE'}),page=await context.newPage(),errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
try{
  await page.goto('http://127.0.0.1:8080/',{waitUntil:'domcontentloaded'});const setup=page.locator('#newProjectForm');await setup.waitFor({state:'visible',timeout:12000});await setup.locator('[name="household"]').fill('Quality Haushalt');await setup.locator('[name="accountName"]').fill('Giro');await setup.locator('[name="balance"]').fill('900');await setup.locator('button.primary-button').click();await page.locator('#modalBackdrop').waitFor({state:'hidden'});
  assert.equal(await page.getAttribute('html','lang'),'de');assert.equal(await page.locator('.skip-link').count(),1);assert.equal(await page.locator('#mainContent').getAttribute('tabindex'),'-1');
  const duplicateIds=await page.evaluate(()=>{const m=new Map;for(const el of document.querySelectorAll('[id]'))m.set(el.id,(m.get(el.id)||0)+1);return [...m].filter(([,n])=>n>1)});assert.deepEqual(duplicateIds,[]);
  const unnamedButtons=await page.evaluate(()=>[...document.querySelectorAll('button')].filter(b=>{const s=getComputedStyle(b);if(s.display==='none'||s.visibility==='hidden')return false;return!(b.getAttribute('aria-label')||b.getAttribute('title')||b.textContent.trim())}).map(b=>b.outerHTML));if(unnamedButtons.length)console.error('Unnamed visible buttons:',JSON.stringify(unnamedButtons));assert.deepEqual(unnamedButtons,[]);
  await page.locator('#quickAddMobile').click();await page.locator('[data-q="expense"]').click();const form=page.locator('#txForm');const unlabeled=await form.evaluate(f=>[...f.querySelectorAll('input,select,textarea')].filter(el=>{if(el.type==='hidden'||getComputedStyle(el).display==='none')return false;if(el.getAttribute('aria-label')||el.getAttribute('aria-labelledby'))return false;const id=el.id;if(id&&f.querySelector(`label[for="${CSS.escape(id)}"]`))return false;return !el.closest('.field')?.querySelector('label')}).map(x=>x.name||x.id||x.type));assert.deepEqual(unlabeled,[]);await form.locator('[data-cancel]').click();
  const reduced=await page.evaluate(async()=>{const txt=await (await fetch('./styles-v3.css')).text();return txt.includes('prefers-reduced-motion')});assert.equal(reduced,true);
  await page.evaluate(async()=>{await navigator.serviceWorker.ready;await new Promise(r=>setTimeout(r,300))});await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>navigator.serviceWorker.controller&&globalThis.FinanzV3?.version==='3.2.0',null,{timeout:12000});await context.setOffline(true);await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>globalThis.FinanzV3?.version==='3.2.0'&&data.accounts?.length===1,null,{timeout:12000});assert.equal(await page.locator('#pageTitle').textContent(),'Übersicht');await context.setOffline(false);
  if(errors.length)throw new Error(errors.join('\n'));console.log('V3 accessibility/offline quality: OK');
}finally{await browser.close()}
