(() => {
'use strict';

// Bürgermeister 2026 – Simulation v5
const $ = s => document.querySelector(s);
const moneyFmt = n => new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Math.round(n));
const numFmt = n => new Intl.NumberFormat('de-DE').format(Math.round(n));
const pct = n => `${Math.round(n)}%`;
const clamp = (v,min,max) => Math.max(min,Math.min(max,v));
const lerp = (a,b,t) => a+(b-a)*t;
const rand = (min,max) => Math.random()*(max-min)+min;
const monthNames = ['Jan','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez'];
const SAVE_KEY = 'buergermeister2026-save-v5';
const LEGACY_SAVE_KEYS = ['buergermeister2026-save-v4','buergermeister2026-save-v3','buergermeister2026-save-v2','buergermeister2026-save-v1'];
const GRID_W=18, GRID_H=14;
const TERM_MONTHS=48;
const MAX_PROJECTS=3;

const BUILDINGS={
 road:{name:'Straße',emoji:'🛣️',cost:18000,upkeep:145,buildMonths:0,jobs:0,capacity:0,happy:0,admin:.25,politics:0},
 house:{name:'Wohnquartier',emoji:'🏠',cost:175000,upkeep:1100,buildMonths:2,jobs:6,capacity:135,happy:1,propertyBase:6100,admin:1,politics:3},
 apartments:{name:'Mehrfamilienhäuser',emoji:'🏢',cost:465000,upkeep:3200,buildMonths:4,jobs:15,capacity:360,happy:-1,propertyBase:16500,admin:1.5,politics:6},
 shop:{name:'Ortszentrum',emoji:'🏪',cost:285000,upkeep:1900,buildMonths:3,jobs:80,capacity:0,happy:2,businessBase:10500,admin:1,politics:5},
 factory:{name:'Gewerbegebiet',emoji:'🏭',cost:690000,upkeep:4900,buildMonths:5,jobs:210,capacity:0,happy:-4,businessBase:28000,admin:2,politics:10},
 park:{name:'Park',emoji:'🌳',cost:115000,upkeep:780,buildMonths:1,jobs:4,capacity:0,happy:5,admin:.5,politics:2},
 kindergarten:{name:'Kita',emoji:'🧸',cost:760000,upkeep:11200,buildMonths:5,jobs:30,capacity:0,happy:5,service:'education',serviceCapacity:150,admin:2,politics:12},
 school:{name:'Schule',emoji:'🏫',cost:1750000,upkeep:24500,buildMonths:8,jobs:62,capacity:0,happy:7,service:'education',serviceCapacity:420,admin:3,politics:18},
 fire:{name:'Feuerwehr',emoji:'🚒',cost:1050000,upkeep:15200,buildMonths:6,jobs:29,capacity:0,happy:5,service:'safety',serviceCapacity:900,admin:2.5,politics:15},
 clinic:{name:'Gesundheitszentrum',emoji:'🏥',cost:1950000,upkeep:28500,buildMonths:8,jobs:75,capacity:0,happy:7,service:'health',serviceCapacity:1100,admin:3,politics:20},
 solar:{name:'Solarpark',emoji:'☀️',cost:410000,upkeep:1850,buildMonths:4,jobs:9,capacity:0,happy:2,energyBase:9200,admin:1.5,politics:7},
 townhall:{name:'Rathaus',emoji:'🏛️',cost:0,upkeep:12500,buildMonths:0,jobs:36,capacity:0,happy:2,unique:true,admin:0,politics:0}
};

const PROMISES={
 budget:{title:'Solide Finanzen',desc:'Strukturelles Defizit vermeiden und Verschuldung begrenzen.'},
 families:{title:'Familiengemeinde',desc:'Bildung, Wohnraum und Lebensqualität für Familien stärken.'},
 economy:{title:'Starke Wirtschaft',desc:'Arbeitsplätze schaffen und das Wirtschaftsklima verbessern.'},
 infrastructure:{title:'Verlässliche Infrastruktur',desc:'Straßen und Sicherheit auf hohem Niveau halten.'},
 climate:{title:'Grüne Gemeinde',desc:'Umweltqualität und erneuerbare Energie ausbauen.'},
 growth:{title:'Gesundes Wachstum',desc:'Bevölkerung nachhaltig steigern, ohne Versorgung zu überlasten.'}
};

const ISSUE_DEFS={
 housing:{title:'Wohnraummangel',icon:'🏠',months:8,desc:'Wohnraum ist fast vollständig ausgelastet.'},
 education:{title:'Bildung überlastet',icon:'🎒',months:7,desc:'Kita- und Schulkapazitäten reichen nicht aus.'},
 safety:{title:'Sicherheitslücke',icon:'🚒',months:7,desc:'Feuerwehr und Gefahrenabwehr sind unterdimensioniert.'},
 health:{title:'Gesundheitsversorgung kritisch',icon:'🏥',months:8,desc:'Die medizinische Grundversorgung ist unzureichend.'},
 roads:{title:'Sanierungsstau',icon:'🛣️',months:9,desc:'Straßen und Erschließung verschlechtern sich deutlich.'},
 jobs:{title:'Arbeitsmarkt schwach',icon:'💼',months:8,desc:'Zu viele Einwohner finden keine ausreichende Beschäftigung.'},
 deficit:{title:'Strukturelles Defizit',icon:'📉',months:6,desc:'Der laufende Haushalt ist über mehrere Monate tief im Minus.'},
 debt:{title:'Verschuldung zu hoch',icon:'🏦',months:10,desc:'Die Pro-Kopf-Verschuldung erreicht ein kritisches Niveau.'},
 trust:{title:'Vertrauenskrise',icon:'🗳️',months:6,desc:'Bürger und Rat verlieren das Vertrauen in deine Amtsführung.'},
 congestion:{title:'Verkehr überlastet',icon:'🚗',months:8,desc:'Das Straßennetz kann den Pendler- und Wirtschaftsverkehr kaum noch aufnehmen.'},
 disconnected:{title:'Abgehängtes Quartier',icon:'🔌',months:6,desc:'Ein bebautes Gebiet ist nicht zuverlässig mit dem Rathausnetz verbunden.'},
 pollution:{title:'Lokale Umweltbelastung',icon:'🌫️',months:8,desc:'Wohngebiete leiden unter zu hoher Gewerbe- und Verkehrsbelastung.'}
};

const EVENTS=[
 {title:'Starkregen und Straßenschäden',text:'Ein Unwetter beschädigt Straßen und Entwässerung.',choices:[
  {label:'Gründlich sanieren',detail:'120.000 € · Infrastruktur +8 · politisches Kapital +1',apply:s=>{s.money-=120000;s.infrastructure+=8;s.politicalCapital+=1;}},
  {label:'Nur Gefahrenstellen sichern',detail:'45.000 € · Infrastruktur +2 · Zustimmung -2',apply:s=>{s.money-=45000;s.infrastructure+=2;s.approval-=2;}}
 ]},
 {title:'Regionaler Betrieb sucht Standort',text:'Ein Unternehmen prüft die Ansiedlung und fordert gute Erschließung.',choices:[
  {label:'Ansiedlung aktiv begleiten',detail:'80.000 € · Wirtschaft +5 · private Jobs +70',apply:s=>{s.money-=80000;s.economy+=5;s.privateJobs+=70;s.businessMomentum+=4;}},
  {label:'Keine Sonderbehandlung',detail:'Kein Aufwand · Wirtschaft -2',apply:s=>{s.economy-=2;s.businessMomentum-=2;}}
 ]},
 {title:'Landeszuschuss Klimaanpassung',text:'Für Grünflächen, Entsiegelung und Hitzeschutz stehen Fördermittel bereit.',choices:[
  {label:'Programm nutzen',detail:'+140.000 € · Umwelt +4 · Verwaltung -1',apply:s=>{s.money+=140000;s.environment+=4;s.actionPoints=Math.max(0,s.actionPoints-1);}},
  {label:'Kapazität für anderes freihalten',detail:'Keine direkte Wirkung',apply:()=>{}}
 ]},
 {title:'Elterninitiative',text:'Eltern fordern bessere Betreuungs- und Bildungsangebote.',choices:[
  {label:'Temporäre Zusatzkapazität',detail:'65.000 € · Bildung kurzfristig +12 · 12 Monate Zusatzkosten',apply:s=>{s.money-=65000;s.tempEducation=12;s.tempEducationMonths=12;s.approval+=2;}},
  {label:'Auf Neubau verweisen',detail:'Zustimmung -3',apply:s=>{s.approval-=3;s.happiness-=1;}}
 ]},
 {title:'Kreis erhöht Umlage',text:'Der Landkreis kündigt eine höhere Umlage an.',choices:[
  {label:'Haushalt anpassen',detail:'Kreisumlage +1 Punkt · Ratsmehrheit +1',apply:s=>{s.levyModifier+=1;s.councilSupport+=1;}},
  {label:'Politisch dagegenhalten',detail:'Zustimmung +2 · Ratsmehrheit -2 · Umlage steigt trotzdem',apply:s=>{s.levyModifier+=1;s.approval+=2;s.councilSupport-=2;}}
 ]},
 {title:'Ärztemangel in der Region',text:'Eine Praxis schließt. Die Belastung der örtlichen Versorgung steigt.',choices:[
  {label:'Niederlassung fördern',detail:'95.000 € · Gesundheit +15 für 18 Monate',apply:s=>{s.money-=95000;s.tempHealth=15;s.tempHealthMonths=18;}},
  {label:'Regionale Lösung abwarten',detail:'Gesundheit -6 · Zufriedenheit -2',apply:s=>{s.healthShock=6;s.happiness-=2;}}
 ]},
 {title:'Energiepreise steigen',text:'Die Betriebskosten kommunaler Gebäude erhöhen sich vorübergehend.',choices:[
  {label:'Energie-Sparprogramm',detail:'45.000 € · Betriebskostenfaktor verbessert sich',apply:s=>{s.money-=45000;s.efficiencyBonus=Math.min(12,(s.efficiencyBonus||0)+4);}},
  {label:'Mehrkosten tragen',detail:'Keine Investition · Inflation +0,8',apply:s=>{s.inflation+=.8;}}
 ]},
 {title:'Jugendrat fordert Treffpunkt',text:'Jugendliche wünschen sich sichere öffentliche Aufenthaltsflächen.',choices:[
  {label:'Temporären Treffpunkt schaffen',detail:'55.000 € · Jugendzufriedenheit +8',apply:s=>{s.money-=55000;s.youthBonus=Math.min(18,(s.youthBonus||0)+8);}},
  {label:'Nicht priorisieren',detail:'Jugendzufriedenheit -8 · Zustimmung -1',apply:s=>{s.youthBonus=Math.max(-18,(s.youthBonus||0)-8);s.approval-=1;}}
 ]}
];

function seeded(x,y,s=0){let n=(x*374761393+y*668265263+s*1442695041)>>>0;n=(n^(n>>13))*1274126177>>>0;return ((n^(n>>16))>>>0)/4294967295;}
function emptyGrid(){return Array.from({length:GRID_H},()=>Array(GRID_W).fill(null));}

function baseStarterState(){
 const g=emptyGrid();
 for(let x=2;x<16;x++)g[7][x]={type:'road'};
 for(let y=3;y<12;y++)g[y][8]={type:'road'};
 for(let y=5;y<=9;y++)g[y][4]={type:'road'};g[6][6]={type:'road'};
 g[6][7]={type:'townhall'};
 g[5][5]={type:'house'};g[5][6]={type:'house'};g[8][5]={type:'house'};g[8][6]={type:'house'};g[4][9]={type:'house'};
 g[9][9]={type:'shop'};g[5][9]={type:'park'};g[8][9]={type:'kindergarten'};
 return {
  version:5,cityName:'Musterstadt',year:2026,month:0,monthsPlayed:0,termStartMonth:0,termStartPopulation:610,
  money:1250000,debt:0,interestRate:3.3,inflation:2.1,economy:56,businessMomentum:0,privateJobs:40,
  population:610,happiness:64,approval:62,councilSupport:60,politicalCapital:58,actionPoints:3,
  environment:59,infrastructure:64,levyModifier:0,roadBudget:100,serviceBudget:100,efficiencyBonus:0,
  taxRates:{property:400,business:380,fees:100},taxCooldown:0,
  grid:g,selected:'inspect',mapMode:'normal',speed:1,
  capitalSpentYear:0,capitalSpentLastYear:0,fiscalHistory:[],eventLog:[],electionsWon:0,gameOver:false,
  activeIssues:[],issueCooldowns:{},neglectedIssues:0,oversightLevel:0,consecutiveDeficitMonths:0,noConfidenceMonths:0,socialCrisisMonths:0,serviceCrisisMonths:0,infrastructureCrisisMonths:0,
  failedBudgets:0,lastBudgetVote:-12,mandate:['growth','families','infrastructure'],promiseHistory:[],victoryShown:false,
  tempEducation:0,tempEducationMonths:0,tempHealth:0,tempHealthMonths:0,healthShock:0,youthBonus:0,
  stats:{},objectives:{pop1500:false,happy75:false,balance:false,services:false}
 };
}

function normalizeState(raw){
 const b=baseStarterState(),s={...b,...(raw||{})};s.version=5;
 s.taxRates={...b.taxRates,...(raw?.taxRates||{})};
 if(s.taxRates.property<200)s.taxRates.property=Math.round(s.taxRates.property*4);
 if(s.taxRates.business<200)s.taxRates.business=Math.round(s.taxRates.business*3.8);
 s.stats={...b.stats,...(raw?.stats||{})};s.objectives={...b.objectives,...(raw?.objectives||{})};
 s.activeIssues=Array.isArray(s.activeIssues)?s.activeIssues:[];s.issueCooldowns=s.issueCooldowns||{};s.fiscalHistory=Array.isArray(s.fiscalHistory)?s.fiscalHistory:[];s.eventLog=Array.isArray(s.eventLog)?s.eventLog:[];
 s.mandate=Array.isArray(s.mandate)&&s.mandate.length?s.mandate:b.mandate;s.promiseHistory=Array.isArray(s.promiseHistory)?s.promiseHistory:[];
 s.grid=Array.isArray(s.grid)?s.grid:b.grid;
 const nums=['money','debt','interestRate','inflation','economy','population','happiness','approval','councilSupport','politicalCapital','actionPoints','environment','infrastructure','roadBudget','serviceBudget','privateJobs','businessMomentum'];
 for(const k of nums)if(!Number.isFinite(s[k]))s[k]=b[k];
 return s;
}
function save(){localStorage.setItem(SAVE_KEY,JSON.stringify(state));}
function load(){try{let raw=localStorage.getItem(SAVE_KEY);if(!raw)for(const k of LEGACY_SAVE_KEYS){raw=localStorage.getItem(k);if(raw)break;}return raw?normalizeState(JSON.parse(raw)):null;}catch{return null;}}
let state=load()||baseStarterState();

const canvas=$('#gameCanvas'),ctx=canvas.getContext('2d');
let view={scale:1,offsetX:0,offsetY:0};
let dragging=false,lastPointer=null,lastTick=performance.now(),toastTimer=null,animationClock=0;

function counts(activeOnly=false){const c={};for(const row of state.grid)for(const cell of row){if(!cell)continue;if(activeOnly&&cell.underConstruction)continue;c[cell.type]=(c[cell.type]||0)+1;}return c;}
function constructionProjects(){const a=[];for(let y=0;y<GRID_H;y++)for(let x=0;x<GRID_W;x++){const c=state.grid[y][x];if(c?.underConstruction)a.push({x,y,...c,name:BUILDINGS[c.type]?.name||c.type});}return a;}
function buildingCount(type,activeOnly=false){let n=0;for(const row of state.grid)for(const c of row)if(c?.type===type&&(!activeOnly||!c.underConstruction))n++;return n;}
function demographicSnapshot(pop=state.population){const familyBias=clamp(((state.stats.attractiveness||55)-50)*.0018,-.03,.045);const youth=Math.round(pop*clamp(.17+familyBias,.12,.23));const seniors=Math.round(pop*clamp(.22-familyBias*.45,.16,.29));const workingAge=Math.max(0,pop-youth-seniors);return{youth,seniors,workingAge,families:Math.round(pop/2.35)};}
function districtOf(x){return x<6?'West':x<12?'Zentrum':'Ost';}
function manhattan(a,b){return Math.abs(a.x-b.x)+Math.abs(a.y-b.y);}
function cellActive(c){return c&&!c.underConstruction;}
function neighbors(x,y){return [[x,y-1],[x+1,y],[x,y+1],[x-1,y]].filter(([nx,ny])=>nx>=0&&ny>=0&&nx<GRID_W&&ny<GRID_H);}
function adjacentRoads(x,y){return neighbors(x,y).filter(([nx,ny])=>cellActive(state.grid[ny][nx])&&state.grid[ny][nx].type==='road');}
function findTownhall(){for(let y=0;y<GRID_H;y++)for(let x=0;x<GRID_W;x++)if(state.grid[y][x]?.type==='townhall')return{x,y};return null;}
function roadNetwork(){
 const town=findTownhall(),connected=new Set();if(!town)return connected;const starts=adjacentRoads(town.x,town.y),q=[...starts];for(const [x,y] of starts)connected.add(`${x},${y}`);
 while(q.length){const [x,y]=q.shift();for(const [nx,ny] of neighbors(x,y)){const k=`${nx},${ny}`;if(connected.has(k))continue;if(cellActive(state.grid[ny][nx])&&state.grid[ny][nx].type==='road'){connected.add(k);q.push([nx,ny]);}}}return connected;
}
function isBuildingConnected(x,y,network){if(state.grid[y][x]?.type==='townhall')return true;return adjacentRoads(x,y).some(([rx,ry])=>network.has(`${rx},${ry}`));}
function roadDistanceBetweenBuildings(a,b,network){
 const sa=adjacentRoads(a.x,a.y).filter(([x,y])=>network.has(`${x},${y}`)),targets=new Set(adjacentRoads(b.x,b.y).filter(([x,y])=>network.has(`${x},${y}`)).map(([x,y])=>`${x},${y}`));if(!sa.length||!targets.size)return Infinity;
 const q=sa.map(([x,y])=>[x,y,0]),seen=new Set(sa.map(([x,y])=>`${x},${y}`));while(q.length){const [x,y,d]=q.shift();if(targets.has(`${x},${y}`))return d;for(const [nx,ny] of neighbors(x,y)){const k=`${nx},${ny}`;if(seen.has(k)||!network.has(k))continue;seen.add(k);q.push([nx,ny,d+1]);}}return Infinity;
}
function locations(type,activeOnly=true){const a=[];for(let y=0;y<GRID_H;y++)for(let x=0;x<GRID_W;x++){const c=state.grid[y][x];if(c?.type===type&&(!activeOnly||!c.underConstruction))a.push({x,y,cell:c});}return a;}
function allActiveBuildings(){const a=[];for(let y=0;y<GRID_H;y++)for(let x=0;x<GRID_W;x++){const c=state.grid[y][x];if(cellActive(c)&&c.type!=='road')a.push({x,y,cell:c});}return a;}
function nearestServiceDistance(home,types,network){let best=Infinity;for(const t of types)for(const s of locations(t)){const d=roadDistanceBetweenBuildings(home,s,network);if(d<best)best=d;}return best;}
function distanceScore(d,ideal=5,max=14){if(!Number.isFinite(d))return 0;if(d<=ideal)return 100;if(d>=max)return 15;return Math.round(100-(d-ideal)/(max-ideal)*85);}
function localPollutionAt(x,y){let p=0;for(const f of locations('factory')){const d=manhattan({x,y},f);if(d<=5)p+=(6-d)*8;}for(const r of locations('road')){const d=manhattan({x,y},r);if(d<=1)p+=2;}for(const pLoc of locations('park')){const d=manhattan({x,y},pLoc);if(d<=4)p-=Math.max(0,5-d)*4;}return clamp(p,0,100);}
function localLeisureAt(x,y){let v=0;for(const p of locations('park')){const d=manhattan({x,y},p);if(d<=6)v+=Math.max(0,7-d)*10;}for(const s of locations('shop')){const d=manhattan({x,y},s);if(d<=5)v+=Math.max(0,6-d)*4;}return clamp(v,0,100);}

function districtMetrics(network){
 const districts={West:{name:'West',residents:0,capacity:0,jobs:0,homes:0,connected:0,pollution:0,leisure:0,education:0,health:0,safety:0},Zentrum:{name:'Zentrum',residents:0,capacity:0,jobs:0,homes:0,connected:0,pollution:0,leisure:0,education:0,health:0,safety:0},Ost:{name:'Ost',residents:0,capacity:0,jobs:0,homes:0,connected:0,pollution:0,leisure:0,education:0,health:0,safety:0}};
 const homes=[...locations('house'),...locations('apartments')],totalCap=homes.reduce((a,h)=>a+(BUILDINGS[h.cell.type].capacity||0),0)||1;
 for(const h of homes){const d=districts[districtOf(h.x)],cap=BUILDINGS[h.cell.type].capacity||0,share=Math.round(state.population*cap/totalCap);d.residents+=share;d.capacity+=cap;d.homes++;if(isBuildingConnected(h.x,h.y,network))d.connected++;d.pollution+=localPollutionAt(h.x,h.y)*share;d.leisure+=localLeisureAt(h.x,h.y)*share;d.education+=Math.max(28,distanceScore(nearestServiceDistance(h,['kindergarten','school'],network),5,14))*share;d.health+=Math.max(55,distanceScore(nearestServiceDistance(h,['clinic'],network),6,16))*share;d.safety+=Math.max(55,distanceScore(nearestServiceDistance(h,['fire'],network),7,18))*share;}
 for(const b of allActiveBuildings()){const d=districts[districtOf(b.x)];d.jobs+=(BUILDINGS[b.cell.type].jobs||0);}
 for(const d of Object.values(districts)){const r=Math.max(1,d.residents);d.pollution=Math.round(d.pollution/r);d.leisure=Math.round(d.leisure/r);d.education=Math.round(d.education/r);d.health=Math.round(d.health/r);d.safety=Math.round(d.safety/r);d.connection=d.homes?Math.round(d.connected/d.homes*100):100;d.score=Math.round(clamp((d.education+d.health+d.safety+d.leisure+(100-d.pollution)+d.connection)/6,0,100));}
 return districts;
}

function metrics(){
 const c=counts(true),network=roadNetwork();let capacity=0,jobs=state.privateJobs,upkeep=0,happyMod=0,propertyBase=0,businessBase=0,energyBase=0;
 const serviceCap={education:0,safety:0,health:0};
 let disconnected=0,activeBuildings=0;
 for(let y=0;y<GRID_H;y++)for(let x=0;x<GRID_W;x++){const cell=state.grid[y][x];if(!cellActive(cell))continue;const b=BUILDINGS[cell.type];if(!b)continue;const connected=cell.type==='road'||cell.type==='townhall'||isBuildingConnected(x,y,network);if(cell.type!=='road'){activeBuildings++;if(!connected)disconnected++;}
  const efficiency=connected?1:.2;capacity+=(b.capacity||0)*efficiency;jobs+=(b.jobs||0)*efficiency;upkeep+=(b.upkeep||0);happyMod+=(b.happy||0)*efficiency;propertyBase+=(b.propertyBase||0)*efficiency;businessBase+=(b.businessBase||0)*efficiency;energyBase+=(b.energyBase||0)*efficiency;if(b.service)serviceCap[b.service]+=(b.serviceCapacity||0)*efficiency;
 }
 const demographics=demographicSnapshot(state.population),workingDemand=Math.max(1,Math.round(demographics.workingAge*.82)),commuterCapacity=Math.round(state.population*.28),residentJobs=Math.min(workingDemand,jobs+commuterCapacity),unemployment=clamp(100-residentJobs/workingDemand*100,0,55);
 const serviceFactor=state.serviceBudget/100;
 const tempEducation=(state.tempEducationMonths>0?state.tempEducation:0),tempHealth=(state.tempHealthMonths>0?state.tempHealth:0);
 const globalServices={education:clamp(24+serviceCap.education/Math.max(1,demographics.youth)*100*serviceFactor+tempEducation,0,160),safety:clamp(58+serviceCap.safety/Math.max(1,state.population)*100*serviceFactor,0,160),health:clamp(56+serviceCap.health/Math.max(1,state.population)*100*serviceFactor+tempHealth-state.healthShock,0,160)};
 const districts=districtMetrics(network),districtList=Object.values(districts),localEducation=districtList.reduce((a,d)=>a+d.education*d.residents,0)/Math.max(1,state.population),localHealth=districtList.reduce((a,d)=>a+d.health*d.residents,0)/Math.max(1,state.population),localSafety=districtList.reduce((a,d)=>a+d.safety*d.residents,0)/Math.max(1,state.population),localPollution=districtList.reduce((a,d)=>a+d.pollution*d.residents,0)/Math.max(1,state.population),localLeisure=districtList.reduce((a,d)=>a+d.leisure*d.residents,0)/Math.max(1,state.population);
 const services={education:Math.round(globalServices.education*.65+localEducation*.35),health:Math.round(globalServices.health*.65+localHealth*.35),safety:Math.round(globalServices.safety*.65+localSafety*.35)};
 const roadCells=Math.max(1,c.road||0),trafficDemand=state.population*.72+jobs*.5+state.privateJobs*.35,roadCapacity=roadCells*58*(state.roadBudget/100)*(state.infrastructure/70),congestion=clamp(trafficDemand/Math.max(1,roadCapacity)*100,5,180);
 const businessClimate=clamp(52+(state.economy-50)*.5+(state.infrastructure-50)*.2-(state.taxRates.business-380)*.12-(Math.max(0,congestion-90))*.18-(disconnected*3)+(state.businessMomentum||0),5,98);
 const companies=Math.max(0,Math.round((c.shop||0)*12+(c.factory||0)*8+state.privateJobs/18));
 const taxPressure=(state.taxRates.property-400)*.08+(state.taxRates.business-380)*.035+(state.taxRates.fees-100)*.18;
 const housingUtil=clamp(state.population/Math.max(1,capacity)*100,0,180);
 const connectionRate=activeBuildings?clamp(100-disconnected/activeBuildings*100,0,100):100;
 const attractiveness=clamp(51+(state.happiness-50)*.34+(state.environment-50)*.17+(state.infrastructure-50)*.18+(services.education-70)*.08+(services.health-70)*.07+(localLeisure-50)*.08-(unemployment*.25)-(Math.max(0,congestion-90))*.12-taxPressure*.18-(localPollution*.08)+(connectionRate-80)*.06,5,96);
 const residentShare=Math.round(state.population*76*(1+state.economy/320));
 const propertyTax=Math.round(propertyBase*(state.taxRates.property/400)*(1+state.population/8500));
 const businessTax=Math.round(businessBase*(state.taxRates.business/380)*(.65+state.economy/105)*(businessClimate/60));
 const fees=Math.round(state.population*18*(state.taxRates.fees/100));
 const grants=Math.round(11000+state.population*13+Math.max(0,65-attractiveness)*100);
 const energy=Math.round(energyBase*(.9+state.economy/220));
 const income=residentShare+propertyTax+businessTax+fees+grants+energy;
 const inf=1+state.inflation/100,eff=1-(state.efficiencyBonus||0)/100;
 const admin=Math.round((14500+state.population*7.2)*inf*eff),facilities=Math.round(upkeep*inf*(state.serviceBudget/100)*eff),social=Math.round(state.population*(10+unemployment*.32)*inf),roads=Math.round((roadCells*720+state.population*3.5+Math.max(0,70-state.infrastructure)*290)*inf*(state.roadBudget/100)),levy=Math.round((11000+state.population*(12+state.levyModifier*.9))*inf),interest=Math.round(state.debt*(state.interestRate/100)/12),repayment=Math.round(state.debt>0?Math.min(Math.max(8000,state.debt*.0075),state.debt):0),expenses=admin+facilities+social+roads+levy+interest+repayment,operating=income-expenses;
 const groupSatisfaction={
  families:clamp(state.happiness*.3+services.education*.32+localLeisure*.18+clamp(115-housingUtil,0,100)*.12+services.health*.08,0,100),
  workers:clamp(state.happiness*.28+clamp(100-unemployment*3,0,100)*.3+businessClimate*.18+clamp(120-congestion*.7,0,100)*.14+state.infrastructure*.1,0,100),
  seniors:clamp(state.happiness*.35+services.health*.35+services.safety*.15+localLeisure*.1+(100-localPollution)*.05,0,100),
  youth:clamp(state.happiness*.28+services.education*.28+localLeisure*.3+state.environment*.08+(state.youthBonus||0),0,100)
 };
 return{c,network,capacity,jobs,unemployment,serviceCap,serviceLevels:services,globalServices,districts,disconnected,connectionRate,propertyTax,residentShare,businessTax,fees,grants,energy,income,admin,facilities,social,roads,levy,interest,repayment,expenses,operating,happyMod,attractiveness,businessClimate,companies,demographics,housingUtil,trafficDemand,roadCapacity,congestion,localPollution,localLeisure,groupSatisfaction,debtPerCapita:state.debt/Math.max(1,state.population)};
}

function promiseProgress(id,m){
 if(id==='budget')return Math.round(clamp(50+m.operating/1400-m.debtPerCapita/28,0,100));
 if(id==='families')return Math.round(m.groupSatisfaction.families);
 if(id==='economy')return Math.round(m.businessClimate*.5+clamp(100-m.unemployment*3,0,100)*.35+clamp(m.companies*2.5,0,100)*.15);
 if(id==='infrastructure')return Math.round(state.infrastructure*.42+m.serviceLevels.safety*.24+clamp(120-m.congestion*.55,0,100)*.2+m.connectionRate*.14);
 if(id==='climate')return Math.round(state.environment*.58+(100-m.localPollution)*.22+clamp((m.c.solar||0)*28+(m.c.park||0)*14,0,100)*.2);
 if(id==='growth'){const growth=(state.population/Math.max(1,state.termStartPopulation)-1)*100;return Math.round(clamp(growth*5,0,100)*.48+m.attractiveness*.36+clamp(115-m.housingUtil,0,100)*.16);}
 return 0;
}
function promiseDone(id,m){return promiseProgress(id,m)>=72;}
function selectMandate(m){return Object.keys(PROMISES).map(id=>({id,p:promiseProgress(id,m)})).sort((a,b)=>a.p-b.p).slice(0,3).map(x=>x.id);}
function legacyScore(m=metrics()){const finance=clamp(55+m.operating/1600-m.debtPerCapita/30,0,100),services=(clamp(m.serviceLevels.education,0,100)+clamp(m.serviceLevels.safety,0,100)+clamp(m.serviceLevels.health,0,100))/3,mandate=state.mandate.reduce((a,id)=>a+promiseProgress(id,m),0)/Math.max(1,state.mandate.length);return Math.round(finance*.18+services*.17+state.approval*.15+state.councilSupport*.08+state.infrastructure*.08+state.environment*.07+m.businessClimate*.08+mandate*.08+m.connectionRate*.05+clamp(120-m.congestion*.45,0,100)*.06);}

function needFor(type,m){
 let score=50,reason='Ausgewogener Bedarf';
 if(type==='road'){score=clamp((100-state.infrastructure)*.65+Math.max(0,m.congestion-75)*.55+(100-m.connectionRate)*.7,8,98);reason=m.connectionRate<90?'Erschließungslücken schließen':m.congestion>105?'Verkehrsnetz ist überlastet':state.infrastructure<55?'Sanierungsdruck hoch':'Neue Straße nur bei konkreter Erschließung sinnvoll';}
 if(type==='house'||type==='apartments'){score=clamp((m.housingUtil-65)*1.35+(m.attractiveness-50)*.35,5,98);reason=m.housingUtil>94?'Wohnraum sehr knapp':m.housingUtil<72?'Aktuell deutliche Wohnraumreserve':'Wachstum beobachten';}
 if(type==='shop'){score=clamp(m.businessClimate*.55+(state.population/25)-m.companies*1.5,5,95);reason=m.businessClimate>65?'Gute Nachfrage und Standortbedingungen':'Wirtschaftsklima/Verkehr zuerst verbessern';}
 if(type==='factory'){score=clamp(m.unemployment*3.2+m.businessClimate*.35-(m.c.factory||0)*13,5,95);reason=m.unemployment>15?'Neue Arbeitsplätze dringend nötig':m.localPollution>45?'Umweltbelastung spricht gegen weiteres Gewerbe':'Nur bei echter Arbeitsmarktnachfrage';}
 if(type==='park'){score=clamp((65-state.environment)*1.2+(60-m.localLeisure)*.8+m.localPollution*.45,5,95);reason=m.localPollution>45?'Grün kann lokale Belastung dämpfen':m.localLeisure<45?'Freizeitangebot ist schwach':'Zusätzlicher Grenznutzen gering';}
 if(type==='kindergarten'||type==='school'){score=clamp(108-m.serviceLevels.education,5,99);reason=m.serviceLevels.education<70?'Bildungskapazität kritisch':'Kapazitäten aktuell ausreichend';}
 if(type==='fire'){score=clamp(108-m.serviceLevels.safety,5,99);reason=m.serviceLevels.safety<70?'Sicherheitsversorgung kritisch':'Kapazitäten aktuell ausreichend';}
 if(type==='clinic'){score=clamp(108-m.serviceLevels.health,5,99);reason=m.serviceLevels.health<70?'Gesundheitsversorgung kritisch':'Kapazitäten aktuell ausreichend';}
 if(type==='solar'){score=clamp((72-state.environment)+28-(m.c.solar||0)*10,5,92);reason=(m.c.solar||0)===0?'Diversifiziert Einnahmen und Klima':'Weitere Anlage nur bei Strategiebedarf';}
 return{score,label:score>=70?'Hoch':score>=42?'Mittel':'Gering',reason};
}
function recommendationList(m){return Object.keys(BUILDINGS).filter(k=>k!=='townhall').map(type=>({type,...needFor(type,m)})).sort((a,b)=>b.score-a.score).slice(0,5);}

function addIssue(id,severity=1){if(state.activeIssues.some(i=>i.id===id))return;if((state.issueCooldowns[id]||0)>state.monthsPlayed)return;const d=ISSUE_DEFS[id];if(!d)return;state.activeIssues.push({id,severity,created:state.monthsPlayed,deadline:state.monthsPlayed+d.months});}
function issueResolved(id,m){if(id==='housing')return m.housingUtil<88;if(id==='education')return m.serviceLevels.education>=75;if(id==='safety')return m.serviceLevels.safety>=75;if(id==='health')return m.serviceLevels.health>=75;if(id==='roads')return state.infrastructure>=55;if(id==='jobs')return m.unemployment<=12;if(id==='deficit')return m.operating>=0;if(id==='debt')return m.debtPerCapita<900;if(id==='trust')return state.approval>=45&&state.happiness>=45;if(id==='congestion')return m.congestion<90;if(id==='disconnected')return m.connectionRate>=95;if(id==='pollution')return m.localPollution<35;return false;}
function applyIssuePenalty(id){state.neglectedIssues++;state.approval-=3;state.councilSupport-=2;if(['housing','education','health','safety','pollution'].includes(id))state.happiness-=4;if(id==='roads')state.infrastructure-=4;if(id==='jobs')state.economy-=3;if(id==='deficit')state.oversightLevel=Math.max(state.oversightLevel,1);if(id==='debt')state.politicalCapital-=6;if(id==='trust')state.councilSupport-=5;if(id==='congestion')state.businessMomentum-=3;if(id==='disconnected')state.infrastructure-=2;state.issueCooldowns[id]=state.monthsPlayed+6;}
function evaluateIssues(m){
 if(m.housingUtil>94)addIssue('housing',2);if(m.serviceLevels.education<60)addIssue('education',2);if(m.serviceLevels.safety<55)addIssue('safety',2);if(m.serviceLevels.health<55)addIssue('health',2);if(state.infrastructure<42)addIssue('roads',2);if(m.unemployment>19)addIssue('jobs');if(state.consecutiveDeficitMonths>=4)addIssue('deficit',2);if(m.debtPerCapita>1300)addIssue('debt',2);if(state.approval<35||state.happiness<35)addIssue('trust',2);if(m.congestion>125)addIssue('congestion',2);if(m.connectionRate<82)addIssue('disconnected',2);if(m.localPollution>58)addIssue('pollution',2);
 const kept=[];for(const issue of state.activeIssues){if(issueResolved(issue.id,m)){state.approval+=1;state.politicalCapital+=1;state.issueCooldowns[issue.id]=state.monthsPlayed+4;continue;}if(state.monthsPlayed>issue.deadline){applyIssuePenalty(issue.id);state.eventLog.unshift({date:`${monthNames[state.month]} ${state.year}`,title:`Problem ungelöst: ${ISSUE_DEFS[issue.id].title}`,choice:'Frist verpasst – Vertrauen und Handlungsfähigkeit sinken'});continue;}kept.push(issue);}state.activeIssues=kept;
}
function loseGame(title,text){if(state.gameOver)return true;state.gameOver=true;state.speed=0;save();openModal(`<h2>${title}</h2><p>${text}</p><div class="card"><div class="stat-row"><span>Amtszeit</span><b>${state.monthsPlayed} Monate</b></div><div class="stat-row"><span>Vermächtnis-Score</span><b>${legacyScore()}</b></div><div class="stat-row"><span>Ungelöste Probleme</span><b>${state.neglectedIssues}</b></div></div><button class="primary" id="restartBtn">Neue Gemeinde übernehmen</button>`);setTimeout(()=>{$('#restartBtn').onclick=()=>{closeModal();resetGame();}},0);return true;}
function evaluateFailure(m){
 state.consecutiveDeficitMonths=m.operating<-20000?state.consecutiveDeficitMonths+1:Math.max(0,state.consecutiveDeficitMonths-1);state.noConfidenceMonths=state.councilSupport<22?state.noConfidenceMonths+1:Math.max(0,state.noConfidenceMonths-1);state.socialCrisisMonths=(state.happiness<25&&state.approval<30)?state.socialCrisisMonths+1:Math.max(0,state.socialCrisisMonths-1);state.serviceCrisisMonths=(Math.min(m.serviceLevels.education,m.serviceLevels.safety,m.serviceLevels.health)<20)?state.serviceCrisisMonths+1:Math.max(0,state.serviceCrisisMonths-1);state.infrastructureCrisisMonths=state.infrastructure<18?state.infrastructureCrisisMonths+1:Math.max(0,state.infrastructureCrisisMonths-1);
 if(state.consecutiveDeficitMonths>=6||m.debtPerCapita>1200||state.money<0)state.oversightLevel=Math.max(state.oversightLevel,1);if(state.consecutiveDeficitMonths>=12||m.debtPerCapita>1900)state.oversightLevel=Math.max(state.oversightLevel,2);if(m.operating>0&&state.money>150000&&m.debtPerCapita<900&&state.consecutiveDeficitMonths===0)state.oversightLevel=Math.max(0,state.oversightLevel-1);
 if(state.noConfidenceMonths>=4)return loseGame('🏛️ Misstrauensvotum','Du hast die Ratsmehrheit dauerhaft verloren. Der Rat entzieht dir die politische Handlungsfähigkeit.');
 if(state.socialCrisisMonths>=5)return loseGame('📉 Rücktritt nach Vertrauenskrise','Zufriedenheit und Zustimmung sind über Monate kollabiert.');
 if(state.serviceCrisisMonths>=6)return loseGame('🚨 Grundversorgung zusammengebrochen','Ein zentraler Bereich der Daseinsvorsorge war über Monate kritisch unterversorgt.');
 if(state.infrastructureCrisisMonths>=6)return loseGame('🛣️ Infrastruktur-Notstand','Der Sanierungsstau ist außer Kontrolle geraten.');
 if(state.oversightLevel>=2&&state.consecutiveDeficitMonths>=18)return loseGame('💸 Haushaltsaufsicht übernimmt','Der Haushalt ist strukturell nicht mehr genehmigungsfähig.');
 if(m.debtPerCapita>3000&&state.money<0)return loseGame('💸 Überschuldung','Schulden und Liquiditätsprobleme überschreiten das tragbare Maß.');
 if(state.neglectedIssues>=7)return loseGame('📋 Verwaltungspolitisches Scheitern','Zu viele dringende Probleme wurden trotz Fristen nicht gelöst.');
 if(state.population<250&&state.monthsPlayed>36)return loseGame('🏚️ Gemeinde verliert Zukunftsfähigkeit','Die Bevölkerung ist massiv eingebrochen und die kommunale Basis zerfällt.');
 return false;
}

function progressConstruction(){const completed=[];for(const row of state.grid)for(const c of row){if(!c?.underConstruction)continue;c.monthsLeft=Math.max(0,(c.monthsLeft||1)-1);if(c.monthsLeft<=0){c.underConstruction=false;completed.push(BUILDINGS[c.type]?.name||c.type);}}if(completed.length){state.eventLog.unshift({date:`${monthNames[state.month]} ${state.year}`,title:'Bauprojekte fertiggestellt',choice:[...new Set(completed)].join(', ')});state.eventLog=state.eventLog.slice(0,30);showToast(`${completed.length} Bauprojekt${completed.length===1?'':'e'} fertiggestellt`);}}
function decrementTemporary(){if(state.tempEducationMonths>0)state.tempEducationMonths--;if(state.tempHealthMonths>0)state.tempHealthMonths--;if(state.healthShock>0)state.healthShock=Math.max(0,state.healthShock-.5);state.youthBonus*=.96;state.businessMomentum*=.94;state.taxCooldown=Math.max(0,state.taxCooldown-1);}
function businessDynamics(m){const delta=clamp(Math.round((m.businessClimate-55)/18+(state.economy-50)/30-m.congestion/140+rand(-1.2,1.2)),-3,3);state.privateJobs=clamp(state.privateJobs+delta*7,0,1200);if(delta>1)state.eventLog.unshift({date:`${monthNames[state.month]} ${state.year}`,title:'Wirtschaft wächst',choice:`Private Betriebe schaffen etwa ${delta*7} zusätzliche Arbeitsplätze`});if(delta<-1)state.eventLog.unshift({date:`${monthNames[state.month]} ${state.year}`,title:'Betriebsschließungen',choice:`Etwa ${Math.abs(delta*7)} private Arbeitsplätze gehen verloren`});state.eventLog=state.eventLog.slice(0,30);}
function annualBudgetVote(m){if(state.month!==0||state.monthsPlayed-state.lastBudgetVote<10)return;state.lastBudgetVote=state.monthsPlayed;const score=state.councilSupport*.45+clamp(60+m.operating/1800,0,100)*.3+clamp(100-m.debtPerCapita/20,0,100)*.15+state.approval*.1;if(score<43){state.failedBudgets++;state.oversightLevel=Math.max(1,state.oversightLevel);state.councilSupport-=3;state.politicalCapital-=4;state.eventLog.unshift({date:`Jan ${state.year}`,title:'Haushalt nicht beschlossen',choice:'Der Rat verweigert dem Haushaltsentwurf die Mehrheit.'});if(state.failedBudgets>=2)loseGame('📑 Haushalt politisch gescheitert','Zwei Haushalte in Folge finden keine Mehrheit. Deine Verwaltung ist nicht mehr handlungsfähig.');}else{state.failedBudgets=0;state.politicalCapital+=3;state.eventLog.unshift({date:`Jan ${state.year}`,title:'Haushalt beschlossen',choice:'Der Rat trägt deinen Haushaltskurs mit.'});}}
function termReview(m){const elapsed=state.monthsPlayed-state.termStartMonth;if(elapsed<=0||elapsed%TERM_MONTHS!==0)return;const results=state.mandate.map(id=>({id,p:promiseProgress(id,m),done:promiseDone(id,m)})),done=results.filter(x=>x.done).length;state.promiseHistory.unshift({year:state.year,results});state.promiseHistory=state.promiseHistory.slice(0,4);const debtPenalty=clamp(m.debtPerCapita/90,0,24),broken=results.length-done,score=Math.round(state.approval*.28+state.happiness*.12+state.councilSupport*.1+legacyScore(m)*.18+done/state.mandate.length*32-debtPenalty-broken*3);if(score<55)return loseGame('🗳️ Kommunalwahl verloren',`Mit ${score}% reicht es nicht für eine weitere Amtszeit. Nur ${done} von ${state.mandate.length} zentralen Wahlversprechen wurden überzeugend erfüllt.`);state.electionsWon++;state.money+=100000;state.politicalCapital=clamp(state.politicalCapital+12,0,100);state.termStartMonth=state.monthsPlayed;state.termStartPopulation=state.population;state.mandate=selectMandate(m);openModal(`<h2>🗳️ Wiedergewählt – ${score}%</h2><p>${done} von ${results.length} Wahlversprechen wurden erfüllt. Die neue Amtszeit beginnt mit neuen Prioritäten.</p><button class="primary" id="continueBtn">Neue Amtszeit beginnen</button>`);setTimeout(()=>{$('#continueBtn').onclick=closeModal;},0);}
function maybeVictory(m){if(state.victoryShown||state.electionsWon<2||state.monthsPlayed<120)return;if(legacyScore(m)>=78&&m.debtPerCapita<900&&Math.min(m.serviceLevels.education,m.serviceLevels.health,m.serviceLevels.safety)>=75){state.victoryShown=true;openModal(`<h2>🏆 Vorbildkommune</h2><p>Nach mehr als zehn Jahren gilt deine Gemeinde als finanziell, sozial und infrastrukturell vorbildlich.</p><div class="card"><div class="stat-row"><span>Vermächtnis</span><b>${legacyScore(m)}/100</b></div><div class="stat-row"><span>Einwohner</span><b>${numFmt(state.population)}</b></div><div class="stat-row"><span>Schulden/Einwohner</span><b>${moneyFmt(m.debtPerCapita)}</b></div></div><button class="primary" id="continueBtn">Trotzdem weiterspielen</button>`);setTimeout(()=>{$('#continueBtn').onclick=closeModal;},0);}}
function triggerEvent(){if(state.gameOver)return;const ev=EVENTS[Math.floor(Math.random()*EVENTS.length)];openModal(`<div class="tag">Entscheidung</div><h2>${ev.title}</h2><p>${ev.text}</p>${ev.choices.map((c,i)=>`<button class="choice" data-choice="${i}"><b>${c.label}</b><small>${c.detail}</small></button>`).join('')}`);document.querySelectorAll('[data-choice]').forEach(btn=>btn.onclick=()=>{const ch=ev.choices[+btn.dataset.choice];ch.apply(state);state.happiness=clamp(state.happiness,5,98);state.approval=clamp(state.approval,5,98);state.councilSupport=clamp(state.councilSupport,5,98);state.environment=clamp(state.environment,5,100);state.infrastructure=clamp(state.infrastructure,5,100);state.economy=clamp(state.economy,15,95);state.eventLog.unshift({date:`${monthNames[state.month]} ${state.year}`,title:ev.title,choice:ch.label});state.eventLog=state.eventLog.slice(0,30);closeModal();save();updateHUD();showToast('Entscheidung übernommen');});}

function simulateMonth(){
 if(state.gameOver)return;state.month++;state.monthsPlayed++;if(state.month>11){state.month=0;state.capitalSpentLastYear=state.capitalSpentYear;state.fiscalHistory.unshift({year:state.year,income:(state.stats.income||0)*12,expenses:(state.stats.expenses||0)*12,capital:state.capitalSpentYear,debt:state.debt});state.fiscalHistory=state.fiscalHistory.slice(0,6);state.capitalSpentYear=0;state.year++;}
 state.actionPoints=clamp(3+(state.councilSupport>=65?.5:0)-(state.oversightLevel>=1?.5:0),1.5,3.5);progressConstruction();decrementTemporary();state.economy=clamp(state.economy+rand(-1.8,2.0),20,95);state.inflation=clamp(state.inflation+rand(-.14,.18),1,8);state.interestRate=clamp(state.interestRate+rand(-.06,.08),2,8.5);
 let m=metrics();businessDynamics(m);m=metrics();state.stats={income:m.income,expenses:m.expenses,operating:m.operating,propertyTax:m.propertyTax,residentShare:m.residentShare,businessTax:m.businessTax,fees:m.fees,grants:m.grants,energy:m.energy,admin:m.admin,facilities:m.facilities,social:m.social,roads:m.roads,levy:m.levy,interest:m.interest,repayment:m.repayment,attractiveness:m.attractiveness,businessClimate:m.businessClimate,congestion:m.congestion,connectionRate:m.connectionRate,pollution:m.localPollution};
 state.money+=m.operating;state.debt=Math.max(0,state.debt-m.repayment);if(state.money<-30000){const needed=Math.ceil(Math.abs(state.money)/25000)*25000+50000;state.debt+=needed;state.money+=needed;state.approval-=2;state.oversightLevel=Math.max(1,state.oversightLevel);showToast(`Kassenkredit: ${moneyFmt(needed)}`);}
 const freeHomes=Math.max(0,m.capacity-state.population),taxPenalty=(state.taxRates.property-400)*.025+(state.taxRates.fees-100)*.1,moveIntent=(m.attractiveness-50)*.45+(m.jobs-state.population)*.012+freeHomes*.018-taxPenalty-(Math.max(0,m.congestion-100))*.08,moveDelta=clamp(Math.round(moveIntent),-28,36),growth=freeHomes>0?Math.min(freeHomes,moveDelta):Math.min(0,moveDelta);state.population=Math.max(180,state.population+growth);
 const gs=m.groupSatisfaction,weighted=(gs.families*.3+gs.workers*.36+gs.seniors*.2+gs.youth*.14),fiscalMood=m.operating>=0?2:-4,debtMood=-Math.min(9,m.debtPerCapita/180),targetHappy=clamp(weighted*.65+state.environment*.12+state.infrastructure*.1+m.connectionRate*.06+fiscalMood+debtMood,8,95);state.happiness=clamp(Math.round(lerp(state.happiness,targetHappy,.22)),5,98);state.approval=clamp(Math.round(state.approval+(state.happiness-state.approval)*.1+(m.operating>0?.5:-.8)-(state.activeIssues.length*.15)),5,98);state.councilSupport=clamp(Math.round(state.councilSupport+(state.approval-state.councilSupport)*.06+(m.operating>0?.25:-.35)),5,98);state.politicalCapital=clamp(state.politicalCapital+(state.approval>60?.5:-.2)-(state.activeIssues.length*.08),0,100);
 state.infrastructure=clamp(state.infrastructure-(state.roadBudget<90?.45:.18)+(state.roadBudget>110?.25:0)-Math.max(0,m.congestion-115)*.006,8,100);state.environment=clamp(state.environment-.08-buildingCount('factory',true)*.28+buildingCount('park',true)*.16+buildingCount('solar',true)*.16-m.localPollution*.015,8,100);
 evaluateIssues(m);m=metrics();annualBudgetVote(m);if(evaluateFailure(m))return;termReview(m);if(state.gameOver)return;maybeVictory(m);if(state.monthsPlayed-(state.lastEvent||0)>=4&&Math.random()<.26){state.lastEvent=state.monthsPlayed;triggerEvent();}
 state.objectives={pop1500:state.population>=1500,happy75:state.happiness>=75,balance:m.operating>=10000,services:Math.min(m.serviceLevels.education,m.serviceLevels.health,m.serviceLevels.safety)>=80};save();updateHUD();if($('#panel').classList.contains('open'))renderPanel(document.querySelector('.dock button.active')?.dataset.panel||'overview');
}

function resetGame(){state=baseStarterState();save();fitMap();renderPanel('overview');showToast('Neue Gemeinde übernommen');}
function canAct(cost=1,politics=0){if(state.actionPoints<cost){showToast('Verwaltungskapazität für diesen Monat aufgebraucht');return false;}if(state.politicalCapital<politics){showToast('Zu wenig politisches Kapital');return false;}return true;}
function changeRate(kind,delta){if(state.taxCooldown>0)return showToast(`Steuerpolitik erst in ${state.taxCooldown} Monaten wieder änderbar`);if(!canAct(.5,3))return;const min=kind==='property'?250:kind==='business'?250:75,max=kind==='fees'?140:600;state.taxRates[kind]=clamp(state.taxRates[kind]+delta,min,max);state.taxCooldown=3;state.actionPoints-=.5;state.politicalCapital-=3;if(delta>0){state.approval-=1.2;}else state.approval+=.5;save();renderPanel('finance');updateHUD();}
function takeLoan(){const m=metrics();if(state.oversightLevel>=2)return showToast('Kommunalaufsicht genehmigt derzeit keine neuen Kredite');if(m.debtPerCapita>2200)return showToast('Verschuldung bereits zu hoch');if(!canAct(.5,4))return;state.debt+=250000;state.money+=250000;state.actionPoints-=.5;state.politicalCapital-=4;state.approval-=1;showToast('Investitionskredit 250.000 € aufgenommen');save();renderPanel('finance');updateHUD();}
function repayDebt(){const amount=Math.min(75000,state.debt,Math.max(0,state.money-150000));if(amount<=0)return showToast('Nicht genügend freie Rücklage');state.debt-=amount;state.money-=amount;state.politicalCapital+=1;showToast(`Sondertilgung ${moneyFmt(amount)}`);save();renderPanel('finance');updateHUD();}
function changeBudget(kind,delta){if(!canAct(.5,2))return;state[kind]=clamp(state[kind]+delta,70,130);state.actionPoints-=.5;state.politicalCapital-=2;save();renderPanel('finance');}

function projectRequirement(type,m){const b=BUILDINGS[type],need=needFor(type,m);let reason='';if(constructionProjects().length>=MAX_PROJECTS)reason='Maximal drei parallele Bauprojekte.';else if(state.oversightLevel>=2&&b.cost>=200000)reason='Haushaltsaufsicht sperrt größere Investitionen.';else if(state.oversightLevel>=1&&b.cost>=900000)reason='Haushaltssperre: Großinvestition nicht genehmigungsfähig.';else if(state.councilSupport<35&&b.cost>=500000)reason='Keine stabile Ratsmehrheit für dieses Projekt.';else if(state.money<b.cost)reason='Nicht genügend liquide Mittel.';else if(state.actionPoints<(b.admin||0))reason='Zu wenig Verwaltungskapazität.';else if(state.politicalCapital<(b.politics||0))reason='Zu wenig politisches Kapital.';return{ok:!reason,reason,need};}
function validCell(x,y){return x>=0&&y>=0&&x<GRID_W&&y<GRID_H;}
function hasRoadAdjacent(x,y){return adjacentRoads(x,y).length>0;}
function inspectCell(x,y){const c=state.grid[y]?.[x];if(!c)return showToast('Freies Grundstück');const b=BUILDINGS[c.type],m=metrics(),connected=c.type==='road'||isBuildingConnected(x,y,m.network),district=m.districts[districtOf(x)],poll=c.type==='road'?0:localPollutionAt(x,y),leisure=c.type==='road'?0:localLeisureAt(x,y);openModal(`<div class="tag">${districtOf(x)}</div><h2>${b?.emoji||''} ${b?.name||c.type}</h2>${c.underConstruction?`<p class="warn">Baustelle · noch ${c.monthsLeft} Monate</p>`:`<p class="${connected?'good':'bad'}">${connected?'Mit Rathaus-Straßennetz verbunden':'Nicht mit Rathaus-Straßennetz verbunden'}</p>`}<div class="card"><div class="stat-row"><span>Lokale Umweltbelastung</span><b>${poll}%</b></div><div class="stat-row"><span>Freizeit-/Grünnähe</span><b>${leisure}%</b></div><div class="stat-row"><span>Stadtteilqualität</span><b>${district.score}%</b></div>${b?.upkeep?`<div class="stat-row"><span>Laufender Grundbetrieb</span><b>${moneyFmt(b.upkeep)}/Mon.</b></div>`:''}</div><button class="secondary" id="closeInspect">Schließen</button>`);setTimeout(()=>{$('#closeInspect').onclick=closeModal;},0);}
function buildAt(x,y){if(!validCell(x,y)||state.gameOver)return;if(state.selected==='inspect')return inspectCell(x,y);const type=state.selected,b=BUILDINGS[type];if(type==='bulldoze'){const old=state.grid[y][x];if(!old||old.type==='townhall')return showToast(old?'Rathaus kann nicht abgerissen werden':'Hier steht nichts');if(!canAct(.5,1))return;state.grid[y][x]=null;state.money-=8000;state.actionPoints-=.5;state.politicalCapital-=1;showToast('Abriss durchgeführt');save();draw();renderPanel('build');return;}if(!b)return;if(state.grid[y][x])return showToast('Feld bereits belegt');if(type!=='road'&&!hasRoadAdjacent(x,y))return showToast('Gebäude benötigen eine angrenzende Straße');if(b.unique&&buildingCount(type))return showToast(`${b.name} bereits vorhanden`);const m=metrics(),req=projectRequirement(type,m);if(!req.ok)return showToast(req.reason);state.money-=b.cost;state.capitalSpentYear+=b.cost;state.actionPoints=Math.max(0,state.actionPoints-(b.admin||0));state.politicalCapital=Math.max(0,state.politicalCapital-(b.politics||0));const months=b.buildMonths||0;state.grid[y][x]=months?{type,underConstruction:true,monthsLeft:months}:{type};if(type==='park')state.environment+=1.5;if(type==='road')state.infrastructure+=.25;if(req.need.score<35&&b.cost>=100000){state.approval-=1;state.councilSupport-=1;showToast(`${b.name} gestartet – Bedarf aktuell gering`);}else showToast(months?`${b.name}: ${months} Monate Bauzeit`:`${b.name} gebaut`);save();updateHUD();draw();renderPanel('build');}

// --- Canvas renderer ---
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.floor(r.width*d);canvas.height=Math.floor(r.height*d);ctx.setTransform(d,0,0,d,0,0);draw();}
function cellSize(){return 54*view.scale;}
function fitMap(){const r=canvas.getBoundingClientRect();view.scale=Math.max(.5,Math.min(1.08,Math.min((r.width-34)/(GRID_W*54),(r.height-34)/(GRID_H*54))));view.offsetX=(r.width-GRID_W*54*view.scale)/2;view.offsetY=(r.height-GRID_H*54*view.scale)/2;draw();}
function roadNeighbors(x,y){return{n:state.grid[y-1]?.[x]?.type==='road',e:state.grid[y]?.[x+1]?.type==='road',s:state.grid[y+1]?.[x]?.type==='road',w:state.grid[y]?.[x-1]?.type==='road'};}
function roundRect(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.stroke();}}
function drawGrass(px,py,cs,x,y){const g=ctx.createLinearGradient(px,py,px,py+cs);const v=seeded(x,y);g.addColorStop(0,v>.5?'#6f9c5e':'#689258');g.addColorStop(1,v>.5?'#5b864e':'#567f49');ctx.fillStyle=g;ctx.fillRect(px,py,cs+1,cs+1);ctx.fillStyle='rgba(255,255,255,.05)';for(let i=0;i<3;i++){const sx=px+cs*seeded(x,y,i+3),sy=py+cs*seeded(x,y,i+9);ctx.fillRect(sx,sy,1.2,2.5);}if(!state.grid[y][x]&&v>.82){ctx.fillStyle='#4d743f';ctx.beginPath();ctx.arc(px+cs*.72,py+cs*.38,cs*.055,0,Math.PI*2);ctx.fill();ctx.fillStyle='#365f35';ctx.beginPath();ctx.arc(px+cs*.76,py+cs*.34,cs*.045,0,Math.PI*2);ctx.fill();}}
function drawRoad(px,py,cs,x,y){const n=roadNeighbors(x,y),w=.42,c=.5,half=w/2;ctx.fillStyle='#9e9b8d';ctx.fillRect(px+cs*(c-half-.055),py,cs*(w+.11),cs);ctx.fillRect(px,py+cs*(c-half-.055),cs,cs*(w+.11));ctx.fillStyle='#555c61';ctx.fillRect(px+cs*(c-half),py+cs*(n.n?0:c-half),cs*w,cs*(n.n||n.s?1:w));ctx.fillRect(px+cs*(n.w?0:c-half),py+cs*(c-half),cs*(n.w||n.e?1:w),cs*w);ctx.fillStyle='#626a70';ctx.fillRect(px+cs*(c-half+.03),py+cs*(n.n?0:c-half),cs*(w-.06),cs*(n.n||n.s?1:w));ctx.fillRect(px+cs*(n.w?0:c-half),py+cs*(c-half+.03),cs*(n.w||n.e?1:w),cs*(w-.06));ctx.strokeStyle='#e8d47f';ctx.lineWidth=Math.max(1,cs*.025);ctx.setLineDash([cs*.09,cs*.07]);ctx.beginPath();if(n.n||n.s){ctx.moveTo(px+cs*.5,py+(n.n?0:cs*(c-half)));ctx.lineTo(px+cs*.5,py+(n.s?cs:cs*(c+half)));}if(n.w||n.e||(!n.n&&!n.s)){ctx.moveTo(px+(n.w?0:cs*(c-half)),py+cs*.5);ctx.lineTo(px+(n.e?cs:cs*(c+half)),py+cs*.5);}ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#2f3d42';const lamp=(x+y)%4===0;if(lamp){ctx.fillRect(px+cs*.18,py+cs*.18,cs*.018,cs*.14);ctx.fillStyle='#f1df9a';ctx.beginPath();ctx.arc(px+cs*.19,py+cs*.17,cs*.025,0,Math.PI*2);ctx.fill();}}
function drawPlot(px,py,cs){ctx.fillStyle='rgba(0,0,0,.18)';ctx.beginPath();ctx.ellipse(px+cs*.53,py+cs*.79,cs*.32,cs*.105,0,0,Math.PI*2);ctx.fill();roundRect(px+cs*.1,py+cs*.13,cs*.8,cs*.67,cs*.045,'#789766','rgba(255,255,255,.18)');}
function roof(px,py,w,h,color){ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(px,py+h);ctx.lineTo(px+w*.5,py);ctx.lineTo(px+w,py+h);ctx.closePath();ctx.fill();ctx.fillStyle='rgba(255,255,255,.12)';ctx.beginPath();ctx.moveTo(px+w*.5,py);ctx.lineTo(px+w*.78,py+h);ctx.lineTo(px+w*.52,py+h);ctx.closePath();ctx.fill();}
function windows(x,y,cols,rows,w,h,color='#cae7ff'){const gx=w/cols,gy=h/rows;ctx.fillStyle=color;for(let r=0;r<rows;r++)for(let c=0;c<cols;c++)ctx.fillRect(x+c*gx+gx*.18,y+r*gy+gy*.18,gx*.48,gy*.43);}
function drawHouse(px,py,cs,x,y){drawPlot(px,py,cs);const v=Math.floor(seeded(x,y,21)*3),body=['#efc28e','#e3b692','#d9c3a2'][v],rc=['#984d39','#8b563b','#77483c'][v];ctx.fillStyle=body;ctx.fillRect(px+cs*.23,py+cs*.38,cs*.52,cs*.3);roof(px+cs*.18,py+cs*.21,cs*.62,cs*.21,rc);ctx.fillStyle='#674735';ctx.fillRect(px+cs*.47,py+cs*.53,cs*.08,cs*.15);windows(px+cs*.28,py+cs*.45,2,1,cs*.17,cs*.11);windows(px+cs*.59,py+cs*.45,1,1,cs*.1,cs*.11);ctx.fillStyle='#4d7a42';ctx.beginPath();ctx.arc(px+cs*.19,py+cs*.57,cs*.08,0,Math.PI*2);ctx.fill();}
function drawApartments(px,py,cs,x,y){drawPlot(px,py,cs);ctx.fillStyle=seeded(x,y,31)>.5?'#d0b1a1':'#c9b8a8';ctx.fillRect(px+cs*.17,py+cs*.25,cs*.65,cs*.46);ctx.fillStyle='#8c5a50';ctx.fillRect(px+cs*.17,py+cs*.22,cs*.65,cs*.07);windows(px+cs*.22,py+cs*.31,5,3,cs*.54,cs*.29);ctx.fillStyle='#665248';ctx.fillRect(px+cs*.47,py+cs*.57,cs*.08,cs*.14);}
function drawShop(px,py,cs){drawPlot(px,py,cs);ctx.fillStyle='#f0d8bd';ctx.fillRect(px+cs*.17,py+cs*.38,cs*.66,cs*.26);ctx.fillStyle='#8f5b46';ctx.fillRect(px+cs*.17,py+cs*.3,cs*.66,cs*.1);for(let i=0;i<5;i++){ctx.fillStyle=i%2?'#f1e6d2':'#bf4540';ctx.fillRect(px+cs*(.2+i*.12),py+cs*.39,cs*.075,cs*.08);}ctx.fillStyle='#bcdcf1';ctx.fillRect(px+cs*.25,py+cs*.5,cs*.22,cs*.09);ctx.fillRect(px+cs*.55,py+cs*.5,cs*.17,cs*.09);}
function drawFactory(px,py,cs){drawPlot(px,py,cs);ctx.fillStyle='#a6a29c';ctx.fillRect(px+cs*.15,py+cs*.41,cs*.65,cs*.25);ctx.fillStyle='#7c675f';for(let i=0;i<3;i++){ctx.beginPath();ctx.moveTo(px+cs*(.15+i*.18),py+cs*.41);ctx.lineTo(px+cs*(.24+i*.18),py+cs*.29);ctx.lineTo(px+cs*(.34+i*.18),py+cs*.41);ctx.closePath();ctx.fill();}ctx.fillStyle='#7b5b50';ctx.fillRect(px+cs*.65,py+cs*.18,cs*.09,cs*.3);windows(px+cs*.24,py+cs*.49,4,1,cs*.38,cs*.08,'#d5e4e9');ctx.fillStyle='rgba(210,215,215,.45)';ctx.beginPath();ctx.arc(px+cs*.7,py+cs*.13,cs*.05,0,Math.PI*2);ctx.arc(px+cs*.74,py+cs*.08,cs*.04,0,Math.PI*2);ctx.fill();}
function drawPark(px,py,cs,x,y){drawPlot(px,py,cs);ctx.strokeStyle='#c5b078';ctx.lineWidth=cs*.05;ctx.beginPath();ctx.moveTo(px+cs*.18,py+cs*.68);ctx.quadraticCurveTo(px+cs*.5,py+cs*.42,px+cs*.82,py+cs*.6);ctx.stroke();for(let i=0;i<4;i++){const tx=px+cs*(.25+seeded(x,y,50+i)*.5),ty=py+cs*(.27+seeded(x,y,70+i)*.28);ctx.fillStyle='#704a32';ctx.fillRect(tx,ty,cs*.035,cs*.16);ctx.fillStyle=i%2?'#4f8444':'#5c914b';ctx.beginPath();ctx.arc(tx+cs*.02,ty,cs*.105,0,Math.PI*2);ctx.fill();}}
function drawCivic(px,py,cs,body,roofColor,accent,symbol){drawPlot(px,py,cs);ctx.fillStyle=body;ctx.fillRect(px+cs*.16,py+cs*.34,cs*.68,cs*.33);roof(px+cs*.13,py+cs*.18,cs*.74,cs*.19,roofColor);ctx.fillStyle=accent;ctx.fillRect(px+cs*.46,py+cs*.5,cs*.09,cs*.17);windows(px+cs*.22,py+cs*.42,4,2,cs*.55,cs*.17);if(symbol){ctx.font=`${Math.max(10,cs*.16)}px system-ui`;ctx.fillStyle='#fff';ctx.textAlign='center';ctx.fillText(symbol,px+cs*.5,py+cs*.33);}}
function drawSolar(px,py,cs){drawPlot(px,py,cs);for(let r=0;r<2;r++)for(let c=0;c<3;c++){const x=px+cs*(.16+c*.23),y=py+cs*(.29+r*.22);ctx.fillStyle='#2e6694';ctx.fillRect(x,y,cs*.19,cs*.15);ctx.strokeStyle='rgba(255,255,255,.3)';ctx.strokeRect(x,y,cs*.19,cs*.15);}ctx.fillStyle='#e9c84e';ctx.beginPath();ctx.arc(px+cs*.8,py+cs*.22,cs*.075,0,Math.PI*2);ctx.fill();}
function drawConstruction(c,px,py,cs){drawPlot(px,py,cs);ctx.fillStyle='#c79b51';ctx.fillRect(px+cs*.15,py+cs*.58,cs*.7,cs*.07);ctx.strokeStyle='#efce7e';ctx.lineWidth=Math.max(1,cs*.024);for(let i=0;i<5;i++){const x=px+cs*(.2+i*.145);ctx.beginPath();ctx.moveTo(x,py+cs*.24);ctx.lineTo(x,py+cs*.64);ctx.stroke();}ctx.fillStyle='#35434b';ctx.fillRect(px+cs*.64,py+cs*.2,cs*.06,cs*.36);ctx.fillStyle='#efc43f';ctx.fillRect(px+cs*.67,py+cs*.2,cs*.2,cs*.035);ctx.fillStyle='#fff';ctx.font=`700 ${Math.max(9,cs*.15)}px system-ui`;ctx.textAlign='center';ctx.fillText(`${c.monthsLeft}M`,px+cs*.5,py+cs*.75);}
function drawBuilding(c,px,py,cs,x,y){if(c.underConstruction)return drawConstruction(c,px,py,cs);switch(c.type){case'road':return drawRoad(px,py,cs,x,y);case'house':return drawHouse(px,py,cs,x,y);case'apartments':return drawApartments(px,py,cs,x,y);case'shop':return drawShop(px,py,cs);case'factory':return drawFactory(px,py,cs);case'park':return drawPark(px,py,cs,x,y);case'kindergarten':return drawCivic(px,py,cs,'#f0d79d','#c88745','#a76b35','K');case'school':return drawCivic(px,py,cs,'#d3a17d','#894739','#76543d','S');case'fire':return drawCivic(px,py,cs,'#d36b62','#8c3030','#742626','112');case'clinic':return drawCivic(px,py,cs,'#dce8ed','#6486aa','#8ca9bd','+');case'solar':return drawSolar(px,py,cs);case'townhall':return drawCivic(px,py,cs,'#d8c5a2','#746047','#61503d','⚑');}}
function overlayColor(x,y,m){if(state.mapMode==='normal')return null;if(state.mapMode==='traffic'){const nearRoad=state.grid[y][x]?.type==='road';if(!nearRoad)return null;const t=clamp(m.congestion/150,0,1);return `rgba(${Math.round(220*t)},${Math.round(180*(1-t)+70)},55,.28)`;}if(state.mapMode==='services'){const d=m.districts[districtOf(x)],s=(d.education+d.health+d.safety)/3;return s<50?'rgba(220,70,60,.18)':s<75?'rgba(240,180,60,.14)':'rgba(70,190,110,.12)';}if(state.mapMode==='environment'){const p=localPollutionAt(x,y);return p>55?'rgba(180,60,70,.22)':p>25?'rgba(220,150,65,.13)':'rgba(60,180,100,.10)';}return null;}
function drawCars(cs){const roads=[];for(let y=0;y<GRID_H;y++)for(let x=0;x<GRID_W;x++)if(state.grid[y][x]?.type==='road')roads.push({x,y});if(!roads.length)return;const count=Math.min(18,Math.max(4,Math.round(state.population/120)));for(let i=0;i<count;i++){const idx=Math.floor((animationClock*.00008*(1+i*.03)+i*.137)%1*roads.length),r=roads[idx],px=view.offsetX+r.x*cs,py=view.offsetY+r.y*cs,n=roadNeighbors(r.x,r.y),horizontal=n.e||n.w;ctx.fillStyle=['#c84d49','#4c7fba','#e3c653','#eceff1','#4e5b64'][i%5];const w=horizontal?cs*.12:cs*.07,h=horizontal?cs*.07:cs*.12;ctx.fillRect(px+cs*.5-w/2,py+cs*.5-h/2,w,h);ctx.fillStyle='rgba(210,235,255,.7)';ctx.fillRect(px+cs*.5-w*.25,py+cs*.5-h*.3,w*.25,h*.25);}}
function draw(){const r=canvas.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);const bg=ctx.createLinearGradient(0,0,0,r.height);bg.addColorStop(0,'#294c31');bg.addColorStop(1,'#1d3824');ctx.fillStyle=bg;ctx.fillRect(0,0,r.width,r.height);const cs=cellSize(),m=metrics();for(let y=0;y<GRID_H;y++)for(let x=0;x<GRID_W;x++){const px=view.offsetX+x*cs,py=view.offsetY+y*cs;drawGrass(px,py,cs,x,y);ctx.strokeStyle='rgba(15,35,18,.10)';ctx.lineWidth=1;ctx.strokeRect(px,py,cs,cs);const c=state.grid[y][x];if(c)drawBuilding(c,px,py,cs,x,y);const ov=overlayColor(x,y,m);if(ov){ctx.fillStyle=ov;ctx.fillRect(px,py,cs,cs);}}drawCars(cs);}

function pointerCell(clientX,clientY){const r=canvas.getBoundingClientRect(),cs=cellSize();return{x:Math.floor((clientX-r.left-view.offsetX)/cs),y:Math.floor((clientY-r.top-view.offsetY)/cs)};}
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);dragging=true;lastPointer={x:e.clientX,y:e.clientY,moved:false};});
canvas.addEventListener('pointermove',e=>{if(!dragging||!lastPointer)return;const dx=e.clientX-lastPointer.x,dy=e.clientY-lastPointer.y;if(Math.abs(dx)+Math.abs(dy)>6){view.offsetX+=dx;view.offsetY+=dy;lastPointer={x:e.clientX,y:e.clientY,moved:true};draw();}});
canvas.addEventListener('pointerup',e=>{if(dragging&&lastPointer&&!lastPointer.moved){const c=pointerCell(e.clientX,e.clientY);buildAt(c.x,c.y);}dragging=false;lastPointer=null;});
canvas.addEventListener('wheel',e=>{e.preventDefault();const old=view.scale;view.scale=clamp(view.scale*(e.deltaY<0?1.1:.9),.43,1.8);const r=canvas.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top;view.offsetX=mx-(mx-view.offsetX)*(view.scale/old);view.offsetY=my-(my-view.offsetY)*(view.scale/old);draw();},{passive:false});

// --- UI ---
function updateHUD(){const m=metrics();$('#cityName').textContent=state.cityName;$('#money').textContent=moneyFmt(state.money);$('#population').textContent=numFmt(state.population);$('#happiness').textContent=pct(state.happiness);$('#dateLabel').textContent=`${monthNames[state.month]} ${state.year}`;$('#money').className=state.money<0?'bad':state.money>400000?'good':'';$('#happiness').className=state.happiness>=70?'good':state.happiness<45?'bad':'';document.title=`${state.cityName} · Bürgermeister 2026`;}
function meter(label,value,colorClass='good'){return `<div class="stat-row"><span>${label}</span><b>${Math.round(value)}%</b></div><div class="meter ${colorClass}" style="color:var(--${colorClass})"><i style="width:${clamp(value,0,100)}%"></i></div>`;}
function issueCards(){if(!state.activeIssues.length)return `<div class="card good-card"><h3>✅ Keine akute Krise</h3><p class="muted">Derzeit gibt es keine Probleme mit verbindlicher Frist.</p></div>`;return state.activeIssues.sort((a,b)=>a.deadline-b.deadline).map(i=>{const d=ISSUE_DEFS[i.id],left=Math.max(0,i.deadline-state.monthsPlayed);return `<div class="card issue-card"><div class="tag bad">${left} Mon. Frist</div><h3>${d.icon} ${d.title}</h3><p class="muted">${d.desc}</p></div>`;}).join('');}
function mandateCards(m){return state.mandate.map(id=>{const p=promiseProgress(id,m),d=PROMISES[id];return `<div class="card"><div class="stat-row"><b>${d.title}</b><span class="tag ${p>=72?'good':p<45?'bad':'warn'}">${p}%</span></div><p class="muted">${d.desc}</p><div class="meter" style="color:${p>=72?'var(--good)':p<45?'var(--bad)':'var(--warn)'}"><i style="width:${clamp(p,0,100)}%"></i></div></div>`;}).join('');}
function recommendationCards(m){return recommendationList(m).map(r=>{const b=BUILDINGS[r.type];return `<button class="recommendation" data-recommend="${r.type}"><span class="rec-icon">${b.emoji}</span><span><b>${b.name}</b><small>${r.reason}</small></span><strong class="${r.score>=70?'good':r.score<42?'muted':'warn'}">${r.label}</strong></button>`;}).join('');}
function districtCards(m){return Object.values(m.districts).map(d=>`<div class="card district-card"><div class="stat-row"><b>${d.name}</b><span class="tag">${d.score}%</span></div><div class="mini-grid"><span>👥 ${numFmt(d.residents)}</span><span>💼 ${numFmt(d.jobs)}</span><span>🔌 ${d.connection}%</span><span>🌫️ ${d.pollution}%</span></div><div class="stat-row"><span>Bildung</span><b>${d.education}%</b></div><div class="stat-row"><span>Gesundheit</span><b>${d.health}%</b></div><div class="stat-row"><span>Sicherheit</span><b>${d.safety}%</b></div></div>`).join('');}
function financeRateControl(title,key,current,step=10){return `<div class="card"><h3>${title}</h3><div class="stat-row"><span>${key==='fees'?'Niveau':'Hebesatz'}</span><b>${current}%</b></div><div class="toolbar-row"><button class="secondary" data-rate="${key}" data-delta="-${step}">-${step}</button><button class="secondary" data-rate="${key}" data-delta="${step}">+${step}</button></div></div>`;}
function supervisionLabel(){return state.oversightLevel===0?'Keine':state.oversightLevel===1?'Haushaltssicherung':'Strenge Kommunalaufsicht';}
function renderPanel(which){
 document.querySelectorAll('.dock button').forEach(b=>b.classList.toggle('active',b.dataset.panel===which));$('#panel').classList.add('open');const m=metrics();let html='',title='',sub='';
 if(which==='overview'){title='Lagezentrum';sub='Prioritäten statt blindem Bauen';html=`<div class="status-hero"><div><small>Vermächtnis</small><b>${legacyScore(m)}/100</b></div><div><small>Zustimmung</small><b>${state.approval}%</b></div><div><small>Rat</small><b>${state.councilSupport}%</b></div><div><small>Handlung</small><b>${state.actionPoints.toFixed(1)}/3</b></div></div><div class="card"><h3>Was jetzt am meisten Sinn macht</h3>${recommendationCards(m)}</div><h3>Dringende Probleme</h3>${issueCards()}<div class="card"><h3>Gemeindelage</h3><div class="stat-row"><span>Betriebssaldo / Monat</span><b class="${m.operating>=0?'good':'bad'}">${moneyFmt(m.operating)}</b></div><div class="stat-row"><span>Wohnraumauslastung</span><b>${m.housingUtil.toFixed(0)}%</b></div><div class="stat-row"><span>Arbeitslosigkeit</span><b>${m.unemployment.toFixed(1)}%</b></div><div class="stat-row"><span>Verkehrsauslastung</span><b class="${m.congestion>110?'bad':m.congestion>85?'warn':'good'}">${m.congestion.toFixed(0)}%</b></div><div class="stat-row"><span>Straßennetz verbunden</span><b>${m.connectionRate.toFixed(0)}%</b></div><div class="stat-row"><span>Schulden / Einwohner</span><b>${moneyFmt(m.debtPerCapita)}</b></div>${meter('Attraktivität',m.attractiveness,m.attractiveness<45?'bad':m.attractiveness<65?'warn':'good')}</div><h3>Wahlversprechen</h3>${mandateCards(m)}`;}
 if(which==='build'){title='Planen & Bauen';sub='Jedes Projekt braucht einen Grund';html=`<div class="toolbar-row map-tools"><button class="secondary ${state.selected==='inspect'?'selected':''}" data-build="inspect">🔎 Prüfen</button><button class="secondary ${state.selected==='bulldoze'?'selected':''}" data-build="bulldoze">🧨 Abriss</button></div><div class="card"><div class="stat-row"><span>Parallele Projekte</span><b>${constructionProjects().length}/${MAX_PROJECTS}</b></div><div class="stat-row"><span>Verwaltungskapazität</span><b>${state.actionPoints.toFixed(1)}</b></div><div class="stat-row"><span>Politisches Kapital</span><b>${Math.round(state.politicalCapital)}</b></div></div><div class="grid-buttons">${Object.entries(BUILDINGS).filter(([k])=>k!=='townhall').map(([k,b])=>{const need=needFor(k,m),req=projectRequirement(k,m);return `<button class="build-btn ${state.selected===k?'selected':''} ${!req.ok?'disabled-look':''}" data-build="${k}"><span class="emoji">${b.emoji}</span><b>${b.name}</b><small>${moneyFmt(b.cost)} · ${b.buildMonths?`${b.buildMonths} Mon.`:'sofort'} · Bedarf ${need.label}</small><em>${need.reason}</em></button>`;}).join('')}</div>`;}
 if(which==='finance'){title='Finanzen';sub='Haushalt, Steuern und Prioritäten';html=`<div class="card"><h3>Ergebnishaushalt / Monat</h3><div class="stat-row"><span>Einkommensteueranteil</span><b class="good">${moneyFmt(m.residentShare)}</b></div><div class="stat-row"><span>Grundsteuer</span><b class="good">${moneyFmt(m.propertyTax)}</b></div><div class="stat-row"><span>Gewerbesteuer</span><b class="good">${moneyFmt(m.businessTax)}</b></div><div class="stat-row"><span>Gebühren & Zuweisungen</span><b class="good">${moneyFmt(m.fees+m.grants+m.energy)}</b></div><div class="stat-row"><b>Einnahmen</b><b class="good">${moneyFmt(m.income)}</b></div><hr><div class="stat-row"><span>Verwaltung</span><b class="bad">${moneyFmt(m.admin)}</b></div><div class="stat-row"><span>Einrichtungen</span><b class="bad">${moneyFmt(m.facilities)}</b></div><div class="stat-row"><span>Soziales</span><b class="bad">${moneyFmt(m.social)}</b></div><div class="stat-row"><span>Straßen</span><b class="bad">${moneyFmt(m.roads)}</b></div><div class="stat-row"><span>Kreisumlage</span><b class="bad">${moneyFmt(m.levy)}</b></div><div class="stat-row"><span>Zins + Tilgung</span><b class="bad">${moneyFmt(m.interest+m.repayment)}</b></div><div class="stat-row"><b>Ausgaben</b><b class="bad">${moneyFmt(m.expenses)}</b></div><div class="stat-row"><b>Saldo</b><b class="${m.operating>=0?'good':'bad'}">${moneyFmt(m.operating)}</b></div></div><div class="card"><h3>Finanzielle Handlungsfähigkeit</h3><div class="stat-row"><span>Rücklage</span><b>${moneyFmt(state.money)}</b></div><div class="stat-row"><span>Schulden</span><b>${moneyFmt(state.debt)}</b></div><div class="stat-row"><span>Schulden/Einwohner</span><b>${moneyFmt(m.debtPerCapita)}</b></div><div class="stat-row"><span>Kommunalaufsicht</span><b class="${state.oversightLevel?'warn':'good'}">${supervisionLabel()}</b></div><div class="toolbar-row"><button class="secondary" id="loanBtn">Kredit +250.000 €</button><button class="secondary" id="repayBtn">75.000 € tilgen</button></div></div><div class="card"><h3>Budgetprioritäten</h3><div class="stat-row"><span>Straßenunterhalt</span><b>${state.roadBudget}%</b></div><div class="toolbar-row"><button class="secondary" data-budget="roadBudget" data-delta="-10">-10</button><button class="secondary" data-budget="roadBudget" data-delta="10">+10</button></div><div class="stat-row"><span>Versorgungsbudget</span><b>${state.serviceBudget}%</b></div><div class="toolbar-row"><button class="secondary" data-budget="serviceBudget" data-delta="-10">-10</button><button class="secondary" data-budget="serviceBudget" data-delta="10">+10</button></div></div>${financeRateControl('Grundsteuer','property',state.taxRates.property,20)}${financeRateControl('Gewerbesteuer','business',state.taxRates.business,20)}${financeRateControl('Gebührenniveau','fees',state.taxRates.fees,5)}`;}
 if(which==='citizens'){title='Bürger & Stadtteile';sub='Unterschiedliche Gruppen haben unterschiedliche Bedürfnisse';html=`<div class="card"><h3>Bevölkerungsgruppen</h3>${meter('Familien',m.groupSatisfaction.families,m.groupSatisfaction.families<45?'bad':m.groupSatisfaction.families<65?'warn':'good')}${meter('Erwerbstätige',m.groupSatisfaction.workers,m.groupSatisfaction.workers<45?'bad':m.groupSatisfaction.workers<65?'warn':'good')}${meter('Senioren',m.groupSatisfaction.seniors,m.groupSatisfaction.seniors<45?'bad':m.groupSatisfaction.seniors<65?'warn':'good')}${meter('Jugend',m.groupSatisfaction.youth,m.groupSatisfaction.youth<45?'bad':m.groupSatisfaction.youth<65?'warn':'good')}</div><div class="card"><div class="stat-row"><span>Einwohner</span><b>${numFmt(state.population)}</b></div><div class="stat-row"><span>Wohnkapazität</span><b>${numFmt(m.capacity)}</b></div><div class="stat-row"><span>Arbeitsplätze inkl. Pendeln</span><b>${numFmt(m.jobs)}</b></div><div class="stat-row"><span>Betriebe</span><b>${numFmt(m.companies)}</b></div></div><h3>Stadtteile</h3>${districtCards(m)}`;}
 if(which==='politics'){title='Politik';sub='Mehrheiten, Mandat und Amtsrisiken';const next=TERM_MONTHS-((state.monthsPlayed-state.termStartMonth)%TERM_MONTHS||0);html=`<div class="election"><h3>🗳️ Nächste Wahl</h3><div style="font-size:28px;font-weight:900">in ${next} Monaten</div>${meter('Zustimmung',state.approval,state.approval<45?'bad':state.approval<60?'warn':'good')}${meter('Ratsmehrheit',state.councilSupport,state.councilSupport<35?'bad':state.councilSupport<55?'warn':'good')}</div><div class="card"><h3>Politische Handlungsfähigkeit</h3><div class="stat-row"><span>Politisches Kapital</span><b>${Math.round(state.politicalCapital)}/100</b></div><div class="stat-row"><span>Verwaltungskapazität</span><b>${state.actionPoints.toFixed(1)}/3</b></div><div class="stat-row"><span>Fehlgeschlagene Haushalte</span><b>${state.failedBudgets}</b></div><div class="stat-row"><span>Vermächtnis</span><b>${legacyScore(m)}/100</b></div></div><h3>Wahlversprechen</h3>${mandateCards(m)}<div class="card"><h3>Bürgermeisterbüro</h3><div class="toolbar-row"><button class="secondary" id="renameBtn">Gemeinde umbenennen</button><button class="danger" id="newGameBtn">Neues Spiel</button></div></div>`;}
 if(which==='events'){title='Ereignisse & Diagnose';sub='Chronik und Kartenanalyse';html=`<div class="card"><h3>Kartenansicht</h3><div class="toolbar-row"><button class="secondary" data-mapmode="normal">Normal</button><button class="secondary" data-mapmode="traffic">Verkehr</button><button class="secondary" data-mapmode="services">Versorgung</button><button class="secondary" data-mapmode="environment">Umwelt</button></div></div>${state.eventLog.length?state.eventLog.map(e=>`<div class="card"><div class="tag">${e.date}</div><h3>${e.title}</h3><div class="muted">${e.choice}</div></div>`).join(''):`<div class="card"><p>Noch keine Ereignisse.</p></div>`}`;}
 $('#panelTitle').textContent=title;$('#panelSubtitle').textContent=sub;$('#panelContent').innerHTML=html;
 document.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>{state.selected=b.dataset.build;save();renderPanel('build');showToast(`${b.querySelector('b')?.textContent||b.textContent.trim()} ausgewählt`);});
 document.querySelectorAll('[data-recommend]').forEach(b=>b.onclick=()=>{state.selected=b.dataset.recommend;renderPanel('build');showToast(`${BUILDINGS[state.selected].name} als Werkzeug gewählt`);});
 document.querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>changeRate(b.dataset.rate,+b.dataset.delta));document.querySelectorAll('[data-budget]').forEach(b=>b.onclick=()=>changeBudget(b.dataset.budget,+b.dataset.delta));document.querySelectorAll('[data-mapmode]').forEach(b=>b.onclick=()=>{state.mapMode=b.dataset.mapmode;save();draw();showToast(`Kartenansicht: ${b.textContent}`);});
 $('#loanBtn')?.addEventListener('click',takeLoan);$('#repayBtn')?.addEventListener('click',repayDebt);$('#newGameBtn')?.addEventListener('click',()=>openModal(`<h2>Neues Spiel?</h2><p>Der aktuelle lokale Spielstand wird ersetzt.</p><div class="toolbar-row"><button class="danger" id="confirmReset">Neu starten</button><button class="secondary" id="cancelReset">Abbrechen</button></div>`));setTimeout(()=>{if($('#confirmReset')){$('#confirmReset').onclick=()=>{closeModal();resetGame();};$('#cancelReset').onclick=closeModal;}},0);$('#renameBtn')?.addEventListener('click',()=>{const n=prompt('Name deiner Gemeinde:',state.cityName);if(n&&n.trim()){state.cityName=n.trim().slice(0,24);save();updateHUD();renderPanel('politics');}});
}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2200);}
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden');}
function closeModal(){$('#modal').classList.add('hidden');}
$('.dock').addEventListener('click',e=>{const b=e.target.closest('button[data-panel]');if(b)renderPanel(b.dataset.panel);});$('#closePanel').onclick=()=>$('#panel').classList.remove('open');$('#menuBtn').onclick=()=>renderPanel('overview');document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>{state.speed=+b.dataset.speed;document.querySelectorAll('[data-speed]').forEach(x=>x.classList.toggle('active',x===b));save();});
function loop(now){animationClock=now;const interval=state.speed===2?1700:state.speed===1?3500:Infinity;if(now-lastTick>interval){lastTick=now;simulateMonth();}draw();requestAnimationFrame(loop);}
window.addEventListener('resize',()=>{resize();fitMap();});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();showToast('Die App kann über das Browsermenü installiert werden');});if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});
updateHUD();resize();fitMap();renderPanel('overview');requestAnimationFrame(loop);
})();
