'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { buildSpeechText, feedbackPhrase, _test } = require('../elevenlabs');
const question = { id: 'test-1', category: 'Natur & Tiere', text: 'Welches Tier ist das größte Landtier?', options: ['Elefant', 'Pferd', 'Löwe', 'Nashorn'], correctIndex: 0, explanation: 'Der Elefant ist das größte heute lebende Landtier.' };
assert.strictEqual(buildSpeechText(question, 'question'), 'Frage. Welches Tier ist das größte Landtier?');
assert(buildSpeechText(question, 'all').includes('Antwort A. Elefant.'));
assert(buildSpeechText(question, 'result-correct-0').includes('Erklärung.'));
assert(buildSpeechText(question, 'result-correct-0').includes('größte heute lebende Landtier'));
assert.notStrictEqual(feedbackPhrase('correct', 0), feedbackPhrase('correct', 1));
assert(_test.resultScope('result-wrong-2'));
assert(_test.isVoiceReadPermissionError('missing the permission voices_read'));
const html = fs.readFileSync(path.join(__dirname, '..', 'public', 'solo.html'), 'utf8');
const client = fs.readFileSync(path.join(__dirname, '..', 'public', 'elevenlabs-speech.js'), 'utf8');
assert(html.includes('/elevenlabs-speech.js'));
assert(client.includes('result-${type}-'));
assert(client.includes('persistentCache'));
console.log('ElevenLabs speech tests passed.');
