const CACHE='syndikat-v5-3-1';
const CORE=['./','./index.html','./style.css','./js/core.js','./cloud-config.js','./js/cloud.js','./assets/city-map.webp','./assets/portrait-vittorio.webp','./assets/portrait-marco.webp','./assets/portrait-sofia.webp','./assets/portrait-keller.webp','./assets/event-raid.webp','./assets/event-court.webp','./assets/event-prison-break.webp','./assets/start-user.webp','./assets/start-noir.svg','./assets/district-harbor.svg','./assets/district-industrial.svg','./assets/district-redlight.svg','./assets/district-west.svg','./assets/district-oldtown.svg','./assets/district-center.svg','./assets/district-station.svg','./assets/district-south.svg','./assets/business-machines.svg','./assets/business-escort.svg','./assets/business-bar.svg','./assets/business-betting.svg','./assets/business-arcade.svg','./assets/business-club.svg','./assets/business-luxury.svg','./assets/business-casino.svg','./assets/business-hotel.svg','./assets/business-holding.svg','./assets/rival-romano.svg','./assets/rival-moretti.svg','./assets/rival-costa.svg','./assets/rival-bianchi.svg','./assets/rival-russo.svg','./assets/rival-conti.svg','./assets/rival-falcone.svg','./assets/staff-informant.svg','./assets/staff-guard.svg','./assets/staff-bodyguard.svg','./assets/staff-gunman.svg','./assets/staff-lawyer.svg','./assets/staff-manager.svg','./assets/op-sabotage.svg','./assets/op-kidnap.svg','./assets/op-hit.svg','./assets/op-bank.svg','./assets/event-betrayal.svg','./assets/event-boom.svg','./assets/event-gangwar.svg','./assets/event-press.svg','./assets/event-informant.svg','./assets/event-fair.svg','./assets/event-recession.svg','./assets/event-corruption.svg','./assets/event-fire.svg','./assets/event-union.svg','./assets/item-pistol.svg','./assets/item-shotgun.svg','./assets/item-tommy.svg','./assets/item-sedan.svg','./assets/item-coupe.svg','./assets/item-van.svg','./assets/item-armored.svg','./assets/item-masks.svg','./assets/item-radios.svg','./assets/item-armor.svg','./assets/item-tools.svg','./assets/person-marco-bellini.svg','./assets/person-julia-costa.svg','./assets/person-vito-serra.svg','./assets/person-mara-conti.svg','./assets/person-enzo-vitale.svg','./assets/person-giulia-rizzo.svg','./assets/person-luca-ferraro.svg','./assets/person-sofia-greco.svg','./assets/person-carlo-de-luca.svg','./assets/person-elena-marino.svg','./assets/person-nico-romano.svg','./assets/person-tessa-bianchi.svg','./assets/person-rico-falcone.svg','./assets/person-valentina-moretti.svg','./assets/person-dario-russo.svg','./assets/person-mina-leone.svg','./assets/contact-officer.svg','./assets/contact-inspector.svg','./assets/contact-judge.svg','./assets/contact-prosecutor.svg','./assets/contact-mayor.svg','./assets/property-shop.svg','./assets/property-block.svg','./assets/property-warehouse.svg','./assets/property-prime.svg','./manifest.webmanifest','./icon.svg','./icon-192.svg','./icon-512.svg'];
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(CORE)).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('syndikat-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',e=>{
  if(e.request.method!=='GET')return;
  const u=new URL(e.request.url);
  if(u.origin!==self.location.origin)return;
  if(e.request.mode==='navigate'){
    e.respondWith(fetch(e.request).then(r=>{const copy=r.clone();caches.open(CACHE).then(c=>c.put('./index.html',copy));return r;}).catch(()=>caches.match('./index.html').then(r=>r||caches.match('./'))));
    return;
  }
  e.respondWith(caches.match(e.request).then(c=>c||fetch(e.request).then(r=>{if(r&&r.ok){const copy=r.clone();caches.open(CACHE).then(cache=>cache.put(e.request,copy));}return r;})));
});
self.addEventListener('message',e=>{if(e.data?.type==='SKIP_WAITING')self.skipWaiting();});
