'use strict';
(function(){
  let localSession=null;
  function aiCfg(){data.integrations=data.integrations||{};return data.integrations.ai=data.integrations.ai||{mode:'local',backendUrl:''}}
  function financeContext(question=''){
    const now=new Date(),s=monthSummary(now),safe=safeToSpendMetrics?.()||{},forecast=FinanzPremium.uncertaintyForecast(),auto=FinanzPremium.autopilot(),year=FinanzPremium.annualCompare(now.getFullYear()),cats=(typeof categoryBreakdown==='function'?categoryBreakdown(now):[]).slice(0,8),contracts=FinanzPremium.contractOptimization().slice(0,6),goals=(data.goals||[]).map(g=>({name:g.name,target:num(g.target),current:typeof goalCurrent==='function'?goalCurrent(g):num(g.current)})).slice(0,8),debts=(data.debts||[]).map(d=>({name:d.name||d.title,balance:typeof debtBalanceAtDate==='function'?debtBalanceAtDate(d,localISO(now)):num(d.balance),rate:num(d.rate),monthly:num(d.monthly||d.payment)})).slice(0,8);
    return {question,period:localISO(now).slice(0,7),month:{income:s.income,expense:s.expense,expectedIncome:s.totalExpectedIncome,expectedExpense:s.totalExpectedExpense},safe:{available:safe.safe,perDay:safe.perDay,earmarked:safe.earmarked},forecast,categories:cats.map(c=>({name:c.cat?.name||c.name||getCat(c.id)?.name||'Sonstiges',value:num(c.value||c.amount)})),anomalies:auto.alerts.slice(0,6),contracts,goals,debts,year:{current:year.current,previous:year.previous,inflation:year.inflation,realExpenseChange:year.realExpenseChange},netWorth:typeof netWorth==='function'?netWorth():0,assetAllocation:FinanzPremium.assetAllocation()}
  }
  function localExplain(question){const q=FinanceLib.normalizeText(question),c=financeContext(question),parts=[];if(/warum|weniger|mehr aus|ausgabe/.test(q)){const cats=c.categories.slice().sort((a,b)=>b.value-a.value).slice(0,3);parts.push(`Diesen Monat liegen die Ausgaben bei ${money(c.month.expense)}.`);if(cats.length)parts.push(`Die größten Bereiche sind ${cats.map(x=>`${x.name} ${money(x.value)}`).join(', ')}.`);if(c.anomalies.length)parts.push(`Zusätzlich wurden ${c.anomalies.length} auffällige Buchung(en) erkannt.`)}else if(/frei|verfügbar|ausgeben|tagesbudget/.test(q)){parts.push(`Aktuell sind ${money(c.safe.available)} frei verfügbar. Das entspricht etwa ${money(c.safe.perDay)} pro Tag bis Monatsende.`);parts.push(`Die konservative Monatsend-Prognose liegt bei ${money(c.forecast.monthEnd.conservative)}.`)}else if(/sparen|ziel/.test(q)){const open=c.goals.filter(g=>g.current<g.target);parts.push(open.length?`Es gibt ${open.length} offene Sparziele. Zusammen fehlen noch ${money(open.reduce((s,g)=>s+Math.max(0,g.target-g.current),0))}.`:'Alle hinterlegten Sparziele sind erreicht.')}else if(/schuld|kredit/.test(q)){parts.push(c.debts.length?`Die hinterlegten Restschulden betragen zusammen ${money(c.debts.reduce((s,d)=>s+d.balance,0))}.`:'Es sind keine aktiven Kredite hinterlegt.')}else if(/jahr|vergleich|vorjahr/.test(q)){parts.push(`Im laufenden Jahr betragen die Ausgaben ${money(c.year.current.expense)} gegenüber ${money(c.year.previous.expense)} im Vorjahr.`);if(c.year.inflation)parts.push(`Inflationsbereinigt beträgt die Veränderung ${money(c.year.realExpenseChange)}.`)}else{parts.push(`Aktuell sind ${money(c.safe.available)} frei verfügbar; das konservative Monatsende liegt bei ${money(c.forecast.monthEnd.conservative)}.`);parts.push(`Einnahmen ${money(c.month.income)}, Ausgaben ${money(c.month.expense)}, Nettovermögen ${money(c.netWorth)}.`)}return parts.join(' ')}
  async function deviceAvailability(){if(typeof LanguageModel==='undefined')return'unavailable';try{return await LanguageModel.availability()}catch{return'unavailable'}}
  async function deviceAnswer(question){if(typeof LanguageModel==='undefined')throw new Error('Lokales Browser-KI-Modell nicht verfügbar');const availability=await deviceAvailability();if(availability==='unavailable')throw new Error('Lokales Browser-KI-Modell auf diesem Gerät nicht verfügbar');if(!localSession)localSession=await LanguageModel.create({monitor(m){m.addEventListener('downloadprogress',e=>toast?.(`Lokales KI-Modell: ${Math.round(e.loaded*100)} %`))}});const c=financeContext(question),prompt=`You are a careful personal-finance explainer. All calculations in the JSON are authoritative. Never invent balances or recalculate them differently. Explain the answer in concise German. Do not give investment guarantees. Question: ${question}\nFinance JSON: ${JSON.stringify(c)}`;return localSession.prompt(prompt)}
  function backend(){return String(aiCfg().backendUrl||data.integrations?.backendUrl||'').replace(/\/$/,'')}
  async function cloudAnswer(question){const url=backend();if(!url)throw new Error('Backend-URL fehlt');const s=await FinanzCloud?.getSession?.();if(!s?.access_token)throw new Error('Für Cloud-KI zuerst bei Cloud anmelden');const r=await fetch(`${url}/api/ai/analyze`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.access_token}`},body:JSON.stringify({question,context:financeContext(question)})}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`KI ${r.status}`);return j.text||'Keine Antwort'}
  async function answer(question,mode=aiCfg().mode||'local'){if(mode==='cloud')return cloudAnswer(question);if(mode==='device'){try{return await deviceAnswer(question)}catch(e){toast?.(`${e.message} – lokaler Analyst wird verwendet`,'error');return localExplain(question)}}return localExplain(question)}
  window.FinanzAI={aiCfg,financeContext,localExplain,deviceAvailability,deviceAnswer,cloudAnswer,answer};
})();
