'use strict';
(function(){
  const AUTH_DB='finanzplan-cloud-auth-v1',AUTH_STORE='secure',COLLECTIONS=['members','accounts','categories','transactions','recurring','budgets','goals','reserves','contracts','insurances','debts','projects','monthClosures','documents','merchantRules','reconciliations','assets','monthlyReports'];
  let session=null;
  const enc=new TextEncoder(),dec=new TextDecoder(),clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
  function cloud(){data.integrations=data.integrations||{};return data.integrations.cloud=data.integrations.cloud||{enabled:false,url:'',publishableKey:'',householdId:'',lastSync:''}}
  function cfg(){const c=cloud();return {url:String(c.url||'').replace(/\/$/,''),key:String(c.publishableKey||'')}}
  function openAuthDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(AUTH_DB,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(AUTH_STORE))d.createObjectStore(AUTH_STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
  async function authGet(k){const db=await openAuthDB();return new Promise((resolve,reject)=>{const r=db.transaction(AUTH_STORE).objectStore(AUTH_STORE).get(k);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
  async function authPut(k,v){const db=await openAuthDB();return new Promise((resolve,reject)=>{const tr=db.transaction(AUTH_STORE,'readwrite');tr.objectStore(AUTH_STORE).put(v,k);tr.oncomplete=resolve;tr.onerror=()=>reject(tr.error)})}
  async function authDelete(k){const db=await openAuthDB();return new Promise(resolve=>{const tr=db.transaction(AUTH_STORE,'readwrite');tr.objectStore(AUTH_STORE).delete(k);tr.oncomplete=resolve;tr.onerror=resolve})}
  async function deviceKey(){let key=await authGet('deviceKey');if(!key){key=await crypto.subtle.generateKey({name:'AES-GCM',length:256},false,['encrypt','decrypt']);await authPut('deviceKey',key)}return key}
  async function saveSession(s){session=s;if(!s?.refresh_token){await authDelete('session');return}const key=await deviceKey(),iv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(s)));await authPut('session',{iv:Array.from(iv),cipher})}
  async function loadSession(){try{const p=await authGet('session');if(!p)return null;const key=await deviceKey(),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(p.iv)},key,p.cipher);session=JSON.parse(dec.decode(plain));return session}catch{return null}}
  function assertConfig(){const {url,key}=cfg();if(!url||!key)throw new Error('Supabase URL und Publishable Key fehlen');return {url,key}}
  async function authRequest(path,body){const {url,key}=assertConfig(),r=await fetch(`${url}/auth/v1/${path}`,{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.msg||j.error_description||j.message||`Auth ${r.status}`);return j}
  async function signUp(email,password){const j=await authRequest('signup',{email,password});if(j.access_token)await saveSession(j);return j}
  async function signIn(email,password){const j=await authRequest('token?grant_type=password',{email,password});await saveSession(j);return j}
  async function refresh(){if(!session)await loadSession();if(!session?.refresh_token)return null;try{const j=await authRequest('token?grant_type=refresh_token',{refresh_token:session.refresh_token});await saveSession(j);return j}catch{await saveSession(null);return null}}
  async function getSession(){if(!session)await loadSession();if(session?.expires_at&&session.expires_at*1000<Date.now()+60000)await refresh();return session}
  async function signOut(){try{const s=await getSession(),{url,key}=cfg();if(s?.access_token)await fetch(`${url}/auth/v1/logout`,{method:'POST',headers:{apikey:key,Authorization:`Bearer ${s.access_token}`}})}catch{}await saveSession(null)}
  async function api(path,{method='GET',body,prefer='return=representation',headers={}}={}){const {url,key}=assertConfig(),s=await getSession();if(!s?.access_token)throw new Error('Nicht bei Cloud angemeldet');const r=await fetch(`${url}${path}`,{method,headers:{apikey:key,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json',Prefer:prefer,...headers},body:body===undefined?undefined:JSON.stringify(body)});const text=await r.text(),j=text?JSON.parse(text):null;if(!r.ok)throw new Error(j?.message||j?.hint||j?.error||`Cloud ${r.status}`);return j}
  function stable(v){if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return `[${v.map(stable).join(',')}]`;return `{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(',')}}`}
  function hash(v){return FinanceLib.fingerprint(stable(v))}
  function collectionArray(name){if(!Array.isArray(data[name]))data[name]=[];return data[name]}
  async function createHousehold(name='Mein Haushalt'){const rows=await api('/rest/v1/households',{method:'POST',body:{name}}),h=rows?.[0];if(!h?.id)throw new Error('Haushalt konnte nicht angelegt werden');cloud().householdId=h.id;cloud().enabled=true;saveData('Cloud-Haushalt angelegt');return h}
  async function listHouseholds(){return api('/rest/v1/households?select=id,name,created_at&order=created_at.asc')}
  async function selectHousehold(id){cloud().householdId=id;cloud().enabled=true;saveData('Cloud-Haushalt gewählt')}
  async function members(){const id=cloud().householdId;if(!id)return[];return api(`/rest/v1/household_members?household_id=eq.${encodeURIComponent(id)}&select=user_id,role,display_name,created_at`)}
  async function createInvite(email,role='adult'){const id=cloud().householdId;if(!id)throw new Error('Kein Cloud-Haushalt gewählt');const token=crypto.randomUUID()+crypto.randomUUID().replaceAll('-',''),rows=await api('/rest/v1/household_invites',{method:'POST',body:{household_id:id,email:String(email).toLowerCase(),role,token}});return {token,row:rows?.[0]}}
  async function acceptInvite(token){const rows=await api('/rest/v1/rpc/accept_household_invite',{method:'POST',body:{p_token:token}});const id=Array.isArray(rows)?rows[0]?.household_id:rows?.household_id;if(id){cloud().householdId=id;cloud().enabled=true;saveData('Einladung angenommen')}return rows}
  function getMeta(){data.sync=data.sync||{};return data.sync.cloudMeta=data.sync.cloudMeta||{records:{},conflicts:[]}}
  async function fetchRemote(){const id=cloud().householdId;if(!id)throw new Error('Kein Cloud-Haushalt gewählt');return api(`/rest/v1/finance_records?household_id=eq.${encodeURIComponent(id)}&select=collection,record_id,payload,version,updated_at,deleted&limit=50000`)}
  async function upsertRemote(collection,record,present=true,version=0){const id=cloud().householdId,body={household_id:id,collection,record_id:record.id,payload:present?record:{},version:version+1,deleted:!present};return api('/rest/v1/finance_records?on_conflict=household_id,collection,record_id',{method:'POST',body,prefer:'resolution=merge-duplicates,return=representation'})}
  async function syncRecords(){const meta=getMeta(),remote=await fetchRemote(),rmap=new Map(remote.map(r=>[`${r.collection}:${r.record_id}`,r])),conflicts=[];let pulled=0,pushed=0,deleted=0;
    for(const collection of COLLECTIONS){const arr=collectionArray(collection),localMap=new Map(arr.map(x=>[x.id,x]));for(const [id,local] of localMap){const key=`${collection}:${id}`,m=meta.records[key]||{},rh=rmap.get(key),lh=hash(local),localChanged=lh!==m.hash,remoteChanged=!!rh&&rh.updated_at!==m.remoteUpdatedAt;if(rh?.deleted){if(!localChanged){data[collection]=data[collection].filter(x=>x.id!==id);meta.records[key]={hash:'',remoteUpdatedAt:rh.updated_at,version:rh.version,deleted:true};deleted++}else conflicts.push({key,collection,id,local:clone(local),remote:null,reason:'remote-delete'});continue}if(rh&&remoteChanged&&localChanged&&m.remoteUpdatedAt){conflicts.push({key,collection,id,local:clone(local),remote:clone(rh.payload),reason:'both-changed'});continue}if(rh&&remoteChanged&&!localChanged){Object.assign(local,clone(rh.payload));meta.records[key]={hash:hash(local),remoteUpdatedAt:rh.updated_at,version:rh.version};pulled++;continue}if(!rh||localChanged){const res=await upsertRemote(collection,local,true,rh?.version||0),row=res?.[0];meta.records[key]={hash:lh,remoteUpdatedAt:row?.updated_at||new Date().toISOString(),version:row?.version||((rh?.version||0)+1)};pushed++}}
      for(const [key,rh] of rmap){if(rh.collection!==collection||rh.deleted||localMap.has(rh.record_id))continue;const m=meta.records[key];if(m?.hash){const tomb={id:rh.record_id};const res=await upsertRemote(collection,tomb,false,rh.version),row=res?.[0];meta.records[key]={hash:'',remoteUpdatedAt:row?.updated_at||new Date().toISOString(),version:row?.version||rh.version+1,deleted:true};deleted++;continue}data[collection].push(clone(rh.payload));meta.records[key]={hash:hash(rh.payload),remoteUpdatedAt:rh.updated_at,version:rh.version};pulled++}}
    meta.conflicts=conflicts;cloud().lastSync=new Date().toISOString();saveData(`Cloud-Sync: ${pulled} geladen, ${pushed} gesendet${conflicts.length?`, ${conflicts.length} Konflikt(e)`:''}`);return {pulled,pushed,deleted,conflicts};
  }
  async function resolveConflict(key,choice){const meta=getMeta(),c=meta.conflicts.find(x=>x.key===key);if(!c)return false;const arr=collectionArray(c.collection),i=arr.findIndex(x=>x.id===c.id);if(choice==='remote'){if(c.remote){if(i>=0)arr[i]=clone(c.remote);else arr.push(clone(c.remote))}else if(i>=0)arr.splice(i,1)}else if(choice==='local'&&c.local){await upsertRemote(c.collection,c.local,true,0)}meta.conflicts=meta.conflicts.filter(x=>x.key!==key);saveData('Cloud-Konflikt aufgelöst');return true}
  async function putCloudFile(doc,blob){const {url,key}=assertConfig(),s=await getSession(),hid=cloud().householdId,path=`${hid}/${doc.id}`;const objectPath=path.split('/').map(encodeURIComponent).join('/'),r=await fetch(`${url}/storage/v1/object/finance-documents/${objectPath}`,{method:'POST',headers:{apikey:key,Authorization:`Bearer ${s.access_token}`,'Content-Type':doc.type||'application/octet-stream','x-upsert':'true'},body:blob});if(!r.ok)throw new Error(`Dokument-Upload ${r.status}`);return true}
  async function syncDocuments(){if(typeof getAllStoredFiles!=='function')return {uploaded:0};const files=await getAllStoredFiles(),docs=new Map((data.documents||[]).map(d=>[d.id,d]));let uploaded=0;for(const f of files){const d=docs.get(f.id);if(!d||d.cloudUploadedAt||!f.blob)continue;await putCloudFile(d,f.blob);d.cloudUploadedAt=new Date().toISOString();uploaded++}if(uploaded)saveData(`${uploaded} Beleg(e) in Cloud gesichert`);return {uploaded}}
  async function fullSync(){const records=await syncRecords();let documents={uploaded:0};try{documents=await syncDocuments()}catch(e){console.warn('Document cloud sync',e)}return {...records,documents}}
  window.FinanzCloud={cloud,cfg,signUp,signIn,signOut,getSession,refresh,api,createHousehold,listHouseholds,selectHousehold,members,createInvite,acceptInvite,syncRecords,syncDocuments,fullSync,resolveConflict,loadSession};
  loadSession().catch(()=>{});
})();
