'use strict';
(function(){
  const normDate=s=>{s=String(s||'').trim();if(/^\d{8}/.test(s))return `${s.slice(0,4)}-${s.slice(4,6)}-${s.slice(6,8)}`;if(/^\d{6}/.test(s)){const yy=Number(s.slice(0,2)),y=yy>=70?1900+yy:2000+yy;return `${y}-${s.slice(2,4)}-${s.slice(4,6)}`}return FinanceLib.normalizeDate(s)};
  const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
  const parseAmount=s=>Math.abs(FinanceLib.parseMoney(String(s||'').replace(',', '.'))||0);
  function rowsToTransactions(rows,source='statement'){
    const accountId=data.integrations?.n26?.localAccountId||data.accounts?.[0]?.id||'';return rows.map(r=>{const signed=Number(r.signedAmount??r.amount??0),type=signed<0?'expense':'income',title=clean(r.title||r.payee||r.memo||'Bankumsatz'),merchant=clean(r.payee||r.merchant||'');const draft=applyMerchantRule(merchant||title,{categoryId:'',accountId}),cat=data.categories.find(c=>c.id===draft.categoryId)||data.categories.find(c=>c.kind===(type==='income'?'income':'expense'));const tx={id:uid('tx'),date:normDate(r.date)||localISO(new Date()),title,merchant,amount:eurosFromSigned(signed),type,categoryId:cat?.id||'',accountId:draft.accountId||accountId,memberId:data.members?.[0]?.id||'',status:'paid',note:clean(r.memo||r.reference||''),tags:['bankimport'],source,externalId:String(r.externalId||'')};tx.fingerprint=transactionFingerprint(tx);return tx}).filter(t=>t.amount>0)}
  function eurosFromSigned(v){return Math.abs(Math.round(Number(v||0)*100)/100)}

  function parseQIF(text){const rows=[];for(const block of String(text).replace(/\r/g,'').split('^')){const r={};for(const line of block.split('\n')){const k=line[0],v=line.slice(1).trim();if(k==='D')r.date=v;else if(k==='T')r.signedAmount=FinanceLib.parseMoney(v);else if(k==='P')r.payee=v;else if(k==='M')r.memo=v;else if(k==='N')r.externalId=v;else if(k==='L')r.category=v}if(r.signedAmount&&r.date)rows.push(r)}return rows}
  function tag(block,name){const m=String(block).match(new RegExp(`<${name}>([^<\\r\\n]+)`,'i'));return m?clean(m[1]):''}
  function parseOFX(text){const rows=[],src=String(text).replace(/\r/g,'');const blocks=src.match(/<STMTTRN>[\s\S]*?(?:<\/STMTTRN>|(?=<STMTTRN>|<\/BANKTRANLIST>))/gi)||[];for(const b of blocks){const amount=FinanceLib.parseMoney(tag(b,'TRNAMT'));if(!amount)continue;rows.push({date:normDate(tag(b,'DTPOSTED')),signedAmount:amount,payee:tag(b,'NAME'),memo:tag(b,'MEMO'),externalId:tag(b,'FITID'),reference:tag(b,'CHECKNUM')})}return rows}
  function parseMT940(text){const rows=[],lines=String(text).replace(/\r/g,'').split('\n');let current=null;for(const raw of lines){const line=raw.trim();if(line.startsWith(':61:')){if(current)rows.push(current);const s=line.slice(4),m=s.match(/^(\d{6})(?:\d{4})?([CD])(?:R)?([0-9,.]+)(.*)$/);if(!m){current=null;continue}current={date:normDate(m[1]),signedAmount:(m[2]==='D'?-1:1)*FinanceLib.parseMoney(m[3]),reference:clean(m[4])}}else if(line.startsWith(':86:')&&current){const d=line.slice(4).replace(/\?\d{2}/g,' ');current.memo=clean(d);const name=d.match(/(?:NAME|EREF|SVWZ|KREF)[+: ]+([^?]+)/i);if(name)current.payee=clean(name[1])}}if(current)rows.push(current);return rows}
  function xmlText(node,names){for(const name of names){const els=node.getElementsByTagNameNS?.('*',name);if(els?.length&&els[0].textContent)return clean(els[0].textContent);const e=node.querySelector?.(name);if(e?.textContent)return clean(e.textContent)}return''}
  function parseCAMT(text){const doc=new DOMParser().parseFromString(String(text),'application/xml');if(doc.querySelector('parsererror'))throw new Error('CAMT-XML konnte nicht gelesen werden');const entries=[...doc.getElementsByTagNameNS('*','Ntry')],rows=[];for(const n of entries){const amtNode=n.getElementsByTagNameNS('*','Amt')[0],amount=FinanceLib.parseMoney(amtNode?.textContent||'0');if(!amount)continue;const ind=xmlText(n,['CdtDbtInd']),signedAmount=(ind==='DBIT'?-1:1)*Math.abs(amount),date=xmlText(n,['BookgDt']);const dtNode=n.getElementsByTagNameNS('*','BookgDt')[0],dt=dtNode?xmlText(dtNode,['Dt','DtTm']):date,details=n.getElementsByTagNameNS('*','TxDtls')[0]||n;const creditor=xmlText(details,['Cdtr','Nm']),debtor=xmlText(details,['Dbtr','Nm']),memo=xmlText(details,['Ustrd','AddtlTxInf','AddtlNtryInf']),reference=xmlText(details,['EndToEndId','AcctSvcrRef','NtryRef']);rows.push({date:normDate(dt.slice(0,10)),signedAmount,payee:ind==='DBIT'?creditor:debtor,memo,reference,externalId:reference})}return rows}
  function detectAndParse(file,text){const lower=file.name.toLowerCase();if(lower.endsWith('.qif'))return {format:'QIF',rows:parseQIF(text)};if(lower.endsWith('.ofx')||lower.endsWith('.qfx')||/<OFX[>\s]/i.test(text))return {format:'OFX',rows:parseOFX(text)};if(lower.endsWith('.mt940')||lower.endsWith('.sta')||/^:20:/m.test(text))return {format:'MT940',rows:parseMT940(text)};if(lower.includes('camt')||/<(?:\w+:)?BkToCstmrStmt\b/i.test(text)||/<(?:\w+:)?Ntry\b/i.test(text))return {format:'CAMT.053',rows:parseCAMT(text)};return null}
  async function importStatementFile(file){const text=await file.text(),parsed=detectAndParse(file,text);if(!parsed)return false;const candidates=rowsToTransactions(parsed.rows,parsed.format.toLowerCase().replace('.','')),dups=candidates.filter(t=>(t.externalId&&data.transactions.some(x=>x.externalId===t.externalId))||isDuplicateTransaction(t)).length,valid=candidates.length-dups;openModal(`${parsed.format} importieren`,`${candidates.length} Bankumsätze erkannt. Händlerregeln und Duplikaterkennung werden automatisch angewendet.`,`<div class="three"><div class="kpi-small"><small>Erkannt</small><strong>${candidates.length}</strong></div><div class="kpi-small"><small>Duplikate</small><strong>${dups}</strong></div><div class="kpi-small"><small>Neu</small><strong>${valid}</strong></div></div><div class="modal-actions"><button type="button" class="secondary-button" data-cancel>Abbrechen</button><button id="statementImportGo" class="primary-button">${valid} Buchungen übernehmen</button></div>`,()=>{$('#statementImportGo').onclick=()=>{let added=0;for(const tx of candidates){if((tx.externalId&&data.transactions.some(x=>x.externalId===tx.externalId))||isDuplicateTransaction(tx))continue;data.transactions.push(tx);added++}closeModal();detectSubscriptionSuggestions?.();saveData(`${added} ${parsed.format}-Buchungen importiert`)};$('[data-cancel]').onclick=closeModal});return true}

  const baseHandle=typeof handleImportFile==='function'?handleImportFile:null;if(baseHandle)handleImportFile=async function(file){if(!file)return;try{if(await importStatementFile(file))return}catch(e){toast(`${e.message}`,'error');return}return baseHandle(file)};
  window.FinanzStatementImport={parseQIF,parseOFX,parseMT940,parseCAMT,detectAndParse,rowsToTransactions,importStatementFile};
})();
