'use strict';
(function(){
  function centralBackend(){data.integrations=data.integrations||{};return String(data.integrations.backendUrl||data.integrations.n26?.backendUrl||data.integrations.ai?.backendUrl||'')}
  function setCentralBackend(v){data.integrations=data.integrations||{};data.integrations.backendUrl=String(v||'').trim().replace(/\/$/,'');data.integrations.n26=data.integrations.n26||{};data.integrations.ai=data.integrations.ai||{};if(!data.integrations.n26.backendUrl)data.integrations.n26.backendUrl=data.integrations.backendUrl;if(!data.integrations.ai.backendUrl)data.integrations.ai.backendUrl=data.integrations.backendUrl}
  function acceptInviteDialog(){openModal('Cloud-Einladung annehmen','Melde dich zuerst mit dem E-Mail-Konto an, an das die Einladung geschickt wurde.',`<form id="acceptInviteForm"><div class="field"><label>Einladungscode</label><input name="token" class="input" autocomplete="off" required></div><div class="modal-actions"><button type="button" class="secondary-button" data-cancel>Abbrechen</button><button class="primary-button">Einladung annehmen</button></div></form>`,()=>{const f=$('#acceptInviteForm');f.onsubmit=async e=>{e.preventDefault();try{const r=await FinanzCloud.acceptInvite(String(new FormData(f).get('token')).trim());closeModal();saveData('Cloud-Einladung angenommen');toast('Haushalt wurde verbunden','success');return r}catch(err){toast(err.message,'error')}};$('[data-cancel]').onclick=closeModal})}
  async function pushCenter(){const p=FinanzPush.cfg(),st=await FinanzPush.status();openModal('Server-Push','Erinnerungen funktionieren bei aktivem Backend auch dann, wenn die PWA geschlossen ist.',`<div class="three"><div class="kpi-small"><small>Browser</small><strong>${st.supported?'Unterstützt':'Nicht unterstützt'}</strong></div><div class="kpi-small"><small>Gerät registriert</small><strong>${st.subscribed?'Ja':'Nein'}</strong></div><div class="kpi-small"><small>Letzte Planung</small><strong>${p.lastSchedule?new Date(p.lastSchedule).toLocaleString('de-DE'):'—'}</strong></div></div><div class="action-row" style="margin-top:16px"><button id="pushEnable" class="primary-button">Push aktivieren</button><button id="pushSync" class="secondary-button">Erinnerungen planen</button><button id="pushTest" class="secondary-button">Test senden</button><button id="pushDisable" class="danger-button">Deaktivieren</button></div><div class="modal-actions"><button class="secondary-button" data-cancel>Schließen</button></div>`,()=>{$('#pushEnable').onclick=async()=>{try{await FinanzPush.subscribe();await FinanzPush.syncJobs();toast('Server-Push aktiviert','success');pushCenter()}catch(e){toast(e.message,'error')}};$('#pushSync').onclick=async()=>{try{const r=await FinanzPush.syncJobs();toast(`${r.scheduled} Erinnerungen geplant`,'success');pushCenter()}catch(e){toast(e.message,'error')}};$('#pushTest').onclick=async()=>{try{const r=await FinanzPush.test();toast(`${r.sent||0} Test-Push gesendet`,'success')}catch(e){toast(e.message,'error')}};$('#pushDisable').onclick=async()=>{await FinanzPush.unsubscribe();toast('Push auf diesem Gerät deaktiviert');pushCenter()};$('[data-cancel]').onclick=closeModal})}
  const baseSettings=renderSettings;renderSettings=function(){baseSettings();const root=$('#view-settings');if($('#v31IntegrationSetup',root))return;root.insertAdjacentHTML('beforeend',`<article id="v31IntegrationSetup" class="card" style="margin-top:16px"><div class="card-title-row"><div><h2>Online-Dienste</h2><p>Optional: ein gemeinsames kostenloses Backend für Multiuser, N26, Push und Cloud-KI</p></div><span class="tag ${navigator.onLine?'green':'amber'}">${navigator.onLine?'Online':'Offline'}</span></div><div class="setting-row"><div><b>Finanzplan API</b><small style="display:block;color:var(--muted)">${escapeHTML(centralBackend()||'Noch nicht hinterlegt')}</small></div><button id="setCentralBackend" class="secondary-button">Backend</button></div><div class="setting-row"><div><b>Einladungscode</b><small style="display:block;color:var(--muted)">Vorhandenem Cloud-Haushalt beitreten</small></div><button id="acceptCloudInvite" class="secondary-button">Annehmen</button></div><div class="setting-row"><div><b>Server-Push</b><small style="display:block;color:var(--muted)">Fälligkeiten, Budgets und Kündigungsfristen im Hintergrund</small></div><button id="serverPushCenter" class="secondary-button">Verwalten</button></div></article>`);$('#setCentralBackend',root).onclick=()=>{const v=prompt('URL des Finanzplan-Backends:',centralBackend()||'https://finanzplan-api.onrender.com');if(v){setCentralBackend(v);saveData('Backend-URL gespeichert');renderSettings()}};$('#acceptCloudInvite',root).onclick=acceptInviteDialog;$('#serverPushCenter',root).onclick=()=>pushCenter().catch(e=>toast(e.message,'error'))};
  window.FinanzIntegrationsUI={centralBackend,setCentralBackend,acceptInviteDialog,pushCenter};
})();
