'use strict';
(function(){
  const KEY='finanzplan:passkey-prf:v31';
  const te=new TextEncoder();
  const b64url=u=>bytesToB64(u).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'');
  const fromB64url=s=>b64ToBytes(String(s).replaceAll('-','+').replaceAll('_','/')+'==='.slice((String(s).length+3)%4));
  function wrapper(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
  function available(){return !!(window.PublicKeyCredential&&navigator.credentials&&window.crypto?.subtle)}
  async function keyFromPin(pin,salt){const mat=await crypto.subtle.importKey('raw',te.encode(pin),'PBKDF2',false,['deriveBits']),raw=new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},mat,256)),key=await crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['encrypt','decrypt']);return {raw,key}}
  async function prfKey(out){const raw=out instanceof Uint8Array?out:new Uint8Array(out);return crypto.subtle.importKey('raw',raw.slice(0,32),{name:'AES-GCM'},false,['encrypt','decrypt'])}
  async function evaluatePrf(credId,salt){const id=fromB64url(credId),assertion=await navigator.credentials.get({publicKey:{challenge:crypto.getRandomValues(new Uint8Array(32)),allowCredentials:[{type:'public-key',id}],userVerification:'required',timeout:60000,extensions:{prf:{evalByCredential:{[credId]:{first:salt}}}}}});const first=assertion?.getClientExtensionResults?.()?.prf?.results?.first;if(!first)throw new Error('Der Geräte-Passkey unterstützt PRF nicht');return new Uint8Array(first)}
  async function setup(pin){if(!available())throw new Error('Passkeys werden auf diesem Gerät nicht unterstützt');const payload=safeJSON(localStorage.getItem(VAULT_KEY));if(!payload||!data.settings?.vault)throw new Error('Zuerst den Finanz-Tresor aktivieren');const vaultSalt=b64ToBytes(payload.salt),derived=await keyFromPin(pin,vaultSalt);try{await decryptWithKey(payload,derived.key)}catch{throw new Error('Tresor-PIN ist nicht korrekt')}
    const userId=crypto.getRandomValues(new Uint8Array(16)),prfSalt=crypto.getRandomValues(new Uint8Array(32)),cred=await navigator.credentials.create({publicKey:{challenge:crypto.getRandomValues(new Uint8Array(32)),rp:{name:'Finanzplan'},user:{id:userId,name:'finanzplan-vault',displayName:'Finanzplan Tresor'},pubKeyCredParams:[{type:'public-key',alg:-7},{type:'public-key',alg:-257}],authenticatorSelection:{authenticatorAttachment:'platform',residentKey:'preferred',userVerification:'required'},timeout:60000,attestation:'none',extensions:{prf:{eval:{first:prfSalt}}}}});if(!cred)throw new Error('Passkey-Erstellung abgebrochen');const credId=b64url(new Uint8Array(cred.rawId));let first=cred.getClientExtensionResults?.()?.prf?.results?.first;if(!first)first=await evaluatePrf(credId,prfSalt);const wrapKey=await prfKey(first),iv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},wrapKey,derived.raw);localStorage.setItem(KEY,JSON.stringify({version:1,credentialId:credId,prfSalt:bytesToB64(prfSalt),iv:bytesToB64(iv),wrappedKey:bytesToB64(new Uint8Array(cipher)),createdAt:new Date().toISOString()}));return true
  }
  async function unlock(){const w=wrapper(),payload=safeJSON(localStorage.getItem(VAULT_KEY));if(!w||!payload)throw new Error('Kein Cold-Start-Passkey eingerichtet');const prf=await evaluatePrf(w.credentialId,b64ToBytes(w.prfSalt)),wrapKey=await prfKey(prf),raw=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64ToBytes(w.iv)},wrapKey,b64ToBytes(w.wrappedKey)),key=await crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['encrypt','decrypt']),restored=await decryptWithKey(payload,key);window.__vaultKey=key;window.__vaultSalt=b64ToBytes(payload.salt);window.__vaultLocked=false;window.__privacyLocked=false;data=restored;migrateV2Data();data.settings.vault=true;data.version='3.1.0';data.schemaVersion=3;renderAll();return true}
  function remove(){localStorage.removeItem(KEY)}
  const baseRotate=typeof rotateVaultKey==='function'?rotateVaultKey:null;if(baseRotate)rotateVaultKey=async function(pin){const r=await baseRotate(pin);remove();toast?.('Tresor-Schlüssel geändert – Cold-Start-Passkey bitte neu einrichten');return r};
  const baseDisable=typeof disableVault==='function'?disableVault:null;if(baseDisable)disableVault=async function(){const r=await baseDisable();remove();return r};
  window.FinanzPasskey={available,wrapper,setup,unlock,remove};
})();
