'use strict';
(function(){
  const b64urlToBytes=s=>{const pad='='.repeat((4-s.length%4)%4),bin=atob((s+pad).replaceAll('-','+').replaceAll('_','/')),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);return u};
  function cfg(){data.integrations=data.integrations||{};return data.integrations.push=data.integrations.push||{enabled:false,lastSchedule:'',deviceName:''}}
  function backend(){return String(data.integrations?.backendUrl||data.integrations?.n26?.backendUrl||data.integrations?.ai?.backendUrl||'').replace(/\/$/,'')}
  async function authHeaders(){const s=await FinanzCloud?.getSession?.();if(!s?.access_token)throw new Error('Für Server-Push zuerst bei Cloud anmelden');return {'Content-Type':'application/json',Authorization:`Bearer ${s.access_token}`}}
  async function api(path,{method='GET',body}={}){const base=backend();if(!base)throw new Error('Backend-URL fehlt');const r=await fetch(`${base}${path}`,{method,headers:await authHeaders(),body:body===undefined?undefined:JSON.stringify(body)}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`Push ${r.status}`);return j}
  async function subscribe(){if(!('Notification'in window)||!('serviceWorker'in navigator)||!('PushManager'in window))throw new Error('Web Push wird auf diesem Gerät nicht unterstützt');const hid=data.integrations?.cloud?.householdId;if(!hid)throw new Error('Bitte zuerst einen Cloud-Haushalt auswählen');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Benachrichtigungen wurden nicht erlaubt');const key=await fetch(`${backend()}/api/push/public-key`,{cache:'no-store'}).then(r=>r.json());if(!key.publicKey)throw new Error('VAPID Public Key fehlt im Backend');const reg=await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64urlToBytes(key.publicKey)});const deviceName=cfg().deviceName||`${navigator.platform||'Gerät'} · Finanzplan`;await api('/api/push/subscribe',{method:'POST',body:{householdId:hid,subscription:sub.toJSON(),deviceName}});cfg().enabled=true;cfg().deviceName=deviceName;saveData('Server-Push aktiviert');return sub}
  async function unsubscribe(){const reg=await navigator.serviceWorker.ready,sub=await reg.pushManager.getSubscription();if(sub)await sub.unsubscribe();cfg().enabled=false;saveData('Server-Push deaktiviert');return true}
  async function status(){if(!('serviceWorker'in navigator)||!('PushManager'in window))return {supported:false,subscribed:false};const reg=await navigator.serviceWorker.ready,sub=await reg.pushManager.getSubscription();return {supported:true,subscribed:!!sub,permission:Notification.permission}}
  async function test(){return api('/api/push/test',{method:'POST',body:{}})}
  function localAt(date,hour=9){const d=new Date(`${date}T${String(hour).padStart(2,'0')}:00:00`);return d.toISOString()}
  function dayBefore(date,days){const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()-days);return localAt(localISO(d),9)}
  function jobs(){const hid=data.integrations?.cloud?.householdId;if(!hid)return[];const out=[],today=new Date(),end=new Date(today);end.setDate(end.getDate()+60);
    for(const t of data.transactions||[]){if((t.status||'paid')!=='planned'||!['expense','income'].includes(t.type))continue;const d=new Date(`${t.date}T12:00:00`);if(d<today||d>end)continue;const source=`payment:${t.id}:${t.date}`,lead=t.type==='expense'?1:0;out.push({household_id:hid,due_at:dayBefore(t.date,lead),title:t.type==='expense'?'Zahlung wird fällig':'Einnahme erwartet',body:`${t.title}: ${money(t.amount)} am ${fmtDate(t.date)}`,url:location.origin+location.pathname,tag:source,source_key:source,sent:false})}
    for(const c of [...(data.contracts||[]),...(data.insurances||[])]){if(c.active===false||typeof cancellationInfo!=='function')continue;let info=null;try{info=cancellationInfo(c)}catch{}if(!info?.deadline)continue;const d=new Date(`${info.deadline}T12:00:00`);if(d<today||d>end)continue;for(const lead of [30,7,1]){const due=new Date(d);due.setDate(due.getDate()-lead);if(due<today)continue;const source=`cancel:${c.id}:${info.deadline}:${lead}`;out.push({household_id:hid,due_at:localAt(localISO(due),9),title:'Kündigungsfrist im Blick',body:`${c.name||c.title}: Frist in ${lead} Tag${lead===1?'':'en'} (${fmtDate(info.deadline)})`,url:location.origin+location.pathname,tag:source,source_key:source,sent:false})}}
    for(const b of data.budgets||[]){if(b.active===false)continue;const spent=typeof categorySpend==='function'?categorySpend(b.categoryId,selectedMonth):0,limit=num(b.amount||b.limit);if(!limit)continue;const ratio=spent/limit*100;if(ratio>=90){const source=`budget:${monthKeyLocal()}:${b.id}:90`;out.push({household_id:hid,due_at:new Date(Date.now()+60*1000).toISOString(),title:'Budget-Warnung',body:`${getCat(b.categoryId)?.name||'Budget'}: ${Math.round(ratio)} % verbraucht`,url:location.origin+location.pathname,tag:source,source_key:source,sent:false})}}
    return out.slice(0,300)}
  function monthKeyLocal(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
  async function syncJobs(){if(!cfg().enabled||!data.integrations?.cloud?.householdId)return {scheduled:0};const list=jobs();if(!list.length)return {scheduled:0};await FinanzCloud.api('/rest/v1/push_jobs?on_conflict=household_id,source_key',{method:'POST',body:list,prefer:'resolution=merge-duplicates,return=minimal'});cfg().lastSchedule=new Date().toISOString();saveData(`${list.length} Push-Erinnerungen synchronisiert`);return {scheduled:list.length}}
  window.FinanzPush={cfg,backend,subscribe,unsubscribe,status,test,jobs,syncJobs};
})();
