'use strict';
function csvEscape(v){const s=String(v??'');return /[;"\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function exportCSV(){const rows=[['Datum','Bezeichnung','Betrag','Typ','Kategorie','Konto','Person','Status','Notiz','Tags'],...data.transactions.sort((a,b)=>a.date.localeCompare(b.date)).map(t=>[t.date,t.title,t.amount,t.type,getCat(t.categoryId).name,getAccount(t.accountId).name,getMember(t.memberId).name,t.status||'paid',t.note||'',(t.tags||[]).join(',')])];download(`finanzplan-transaktionen-${localISO(now)}.csv`,'\uFEFF'+rows.map(r=>r.map(csvEscape).join(';')).join('\n'),'text/csv;charset=utf-8');toast('CSV exportiert','success')}
function exportXLS(){const rows=data.transactions.sort((a,b)=>a.date.localeCompare(b.date)).map(t=>`<tr><td>${escapeHTML(t.date)}</td><td>${escapeHTML(t.title)}</td><td>${num(t.amount).toFixed(2)}</td><td>${escapeHTML(t.type)}</td><td>${escapeHTML(getCat(t.categoryId).name)}</td><td>${escapeHTML(getAccount(t.accountId).name)}</td><td>${escapeHTML(t.status||'paid')}</td></tr>`).join('');const html=`<html><head><meta charset="utf-8"></head><body><table border="1"><tr><th>Datum</th><th>Bezeichnung</th><th>Betrag</th><th>Typ</th><th>Kategorie</th><th>Konto</th><th>Status</th></tr>${rows}</table></body></html>`;download(`finanzplan-${localISO(now)}.xls`,html,'application/vnd.ms-excel;charset=utf-8');toast('Excel-kompatible Datei exportiert','success')}
function exportJSON(){download(`finanzplan-backup-${localISO(now)}.json`,JSON.stringify({app:'Finanzplan',version:APP_VERSION,exportedAt:new Date().toISOString(),data},null,2),'application/json;charset=utf-8');toast('Vollbackup exportiert','success')}
function pdfEscape(s){return String(s).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)').replace(/[^\x20-\x7E]/g,c=>({'ä':'ae','ö':'oe','ü':'ue','Ä':'Ae','Ö':'Oe','Ü':'Ue','ß':'ss','€':'EUR'}[c]||'?'))}
function makeSimplePDF(lines){
  const text=lines.slice(0,45).map((l,i)=>`BT /F1 ${i===0?18:10} Tf 50 ${790-i*16} Td (${pdfEscape(l)}) Tj ET`).join('\n');
  const objs=[];objs[1]='<< /Type /Catalog /Pages 2 0 R >>';objs[2]='<< /Type /Pages /Kids [3 0 R] /Count 1 >>';objs[3]='<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>';objs[4]=`<< /Length ${text.length} >>\nstream\n${text}\nendstream`;objs[5]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';
  let pdf='%PDF-1.4\n',offsets=[0];for(let i=1;i<=5;i++){offsets[i]=pdf.length;pdf+=`${i} 0 obj\n${objs[i]}\nendobj\n`}const xref=pdf.length;pdf+='xref\n0 6\n0000000000 65535 f \n';for(let i=1;i<=5;i++)pdf+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;pdf+=`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return pdf
}
function exportPDF(){const s=monthSummary(),b=categoryBreakdown();const lines=[`Finanzplan - Monatsbericht ${fmtMonth(selectedMonth)}`,`Erstellt: ${new Date().toLocaleString('de-DE')}`,'',`Einnahmen: ${money(s.income)}`,`Ausgaben: ${money(s.expense)}`,`Saldo: ${money(s.balance)}`,`Geplante Einnahmen: ${money(s.plannedIncome)}`,`Geplante Ausgaben: ${money(s.plannedExpense)}`,`Prognose Monatsende: ${money(s.forecast)}`,`Sparquote: ${pct(savingsRate())}`,`Fixkosten pro Monat: ${money(fixedMonthly())}`,`Nettovermoegen: ${money(netWorth())}`,`Finanz-Score: ${financeScore()}/100`,'','Ausgaben nach Kategorie:',...b.map(x=>`${x.cat.name}: ${money(x.value)}`),'','Hinweise:',...insights().map(x=>`- ${x.t}: ${x.p}`)];download(`finanzplan-monatsbericht-${monthKey(selectedMonth)}.pdf`,makeSimplePDF(lines),'application/pdf');toast('PDF-Bericht exportiert','success')}
function parseCSV(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];const delim=lines[0].includes(';')?';':',';const parseLine=line=>{const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(c===delim&&!q){out.push(cur);cur=''}else cur+=c}out.push(cur);return out};const headers=parseLine(lines[0]).map(h=>h.trim().toLowerCase());return lines.slice(1).map(parseLine).map(cols=>Object.fromEntries(headers.map((h,i)=>[h,cols[i]||''])))}
function mapImportedTransactions(rows){let count=0;for(const r of rows){const date=r.datum||r.date;const title=r.bezeichnung||r.title||r.name||'Import';let amount=num(r.betrag||r.amount),type=(r.typ||r.type||'').toLowerCase();if(!type)type=amount<0?'expense':'income';amount=Math.abs(amount);if(!date||!amount)continue;const catName=r.kategorie||r.category;const cat=data.categories.find(c=>c.name.toLowerCase()===String(catName||'').toLowerCase())||data.categories.find(c=>c.kind===(type==='income'?'income':'expense'))||getCat('');const accName=r.konto||r.account;const acc=data.accounts.find(a=>a.name.toLowerCase()===String(accName||'').toLowerCase())||data.accounts[0];data.transactions.push({id:uid('tx'),date:String(date).slice(0,10),title,amount,type:type==='income'?'income':'expense',categoryId:cat.id,accountId:acc?.id||'',memberId:data.members[0]?.id||'',status:(r.status||'paid').toLowerCase(),note:r.notiz||r.note||'',tags:['import']});count++}return count}
async function handleImportFile(file){if(!file)return;const text=await file.text();autoSnapshot();if(file.name.toLowerCase().endsWith('.json')){const obj=safeJSON(text);const restored=obj?.data||obj;if(restored?.transactions&&restored?.accounts){if(confirm('Das JSON-Vollbackup ersetzt die aktuellen App-Daten. Fortfahren?')){data=restored;localStorage.setItem(STORE_KEY,JSON.stringify(data));closeModal();renderAll();toast('Backup wiederhergestellt','success')}}else toast('Ungültiges Finanzplan-Backup','error');return}
  if(file.name.toLowerCase().endsWith('.xls')||file.name.toLowerCase().endsWith('.xml')){const tmp=document.createElement('div');tmp.innerHTML=text;const table=tmp.querySelector('table');if(!table){toast('Diese Excel-Datei kann ohne XLSX-Parser nicht gelesen werden','error');return}const trs=[...table.querySelectorAll('tr')],heads=[...trs.shift().querySelectorAll('th,td')].map(x=>x.textContent.trim());const rows=trs.map(tr=>Object.fromEntries([...tr.querySelectorAll('td')].map((td,i)=>[heads[i]||`col${i}`,td.textContent.trim()])));const c=mapImportedTransactions(rows);closeModal();saveData(`${c} Excel-Zeilen importiert`);return}
  const rows=parseCSV(text),c=mapImportedTransactions(rows);closeModal();saveData(`${c} CSV-Buchungen importiert`)
}