'use strict';

// Ein Abgleich ist ein echter Konten-Checkpoint. Neue Buchungen am selben Kalendertag
// werden danach weitergezählt, bereits vorhandene Buchungen am Stichtag nicht doppelt.
relevantReconciliation=function(accountId,dateISO){return data.reconciliations.filter(r=>r.accountId===accountId&&r.date<=dateISO).sort((a,b)=>b.date.localeCompare(a.date)||String(b.createdAt||'').localeCompare(String(a.createdAt||'')))[0]||null};
reconcileAccount=function(accountId,balance,date=localISO(now),note='Manueller Kontenabgleich'){const a=data.accounts.find(x=>x.id===accountId);if(!a)return null;const checkpoint=FinanceLib.normalizeDate(date)||localISO(now),coveredIds=data.transactions.filter(t=>{const td=FinanceLib.normalizeDate(t.date);return td&&td<=checkpoint&&(t.accountId===accountId||t.targetAccountId===accountId)}).map(t=>t.id),rec={id:uid('recon'),accountId,date:checkpoint,balance:num(balance),note,coveredIds,createdAt:new Date().toISOString()};data.reconciliations.push(rec);return rec};
accountBalanceAtDate=function(aOrId,dateISO=localISO(now)){const a=typeof aOrId==='string'?data.accounts.find(x=>x.id===aOrId):aOrId;if(!a)return 0;dateISO=FinanceLib.normalizeDate(dateISO)||localISO(now);if(a.openingDate&&dateISO<a.openingDate)return 0;const rec=relevantReconciliation(a.id,dateISO),covered=rec?.coveredIds?new Set(rec.coveredIds):null;let base=rec?num(rec.balance):num(a.openingBalance),from=rec?rec.date:a.openingDate;for(const t of data.transactions){const td=FinanceLib.normalizeDate(t.date);if(!td||td>dateISO)continue;if(rec){if(td<from)continue;if(td===from&&(covered?covered.has(t.id):true))continue}else if(td<from)continue;base+=txAccountImpact(t,a.id)}return base};
accountBalance=function(aOrId){return accountBalanceAtDate(aOrId,localISO(now))};
accountTotalAtDate=function(date=localISO(now)){return data.accounts.reduce((s,a)=>s+accountBalanceAtDate(a,date),0)};
accountTotal=function(){return accountTotalAtDate(localISO(now))};
netWorthAtDate=function(date=localISO(now)){return data.accounts.filter(a=>a.includeNetWorth!==false).reduce((s,a)=>s+accountBalanceAtDate(a,date),0)-data.debts.reduce((s,d)=>s+debtBalanceAtDate(d,date),0)};
netWorth=function(){return netWorthAtDate(localISO(now))};

// Dokumente bleiben im Papierkorb physisch erhalten und werden erst nach der Aufbewahrungsfrist gelöscht.
deleteStoredFile=async function(id){const doc=data.documents.find(d=>d.id===id);if(!doc)return;const deletedAt=new Date().toISOString();try{const db=await openFileDB(),rec=await new Promise((resolve,reject)=>{const r=db.transaction('files').objectStore('files').get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});if(rec)await new Promise((resolve,reject)=>{const tr=db.transaction('files','readwrite');tr.objectStore('files').put({...rec,deletedAt});tr.oncomplete=resolve;tr.onerror=()=>reject(tr.error)})}catch(_){}data.trash.push({id:uid('trash'),collection:'documents',item:{...doc},label:`Dokument ${doc.name}`,deletedAt});data.documents=data.documents.filter(d=>d.id!==id);saveData('Dokument in Papierkorb verschoben')};
const edgeRestoreTrash=restoreTrash;restoreTrash=function(id){const row=data.trash.find(x=>x.id===id);if(row?.collection!=='documents')return edgeRestoreTrash(id);data.documents.push(row.item);data.trash=data.trash.filter(x=>x.id!==id);openFileDB().then(db=>new Promise(resolve=>{const r=db.transaction('files').objectStore('files').get(row.item.id);r.onsuccess=()=>{const rec=r.result;if(!rec)return resolve();const tr=db.transaction('files','readwrite');tr.objectStore('files').put({...rec,deletedAt:''});tr.oncomplete=resolve;tr.onerror=resolve};r.onerror=resolve})).catch(()=>{});saveData(`Dokument ${row.item.name} wiederhergestellt`);return true};
async function purgeExpiredDocumentBlobsEdge(){const days=num(data.settings?.trashDays)||30,limit=Date.now()-days*86400000;try{const db=await openFileDB(),records=await new Promise((resolve,reject)=>{const r=db.transaction('files').objectStore('files').getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)}),expired=records.filter(r=>r.deletedAt&&new Date(r.deletedAt).getTime()<=limit);if(expired.length)await new Promise(resolve=>{const tr=db.transaction('files','readwrite'),store=tr.objectStore('files');expired.forEach(r=>store.delete(r.id));tr.oncomplete=resolve;tr.onerror=resolve});const ids=new Set(expired.map(r=>r.id));data.trash=data.trash.filter(x=>!(x.collection==='documents'&&ids.has(x.item?.id)))}catch(_){}}
purgeExpiredDocumentBlobsEdge();

// Nach der letzten Override-Schicht einmal neu rechnen, damit ein bestehender Haushalt sofort
// den gehärteten Kontenstand und Nettovermögenswert sieht.
if(typeof renderAll==='function'&&!window.__vaultLocked)renderAll();
