'use strict';
(function(){
  const baseLocal=FinanzAI.localExplain.bind(FinanzAI);
  function categoryDelta(){const now=new Date(),prev=new Date(now.getFullYear(),now.getMonth()-1,1),cur=typeof categoryBreakdown==='function'?categoryBreakdown(now):[],old=typeof categoryBreakdown==='function'?categoryBreakdown(prev):[],m=new Map(old.map(x=>[x.cat?.id||x.id,num(x.value||x.amount)]));return cur.map(x=>({name:x.cat?.name||x.name||'Sonstiges',value:num(x.value||x.amount),previous:m.get(x.cat?.id||x.id)||0})).map(x=>({...x,diff:x.value-x.previous})).sort((a,b)=>Math.abs(b.diff)-Math.abs(a.diff))}
  function savingsIdeas(){const auto=FinanzPremium.autopilot(),ideas=[];for(const x of categoryDelta().filter(x=>x.diff>20).slice(0,3))ideas.push(`${x.name} liegt ${money(x.diff)} über dem Vormonat.`);for(const c of auto.contracts.filter(x=>x.kind==='review').slice(0,2))ideas.push(`${c.title}: ${money(c.monthly)}/Monat – Tarif prüfen.`);const candidates=FinanzIntelligence.recurringCandidates().slice(0,2);for(const c of candidates)ideas.push(`${c.merchant}: wiederkehrende Abbuchung ${money(c.amount)} erkannt; als Vertrag prüfen.`);return ideas}
  function enhanced(question){const q=FinanceLib.normalizeText(question),ctx=FinanzAI.financeContext(question);if(/wo.*spar|sparen|einspar|optimier/.test(q)){const ideas=savingsIdeas();return ideas.length?`Die stärksten Ansatzpunkte sind: ${ideas.join(' ')}`:'Aktuell sehe ich keinen einzelnen klaren Kostentreiber. Prüfe vor allem variable Kategorien und laufende Verträge.'}if(/geändert|veraendert|unterschied|letzten monat|vormonat/.test(q)){const d=categoryDelta().slice(0,4);if(!d.length)return'Für einen belastbaren Monatsvergleich sind noch nicht genug kategorisierte Buchungen vorhanden.';return `Gegenüber dem Vormonat fallen besonders auf: ${d.map(x=>`${x.name} ${x.diff>=0?'+':''}${money(x.diff)}`).join(', ')}.`}if(/vertrag|abo|abonnement/.test(q)){const cands=FinanzIntelligence.recurringCandidates(),active=(data.contracts||[]).filter(c=>c.active!==false);return `Es sind ${active.length} aktive Verträge hinterlegt${cands.length?` und ${cands.length} weitere wiederkehrende Abbuchung(en) als Vertragskandidaten erkannt`:''}. ${FinanzPremium.contractOptimization().slice(0,3).map(x=>x.detail).join(' ')}`.trim()}if(/auffällig|auffaellig|doppelt|anomal/.test(q)){const a=FinanzPremium.anomalies();return a.length?`Ich habe ${a.length} Auffälligkeit(en) gefunden. ${a.slice(0,4).map(x=>`${x.title}: ${x.type==='duplicate'?'mögliche Doppelbuchung':`${money(x.current)} statt typisch ${money(x.baseline)}`}`).join(' ')}`:'Aktuell wurden keine deutlichen Anomalien oder Doppelbuchungen erkannt.'}if(/prognose|monatsende|schlimm|best case|worst case/.test(q)){const f=FinanzPremium.uncertaintyForecast();return `Die Monatsend-Prognose liegt zwischen ${money(f.monthEnd.conservative)} konservativ und ${money(f.monthEnd.optimistic)} optimistisch; Basisszenario ${money(f.monthEnd.base)}. Datenbasis: ${f.confidence}e Sicherheit.`}if(/warum.*weniger|warum.*mehr|kostentreiber/.test(q)){const d=categoryDelta().filter(x=>x.diff>0).slice(0,3);const extra=d.reduce((s,x)=>s+x.diff,0);return d.length?`Der größte Unterschied zum Vormonat kommt aus ${d.map(x=>`${x.name} (+${money(x.diff)})`).join(', ')}. Zusammen erklären diese Bereiche rund ${money(extra)} Mehrkosten.`:baseLocal(question)}return baseLocal(question)}
  FinanzAI.localExplain=enhanced;
  FinanzAI.savingsIdeas=savingsIdeas;
  FinanzAI.categoryDelta=categoryDelta;
  window.FinanzAIPlus={enhanced,savingsIdeas,categoryDelta};
})();
