'use strict';
(function(){
  const USER_MARKER='finanzplan:auth-user:v1';
  const isLocalDev=()=>['localhost','127.0.0.1','::1'].includes(location.hostname)&&!new URL(location.href).searchParams.has('auth_test');
  let currentSession=null,gate=null,busy=false;
  const esc=s=>typeof escapeHTML==='function'?escapeHTML(s):String(s||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  function emailOf(s=currentSession){return String(s?.user?.email||'').trim()}
  function initials(email){const name=String(email||'FP').split('@')[0].replace(/[^a-z0-9äöüß]+/gi,' ').trim(),p=name.split(/\s+/).filter(Boolean);return (p.length>1?p[0][0]+p[1][0]:p[0]?.slice(0,2)||'FP').toUpperCase()}
  function setMessage(text,type='info'){const n=gate?.querySelector('[data-auth-message]');if(!n)return;n.textContent=text||'';n.className=`auth-gate-message ${type}`;n.hidden=!text}
  function setBusy(v,label='Bitte warten …'){busy=!!v;if(!gate)return;gate.querySelectorAll('button,input').forEach(x=>x.disabled=busy);const b=gate.querySelector('[data-auth-submit]');if(b){if(v){b.dataset.oldLabel=b.textContent;b.textContent=label}else if(b.dataset.oldLabel){b.textContent=b.dataset.oldLabel;delete b.dataset.oldLabel}}}
  function shellHidden(hidden){const app=document.getElementById('appShell');if(!app)return;if(hidden){app.setAttribute('aria-hidden','true');app.inert=true}else{app.removeAttribute('aria-hidden');app.inert=false}}
  function removeGate(){gate?.remove();gate=null;shellHidden(false)}
  function template(mode='login'){
    const register=mode==='register';
    return `<div class="auth-gate-card"><div class="auth-gate-brand"><div class="auth-gate-mark">⌁</div><div><strong>Finanzplan</strong><small>Sicher. Persönlich. Gemeinsam nutzbar.</small></div></div><div class="auth-gate-copy"><span class="auth-eyebrow">${register?'NEUEN ACCOUNT ANLEGEN':'WILLKOMMEN ZURÜCK'}</span><h1>${register?'Deinen Finanzplan starten':'Bei Finanzplan anmelden'}</h1><p>${register?'Erstelle deinen eigenen Zugang. Danach kannst du einen eigenen Haushalt nutzen oder einem gemeinsamen Haushalt beitreten.':'Melde dich an, um auf deinen Haushalt, deine Bankverbindungen und deine Finanzdaten zuzugreifen.'}</p></div><div class="auth-tabs" role="tablist"><button type="button" data-auth-mode="login" class="${register?'':'active'}">Anmelden</button><button type="button" data-auth-mode="register" class="${register?'active':''}">Account erstellen</button></div><form data-auth-form data-mode="${register?'register':'login'}" novalidate>${register?'<div class="field"><label>Name <span>(optional)</span></label><input class="input" name="displayName" autocomplete="name" placeholder="z. B. Anna"></div>':''}<div class="field"><label>E-Mail</label><input class="input" name="email" type="email" autocomplete="email" inputmode="email" required placeholder="name@beispiel.de"></div><div class="field"><label>Passwort</label><input class="input" name="password" type="password" autocomplete="${register?'new-password':'current-password'}" minlength="8" required placeholder="Mindestens 8 Zeichen"></div>${register?'<label class="auth-consent"><input type="checkbox" name="consent" required><span>Ich möchte einen persönlichen Finanzplan-Account erstellen und akzeptiere, dass meine Anmeldung über den Finanzplan-Cloud-Dienst verarbeitet wird.</span></label>':''}<div data-auth-message class="auth-gate-message" hidden></div><button data-auth-submit class="primary-button auth-submit">${register?'Account erstellen':'Anmelden'}</button></form><div class="auth-security"><span>✓</span><p><b>Getrennte Benutzerbereiche</b><br>Bankzugänge und Cloud-Sitzungen sind an deinen persönlichen Account gebunden.</p></div></div>`;
  }
  function show(mode='login'){
    shellHidden(true);
    if(!gate){gate=document.createElement('section');gate.id='finanzplanAuthGate';gate.className='auth-gate';gate.setAttribute('aria-label','Finanzplan Anmeldung');document.body.appendChild(gate)}
    gate.innerHTML=template(mode);
    gate.querySelectorAll('[data-auth-mode]').forEach(b=>b.onclick=()=>{if(!busy)show(b.dataset.authMode)});
    const form=gate.querySelector('[data-auth-form]');
    form.onsubmit=async e=>{e.preventDefault();if(busy)return;const fd=new FormData(form),email=String(fd.get('email')||'').trim().toLowerCase(),password=String(fd.get('password')||''),displayName=String(fd.get('displayName')||'').trim(),formMode=form.dataset.mode;if(!email||!email.includes('@')){setMessage('Bitte gib eine gültige E-Mail-Adresse ein.','error');return}if(password.length<8){setMessage('Das Passwort muss mindestens 8 Zeichen lang sein.','error');return}if(formMode==='register'&&!fd.get('consent')){setMessage('Bitte bestätige die Account-Erstellung.','error');return}setBusy(true,formMode==='register'?'Account wird erstellt …':'Anmeldung läuft …');setMessage('');try{if(formMode==='register'){const r=await FinanzCloud.signUp(email,password,displayName);if(!r?.access_token){setBusy(false);setMessage('Account angelegt. Bitte bestätige jetzt die E-Mail von Supabase und melde dich anschließend hier an.','success');return}currentSession=r}else currentSession=await FinanzCloud.signIn(email,password);await finishLogin(currentSession)}catch(err){setBusy(false);setMessage(humanAuthError(err),'error')}};
    setTimeout(()=>gate?.querySelector('input[name="email"]')?.focus(),40);
  }
  function humanAuthError(err){const m=String(err?.message||err||'Anmeldung fehlgeschlagen');if(/invalid login credentials/i.test(m))return 'E-Mail oder Passwort ist nicht korrekt.';if(/email not confirmed/i.test(m))return 'Bitte bestätige zuerst deine E-Mail-Adresse.';if(/user already registered/i.test(m))return 'Für diese E-Mail existiert bereits ein Account.';if(/network|fetch/i.test(m))return 'Die Anmeldung benötigt gerade eine Internetverbindung.';return m}
  async function isolateUser(session){const uid=String(session?.user?.id||'');if(!uid)return;const previous=localStorage.getItem(USER_MARKER)||'';if(previous&&previous!==uid){await window.__finanzplanStorage?.clearState?.().catch(()=>{});try{data=emptyProjectData(false);FinanzPublicConfig?.apply?.(data);migrateV2Data?.();window.__finanzplanFirstRun=true;sessionStorage.setItem('finanzplan:first-run','1')}catch(e){console.warn('Benutzerwechsel konnte lokale Daten nicht vollständig zurücksetzen',e)}}localStorage.setItem(USER_MARKER,uid)}
  async function ensureHousehold(){let list=[];try{list=await FinanzCloud.listHouseholds()}catch(e){throw new Error(`Haushalt konnte nicht geladen werden: ${e.message}`)}const selected=String(data.integrations?.cloud?.householdId||'');let chosen=list.find(h=>h.id===selected)||list[0]||null;if(!chosen)chosen=await FinanzCloud.createHousehold(data.household?.name||'Mein Haushalt');else await FinanzCloud.selectHousehold(chosen.id);const c=FinanzCloud.cloud();c.enabled=true;return chosen}
  async function finishLogin(session){if(!session?.user?.id)throw new Error('Anmeldung lieferte keinen Benutzer');await isolateUser(session);await ensureHousehold();currentSession=session;removeGate();decorateProfile();window.dispatchEvent(new CustomEvent('finanzplan:authenticated',{detail:{user:session.user}}));return session}
  async function requireSession(){if(isLocalDev())return {localDev:true};show('login');try{const s=await FinanzCloud.getSession();if(s?.user?.id){await finishLogin(s);return s}}catch(e){console.warn('Gespeicherte Finanzplan-Sitzung konnte nicht verwendet werden',e)}return new Promise(resolve=>window.addEventListener('finanzplan:authenticated',e=>resolve({user:e.detail.user}),{once:true}))}
  async function afterStart(){if(isLocalDev())return;decorateProfile();try{if(navigator.onLine&&FinanzCloud.cloud()?.householdId)await FinanzCloud.fullSync()}catch(e){console.warn('Erster Multiuser-Cloud-Sync',e)}decorateProfile()}
  function decorateProfile(){const email=emailOf();if(!email)return;const card=document.querySelector('.profile-card');if(card){const av=card.querySelector('.avatar'),b=card.querySelector('b'),small=card.querySelector('small');if(av)av.textContent=initials(email);if(b)b.textContent=data.household?.name||'Mein Haushalt';if(small)small.textContent=email}const root=document.querySelector('#view-settings');if(root&&!root.querySelector('#authAccountCard'))root.insertAdjacentHTML('beforeend',`<article id="authAccountCard" class="card" style="margin-top:16px"><div class="card-title-row"><div><h2>Dein Finanzplan-Account</h2><p>Dieser Zugang schützt deine persönlichen Finanz- und Bankdaten.</p></div><span class="tag green">Angemeldet</span></div><div class="setting-row"><div><b>${esc(email)}</b><small style="display:block;color:var(--muted)">Cloud-Haushalt: ${esc(data.household?.name||'Mein Haushalt')}</small></div><button id="authLogout" class="secondary-button">Abmelden</button></div></article>`);document.querySelector('#authLogout')?.addEventListener('click',()=>FinanzCloud.signOut())}
  const baseRenderSettings=window.renderSettings;if(typeof baseRenderSettings==='function')window.renderSettings=function(){baseRenderSettings();decorateProfile()};
  const rawSignOut=FinanzCloud.signOut.bind(FinanzCloud);FinanzCloud.signOut=async function(){await rawSignOut();try{await window.__finanzplanStorage?.clearState?.()}catch{}localStorage.removeItem(USER_MARKER);location.reload()};
  window.FinanzAuthGate={requireSession,afterStart,show,finishLogin,decorateProfile,isLocalDev,version:'1.0.0'};
})();
