'use strict';
(function(){
  const providers=new Map();
  function register(p){if(!p?.id)throw new Error('Banking-Provider braucht eine ID');providers.set(p.id,p);return p}
  register({id:'n26',name:'N26',kind:'psd2',capabilities:['balances','transactions','consent'],status:()=>FinanzN26.status(),connect:()=>FinanzN26.start(),sync:o=>FinanzN26.sync(o),ready:()=>!!data.integrations?.n26?.sessionReady});
  register({id:'file',name:'Bankdatei',kind:'local',capabilities:['CSV','XLS','XLSX','XML','QIF','OFX','MT940','CAMT.053'],ready:()=>true});
  function list(){return [...providers.values()].map(p=>({id:p.id,name:p.name,kind:p.kind,capabilities:p.capabilities,ready:!!p.ready?.()}))}
  async function providerStatus(id){const p=providers.get(id);if(!p)throw new Error('Unbekannter Banking-Provider');if(!p.status)return {configured:true,ready:p.ready?.()!==false};try{return await p.status()}catch(e){return {configured:false,ready:false,error:e.message}}}
  async function sync(id='n26',opts={}){const p=providers.get(id);if(!p?.sync)throw new Error('Dieser Provider unterstützt keinen Live-Sync');const r=await p.sync(opts);FinanzIntelligence?.postImport?.();return r}
  async function open(){const n=await providerStatus('n26'),rows=list();openModal('Banking-Zentrale','Providerneutral aufgebaut: heute N26 und Bankdateien, später weitere PSD2-Banken ohne Umbau der Finanzengine.',`<div class="three"><div class="kpi-small"><small>N26-Bridge</small><strong>${n.configured===false?'Zugang fehlt':data.integrations?.n26?.sessionReady?'Verbunden':'Bereit'}</strong></div><div class="kpi-small"><small>Bankdateien</small><strong>8 Formate</strong></div><div class="kpi-small"><small>Auto-Pipeline</small><strong>Händler → Kategorie → Vertrag</strong></div></div><div style="margin-top:16px">${rows.map(p=>`<div class="list-row"><div class="list-icon">${p.kind==='psd2'?'⌁':'⇩'}</div><div><strong>${escapeHTML(p.name)}</strong><small>${escapeHTML(p.capabilities.join(' · '))}</small></div><span class="tag ${p.ready?'green':'amber'}">${p.ready?'bereit':'nicht verbunden'}</span></div>`).join('')}</div><div class="action-row" style="margin-top:16px"><button id="bankConnect" class="primary-button">N26 verbinden</button><button id="bankSync" class="secondary-button">N26 synchronisieren</button><button id="bankImport" class="secondary-button">Bankdatei importieren</button></div><div class="modal-actions"><button class="secondary-button" data-cancel>Schließen</button></div>`,()=>{$('#bankConnect').onclick=async()=>{try{await providers.get('n26').connect()}catch(e){toast(e.message,'error')}};$('#bankSync').onclick=async()=>{try{const r=await sync('n26',{days:180,reconcile:true});toast(`${r.added||0} neue N26-Buchungen`,'success');open()}catch(e){toast(e.message,'error')}};$('#bankImport').onclick=()=>{$('#fileImport')?.click()};$('[data-cancel]').onclick=closeModal})}
  window.FinanzBankingHub={register,list,providerStatus,sync,open,providers};
})();
