'use strict';
(function(){
  const DAY=86400000;
  const norm=s=>FinanceLib.normalizeText(String(s||''));
  const aliases=[['rewe','REWE'],['edeka','EDEKA'],['aldi','ALDI'],['lidl','Lidl'],['netto','Netto'],['amazon','Amazon'],['paypal','PayPal'],['spotify','Spotify'],['netflix','Netflix'],['disney','Disney+'],['youtube','YouTube'],['shell','Shell'],['aral','Aral'],['jet','JET'],['n26','N26']];
  function canonicalMerchant(raw){let s=norm(raw).replace(/\b(ec|kartenzahlung|visa|mastercard|debit|zahlung|lastschrift|sepa|pos|gmbh|ag|kg|ug)\b/g,' ').replace(/\b\d{2,}\b/g,' ').replace(/\s+/g,' ').trim();for(const [needle,name] of aliases)if(s.includes(needle))return name;return s.split(' ').slice(0,4).join(' ').replace(/\b\w/g,c=>c.toUpperCase())||'Unbekannt'}
  function ensure(){data.settings=data.settings||{};data.settings.intelligence=data.settings.intelligence||{merchantLearning:true,contractDetection:true};data.merchantRules=Array.isArray(data.merchantRules)?data.merchantRules:[];return data.settings.intelligence}
  function learnFromHistory(){if(!ensure().merchantLearning)return 0;const groups=new Map();for(const t of data.transactions||[]){if((t.status||'paid')!=='paid'||!['expense','income'].includes(t.type))continue;const merchant=canonicalMerchant(t.merchant||t.title);if(!merchant||merchant==='Unbekannt')continue;const key=norm(merchant);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(t)}let changed=0;for(const [key,rows] of groups){if(rows.length<2)continue;const cats=new Map();for(const t of rows)if(t.categoryId)cats.set(t.categoryId,(cats.get(t.categoryId)||0)+1);const best=[...cats].sort((a,b)=>b[1]-a[1])[0];if(!best||best[1]/rows.length<.7)continue;const existing=data.merchantRules.find(r=>r.learned&&norm(r.pattern)===key);const merchant=canonicalMerchant(rows.at(-1).merchant||rows.at(-1).title),rule={id:existing?.id||uid('mr'),pattern:merchant,merchant,categoryId:best[0],accountId:'',active:true,learned:true,hits:rows.length,confidence:best[1]/rows.length,updatedAt:new Date().toISOString()};if(existing)Object.assign(existing,rule);else{data.merchantRules.push(rule);changed++}}return changed}
  const baseApply=window.applyMerchantRule;
  window.applyMerchantRule=function(title,draft={}){const merchant=canonicalMerchant(title);let out=typeof baseApply==='function'?baseApply(title,draft):draft;const learned=(data.merchantRules||[]).filter(r=>r.active!==false&&r.learned).sort((a,b)=>(b.confidence||0)-(a.confidence||0)).find(r=>norm(merchant).includes(norm(r.pattern))||norm(title).includes(norm(r.pattern)));if(learned)out={...out,categoryId:learned.categoryId||out.categoryId,accountId:learned.accountId||out.accountId,merchant:learned.merchant||merchant};else if(!out.merchant)out={...out,merchant};return out};
  function median(a){const x=a.slice().sort((a,b)=>a-b),m=Math.floor(x.length/2);return x.length?x.length%2?x[m]:(x[m-1]+x[m])/2:0}
  function freq(days){if(days>=24&&days<=38)return'monthly';if(days>=75&&days<=105)return'quarterly';if(days>=160&&days<=205)return'semiannual';if(days>=330&&days<=400)return'annual';return''}
  function recurringCandidates(){if(!ensure().contractDetection)return[];const groups=new Map();for(const t of data.transactions||[]){if(t.type!=='expense'||(t.status||'paid')!=='paid')continue;const merchant=canonicalMerchant(t.merchant||t.title);if(!merchant||merchant==='Unbekannt')continue;const k=norm(merchant);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(t)}const existing=(data.contracts||[]).map(c=>norm(`${c.provider||''} ${c.name||''}`));const out=[];for(const rows0 of groups.values()){const rows=rows0.slice().sort((a,b)=>String(a.date).localeCompare(String(b.date)));if(rows.length<3)continue;const merchant=canonicalMerchant(rows.at(-1).merchant||rows.at(-1).title);if(existing.some(x=>x.includes(norm(merchant))||norm(merchant).includes(x)))continue;const gaps=[];for(let i=1;i<rows.length;i++)gaps.push((new Date(rows[i].date)-new Date(rows[i-1].date))/DAY);const interval=median(gaps),frequency=freq(interval);if(!frequency)continue;const amounts=rows.map(t=>num(t.amount)),m=median(amounts),spread=Math.max(...amounts)-Math.min(...amounts);if(m<=0||spread>Math.max(4,m*.18))continue;const confidence=Math.min(.99,.55+Math.min(rows.length,6)*.05+Math.max(0,.15-spread/Math.max(1,m))+.1);const last=rows.at(-1),next=new Date(last.date);next.setDate(next.getDate()+Math.round(interval));out.push({id:`cand:${norm(merchant)}`,merchant,name:merchant,amount:Math.round(m*100)/100,frequency,nextDate:FinanceLib.iso(next),categoryId:last.categoryId||'',accountId:last.accountId||'',memberId:last.memberId||'',confidence,transactionIds:rows.map(x=>x.id),occurrences:rows.length})}return out.sort((a,b)=>b.confidence-a.confidence)}
  function acceptContractCandidate(c){const contract={id:uid('con'),name:c.name,provider:c.merchant,amount:c.amount,frequency:c.frequency,categoryId:c.categoryId||'c_subs',nextDate:c.nextDate,start:(data.transactions.find(t=>t.id===c.transactionIds?.[0])?.date)||localISO(new Date()),end:'',noticeDays:30,type:'contract',active:true,autoDetected:true,detection:{confidence:c.confidence,transactionIds:c.transactionIds||[],acceptedAt:new Date().toISOString()}};data.contracts.push(contract);saveData('Vertrag automatisch erkannt und übernommen');return contract}
  function sender(){data.settings=data.settings||{};return data.settings.cancellationProfile=data.settings.cancellationProfile||{name:'',address:'',email:''}}
  function cancellationText(contract,extra={}){const p={...sender(),...extra},today=new Date().toLocaleDateString('de-DE'),number=extra.contractNo||contract.contractNo||contract.customerNo||'';return `${p.name||'[Name]'}\n${p.address||'[Anschrift]'}\n${p.email||''}\n\n${contract.provider||contract.name}\n${contract.providerAddress||'[Anbieteranschrift]'}\n\n${today}\n\nKündigung ${contract.name||'Vertrag'}${number?` – Vertrags-/Kundennummer ${number}`:''}\n\nSehr geehrte Damen und Herren,\n\nhiermit kündige ich den oben genannten Vertrag fristgerecht zum nächstmöglichen Zeitpunkt. Bitte bestätigen Sie mir die Kündigung unter Angabe des Beendigungsdatums in Textform.\n\nMit freundlichen Grüßen\n${p.name||'[Name]'}`}
  function exportCancellationPDF(contract,text){const lines=String(text||cancellationText(contract)).split(/\r?\n/);download(`kuendigung-${String(contract.name||'vertrag').replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.pdf`,makeSimplePDF(lines),'application/pdf');contract.cancellation=contract.cancellation||{};contract.cancellation.pdfCreatedAt=new Date().toISOString();saveData('Kündigungs-PDF erstellt')}
  function emailCancellation(contract,text){const subject=encodeURIComponent(`Kündigung ${contract.name||'Vertrag'}`),body=encodeURIComponent(text||cancellationText(contract)),to=encodeURIComponent(contract.email||contract.providerEmail||'');location.href=`mailto:${to}?subject=${subject}&body=${body}`;contract.cancellation=contract.cancellation||{};contract.cancellation.emailOpenedAt=new Date().toISOString();saveData('Kündigungs-E-Mail vorbereitet')}
  async function attachEvidence(contract,file){const before=new Set((data.documents||[]).map(d=>d.id));await storeFile(file,`contract:${contract.id}:cancellation`);const doc=(data.documents||[]).find(d=>!before.has(d.id));contract.cancellation=contract.cancellation||{};contract.cancellation.evidenceDocIds=contract.cancellation.evidenceDocIds||[];if(doc)contract.cancellation.evidenceDocIds.push(doc.id);contract.cancellation.evidenceAt=new Date().toISOString();saveData('Kündigungsnachweis gespeichert');return doc}
  function openCancellationAssistant(contract){const p=sender(),text=cancellationText(contract);openModal('Kündigungsassistent',`PDF, E-Mail und Nachweis für ${escapeHTML(contract.name||'Vertrag')}.`,`<form id="cancelAssist"><div class="form-grid"><div class="field"><label>Name</label><input name="name" class="input" value="${escapeHTML(p.name||'')}"></div><div class="field"><label>E-Mail</label><input name="email" class="input" type="email" value="${escapeHTML(p.email||'')}"></div><div class="field full"><label>Anschrift</label><input name="address" class="input" value="${escapeHTML(p.address||'')}"></div><div class="field full"><label>Vertrags-/Kundennummer</label><input name="contractNo" class="input" value="${escapeHTML(contract.contractNo||contract.customerNo||'')}"></div><div class="field full"><label>Kündigungstext</label><textarea name="text" class="input" rows="13">${escapeHTML(text)}</textarea></div><div class="field full"><label>Versand-/Kündigungsnachweis</label><input id="cancelEvidence" type="file" class="input" accept="image/*,.pdf"></div></div><div class="modal-actions"><button type="button" id="cancelPdf" class="primary-button">PDF erstellen</button><button type="button" id="cancelMail" class="secondary-button">E-Mail vorbereiten</button><button type="button" id="cancelMark" class="secondary-button">Als versendet markieren</button><button type="button" class="secondary-button" data-cancel>Schließen</button></div></form>`,()=>{const f=$('#cancelAssist'),refresh=()=>{const fd=new FormData(f);Object.assign(sender(),{name:String(fd.get('name')||''),address:String(fd.get('address')||''),email:String(fd.get('email')||'')});return String(fd.get('text')||'')};$('#cancelPdf').onclick=()=>exportCancellationPDF(contract,refresh());$('#cancelMail').onclick=()=>emailCancellation(contract,refresh());$('#cancelMark').onclick=()=>{contract.cancellation={...(contract.cancellation||{}),sentAt:new Date().toISOString(),status:'sent'};saveData('Kündigung als versendet markiert');toast('Kündigung dokumentiert','success')};$('#cancelEvidence').onchange=async e=>{if(e.target.files?.[0]){await attachEvidence(contract,e.target.files[0]);toast('Nachweis gespeichert','success')}};$('[data-cancel]').onclick=closeModal})}
  const baseRenderContracts=window.renderContracts;window.renderContracts=function(){baseRenderContracts();const root=$('#view-contracts');if(!root||$('#v32ContractAutomation',root))return;const cands=recurringCandidates().slice(0,6),active=(data.contracts||[]).filter(c=>c.active!==false).slice(0,8);root.insertAdjacentHTML('beforeend',`<article id="v32ContractAutomation" class="card" style="margin-top:16px"><div class="card-title-row"><div><h2>Automatische Vertragserkennung</h2><p>Wiederkehrende Abbuchungen werden aus deinen Buchungen erkannt und können mit einem Klick übernommen werden.</p></div><span class="tag green">V3.2</span></div>${cands.length?cands.map((c,i)=>`<div class="list-row"><div class="list-icon">◎</div><div><strong>${escapeHTML(c.merchant)}</strong><small>${c.occurrences} Abbuchungen · ${Math.round(c.confidence*100)} % Sicherheit · ${escapeHTML(c.frequency)}</small></div><div class="list-amount"><b>${money(c.amount)}</b><button class="mini-btn" data-v32-accept="${i}">Übernehmen</button></div></div>`).join(''):'<div class="empty">Aktuell keine neuen Vertragskandidaten.</div>'}<div class="card-title-row" style="margin-top:18px"><div><h3>Kündigungsassistent</h3><p>Schreiben, PDF, E-Mail und Nachweisverwaltung.</p></div></div>${active.length?active.map(c=>`<div class="list-row"><div class="list-icon">✎</div><div><strong>${escapeHTML(c.name)}</strong><small>${c.cancellation?.sentAt?'Kündigung dokumentiert':'Noch aktiv'}</small></div><button class="mini-btn" data-v32-cancel="${c.id}">Kündigen</button></div>`).join(''):'<div class="empty">Keine aktiven Verträge.</div>'}</article>`);$$('[data-v32-accept]',root).forEach(b=>b.onclick=()=>{acceptContractCandidate(cands[Number(b.dataset.v32Accept)]);renderContracts()});$$('[data-v32-cancel]',root).forEach(b=>b.onclick=()=>openCancellationAssistant(data.contracts.find(c=>c.id===b.dataset.v32Cancel))) };
  function postImport(){const changed=learnFromHistory();if(changed)saveData(`${changed} Händlerregel(n) automatisch gelernt`);return {learned:changed,candidates:recurringCandidates()}}
  window.FinanzIntelligence={canonicalMerchant,learnFromHistory,recurringCandidates,acceptContractCandidate,cancellationText,exportCancellationPDF,emailCancellation,attachEvidence,openCancellationAssistant,postImport};
  learnFromHistory();
})();
