'use strict';
(function(){
  const MAX=100;
  function state(){data.settings=data.settings||{};return data.settings.monitoring=data.settings.monitoring||{enabled:true,cloudErrors:true,events:[]}}
  function clean(v){return String(v||'').replace(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/g,'[email]').replace(/\b\d{5,}\b/g,'[number]').replace(/\b\d+[.,]\d{2}\s?(€|EUR)?/gi,'[amount]').slice(0,240)}
  async function send(evt){if(!state().cloudErrors||!navigator.onLine||!data.integrations?.cloud?.householdId)return;try{const s=await FinanzCloud?.getSession?.();if(!s?.access_token)return;await FinanzCloud.api('/rest/v1/client_events',{method:'POST',body:{household_id:data.integrations.cloud.householdId,kind:evt.kind,level:evt.level,code:evt.code,message:evt.message,details:evt.details||{}},prefer:'return=minimal'})}catch(_){}}
  function record(kind,level='error',code='app_error',message='',details={}){if(!state().enabled)return null;const evt={id:`evt:${Date.now()}:${Math.random().toString(36).slice(2,7)}`,kind:String(kind||'app'),level:String(level||'error'),code:clean(code),message:clean(message),details:Object.fromEntries(Object.entries(details||{}).slice(0,10).map(([k,v])=>[clean(k),clean(v)])),at:new Date().toISOString()};state().events.unshift(evt);state().events=state().events.slice(0,MAX);send(evt);return evt}
  const baseCloud=FinanzCloud?.fullSync?.bind(FinanzCloud);if(baseCloud)FinanzCloud.fullSync=async function(...args){const t=performance.now();try{const r=await baseCloud(...args);record('cloud','info','sync_ok','Cloud-Synchronisierung erfolgreich',{ms:Math.round(performance.now()-t)});return r}catch(e){record('cloud','error','sync_failed',e.message);throw e}};
  const baseN26=FinanzN26?.sync?.bind(FinanzN26);if(baseN26)FinanzN26.sync=async function(...args){const t=performance.now();try{const r=await baseN26(...args);record('banking','info','n26_sync_ok','N26-Synchronisierung erfolgreich',{ms:Math.round(performance.now()-t),added:r?.added||0});FinanzIntelligence?.postImport?.();return r}catch(e){record('banking','error','n26_sync_failed',e.message);throw e}};
  window.addEventListener('error',e=>record('runtime','error','window_error',e.message,{file:(e.filename||'').split('/').pop(),line:e.lineno||0}));
  window.addEventListener('unhandledrejection',e=>record('runtime','error','unhandled_rejection',e.reason?.message||e.reason||'Promise rejected'));
  function summary(){const ev=state().events||[],day=Date.now()-86400000;return {total:ev.length,last24h:ev.filter(e=>new Date(e.at).getTime()>=day).length,errors24h:ev.filter(e=>e.level==='error'&&new Date(e.at).getTime()>=day).length,last:ev[0]||null}}
  function open(){const s=summary(),rows=(state().events||[]).slice(0,25);openModal('Betriebsmonitoring','Technische Fehlercodes ohne Buchungsbeträge oder Transaktionstexte.',`<div class="three"><div class="kpi-small"><small>Ereignisse</small><strong>${s.total}</strong></div><div class="kpi-small"><small>Letzte 24 h</small><strong>${s.last24h}</strong></div><div class="kpi-small"><small>Fehler 24 h</small><strong>${s.errors24h}</strong></div></div><div style="margin-top:16px">${rows.length?rows.map(e=>`<div class="list-row"><div class="list-icon">${e.level==='error'?'!':'i'}</div><div><strong>${escapeHTML(e.code)}</strong><small>${escapeHTML(e.message)} · ${new Date(e.at).toLocaleString('de-DE')}</small></div><span class="tag ${e.level==='error'?'amber':'green'}">${escapeHTML(e.kind)}</span></div>`).join(''):'<div class="empty">Keine technischen Ereignisse.</div>'}</div><div class="modal-actions"><button id="clearMonitor" class="secondary-button">Lokales Protokoll leeren</button><button class="secondary-button" data-cancel>Schließen</button></div>`,()=>{$('#clearMonitor').onclick=()=>{state().events=[];saveData('Monitoring-Protokoll geleert');open()};$('[data-cancel]').onclick=closeModal})}
  window.FinanzMonitoring={state,record,summary,open,clean};
})();
