'use strict';
(function(){
  function roadmap(){return [
    {n:1,title:'N26 Live-Banking',state:data.integrations?.n26?.sessionReady?'complete':'external',detail:data.integrations?.n26?.sessionReady?'N26 ist verbunden.':'Bridge fertig; persönlicher Enable-Banking-Zugang + Consent fehlen noch.'},
    {n:2,title:'Händler & Kategorien',state:'complete',detail:'Händlernormalisierung und lernende Kategorisierung aktiv.'},
    {n:3,title:'Vertragserkennung',state:'complete',detail:'Wiederkehrende Abbuchungen werden als Vertragskandidaten erkannt.'},
    {n:4,title:'Kündigungsassistent',state:'complete',detail:'PDF, E-Mail-Vorbereitung und Nachweisverwaltung vorhanden.'},
    {n:5,title:'KI-Finanzassistent',state:data.integrations?.ai?.mode==='cloud'?'complete':'partial',detail:data.integrations?.ai?.mode==='cloud'?'Cloud-KI aktiviert.':'Lokale KI vollständig nutzbar; Cloud-KI optionaler externer Zugang.'},
    {n:6,title:'Cloud-E2EE',state:FinanzE2EE?.cfg?.().enabled?'complete':'ready',detail:FinanzE2EE?.cfg?.().enabled?'Client-seitige E2EE aktiviert.':'Technisch fertig, bewusst noch nicht aktiviert.'},
    {n:7,title:'Produktionsmonitoring',state:'complete',detail:'Sanitisierte technische Fehler-/Sync-Überwachung mit RLS.'},
    {n:8,title:'UX & Onboarding',state:'complete',detail:'Zentrales Setup für Banking, E2EE, Push, KI und Monitoring.'},
    {n:9,title:'Audit-Härtung',state:'partial',detail:'Automatisierte Security/WCAG/Browser-Tests vorhanden; externer Penetrationstest bleibt extern.'},
    {n:10,title:'Weitere Banken & Native',state:'ready',detail:'Providerneutraler Banking-Hub und Native-Wrapper-Vorbereitung; weitere reale Banken erst mit Providerzugang.'}
  ]}
  function aiMode(){const c=FinanzAI.aiCfg(),next=c.mode==='local'?'device':c.mode==='device'?'cloud':'local';c.mode=next;saveData(`KI-Modus: ${next}`);return next}
  function openCenter(){const rows=roadmap();openModal('V3.2 Automation & Intelligence','Ein zentraler Status für die zehn Ausbaupunkte.',`<div class="v32-roadmap">${rows.map(x=>`<div class="list-row"><div class="list-icon">${x.n}</div><div><strong>${escapeHTML(x.title)}</strong><small>${escapeHTML(x.detail)}</small></div><span class="tag ${x.state==='complete'?'green':x.state==='external'?'amber':''}">${x.state==='complete'?'fertig':x.state==='external'?'extern':x.state==='partial'?'teilweise':'bereit'}</span></div>`).join('')}</div><div class="action-row" style="margin-top:16px"><button id="v32Bank" class="primary-button">Banking</button><button id="v32E2EE" class="secondary-button">Cloud-E2EE</button><button id="v32Monitor" class="secondary-button">Monitoring</button><button id="v32AI" class="secondary-button">KI-Modus: ${escapeHTML(FinanzAI.aiCfg().mode||'local')}</button></div><div class="modal-actions"><button class="secondary-button" data-cancel>Schließen</button></div>`,()=>{$('#v32Bank').onclick=()=>FinanzBankingHub.open().catch(e=>toast(e.message,'error'));$('#v32E2EE').onclick=()=>FinanzE2EE.openSetup();$('#v32Monitor').onclick=()=>FinanzMonitoring.open();$('#v32AI').onclick=()=>{const m=aiMode();toast(`KI-Modus: ${m}`,'success');openCenter()};$('[data-cancel]').onclick=closeModal})}
  const baseSettings=window.renderSettings;window.renderSettings=function(){baseSettings();const root=$('#view-settings');if(!root||$('#v32SetupCard',root))return;const r=roadmap(),done=r.filter(x=>x.state==='complete').length;root.insertAdjacentHTML('beforeend',`<article id="v32SetupCard" class="card" style="margin-top:16px"><div class="card-title-row"><div><h2>V3.2 Automation & Intelligence</h2><p>${done}/10 Ausbaupunkte vollständig aktiv; externe Provider werden getrennt ausgewiesen.</p></div><span class="tag green">V3.2</span></div><div class="three"><div class="kpi-small"><small>Händlerlernen</small><strong>Aktiv</strong></div><div class="kpi-small"><small>Vertragserkennung</small><strong>${FinanzIntelligence.recurringCandidates().length} Kandidaten</strong></div><div class="kpi-small"><small>Monitoring</small><strong>${FinanzMonitoring.summary().errors24h} Fehler/24 h</strong></div></div><div class="action-row" style="margin-top:14px"><button id="openV32Center" class="primary-button">Einrichtungscenter öffnen</button><button id="openV32E2EE" class="secondary-button">E2EE</button><button id="openV32Bank" class="secondary-button">Banking</button></div></article>`);$('#openV32Center',root).onclick=openCenter;$('#openV32E2EE',root).onclick=()=>FinanzE2EE.openSetup();$('#openV32Bank',root).onclick=()=>FinanzBankingHub.open().catch(e=>toast(e.message,'error'))};
  window.FinanzV32Onboarding={roadmap,openCenter,aiMode};
})();
