'use strict';
(function(){
  function conf(){data.integrations=data.integrations||{};const s=data.integrations.sparkasse=data.integrations.sparkasse||{};s.backendUrl=s.backendUrl||data.integrations.backendUrl||data.integrations.n26?.backendUrl||'';return s}
  const req=(path,opts)=>FinanzN26.req(path,opts);
  async function session(){return FinanzCloud?.getSession?.()}
  function sourceKey(t){return !!t&&(t.source==='sparkasse'||(t.tags||[]).includes('sparkasse'))}
  function safeFallback(type){return globalThis.FinanzCategoryIntelligence?.fallbackCategory?.(type)||data.categories?.find(c=>c.id===(type==='income'?'c_income_other':'c_other'))?.id||''}
  async function status(){const hid=data.integrations?.cloud?.householdId||'';if(!hid)return {configured:true,ready:false};try{const j=await req(`/api/banking/connections?householdId=${encodeURIComponent(hid)}`),rows=j.connections||[],wanted=rows.find(x=>/sparkasse/i.test(String(x.bank||'')));if(wanted){conf().bankName=wanted.bank;conf().sessionReady=true;return {configured:true,ready:true,connection:wanted}}return {configured:true,ready:false}}catch(e){return {configured:false,ready:false,error:e.message}}}
  async function institutions(query='Sparkasse'){const j=await req(`/api/banking/institutions?query=${encodeURIComponent(query)}`);return j.institutions||[]}
  async function begin(aspspName=''){const s=await session(),householdId=data.integrations?.cloud?.householdId||'';if(!s?.access_token)throw new Error('Bitte zuerst bei Finanzplan anmelden');if(!householdId)throw new Error('Kein Cloud-Haushalt gewählt');const redirectUrl=`${location.origin}${location.pathname}`,body={redirectUrl,householdId,bankQuery:aspspName||'Sparkasse',aspspName,psuId:s.user?.id||'finanzplan-user'},j=await req('/api/banking/start',{method:'POST',body});if(j.needsSelection)return j;if(!j.url)throw new Error('Die Sparkassen-Anmeldung konnte nicht gestartet werden');sessionStorage.setItem('finanzplan:sparkasse:state',j.state||'');sessionStorage.setItem('finanzplan:sparkasse:bank',j.bank?.name||aspspName||'Sparkasse');location.href=j.url;return j}
  async function openConnect(){openModal('Sparkasse verbinden','Suche deine konkrete Sparkasse. Die Anmeldung und TAN-Freigabe erfolgen anschließend über die PSD2-Schnittstelle der Bank.',`<form id="sparkasseSearch"><div class="field"><label>Sparkasse</label><input name="q" class="input" value="${escapeHTML(conf().bankName||'Sparkasse')}" placeholder="z. B. Sparkasse Schaumburg" autocomplete="off"></div><div class="modal-actions"><button type="button" class="secondary-button" data-cancel>Abbrechen</button><button class="primary-button">Sparkasse suchen</button></div></form><div id="sparkasseResults" class="simple-list" style="margin-top:12px"></div>`,()=>{const f=$('#sparkasseSearch'),out=$('#sparkasseResults');f.onsubmit=async e=>{e.preventDefault();const q=String(new FormData(f).get('q')||'Sparkasse').trim();out.innerHTML='<div class="empty">Suche läuft …</div>';try{const rows=await institutions(q);if(!rows.length){out.innerHTML='<div class="empty">Keine passende Sparkasse gefunden. Probiere den vollständigen Banknamen.</div>';return}out.innerHTML=rows.map((x,i)=>`<div class="list-row"><div class="list-icon">S</div><div><strong>${escapeHTML(x.name)}</strong><small>${escapeHTML(x.bic||'Deutschland · PSD2')}</small></div><button class="mini-btn" data-spk-connect="${i}">Verbinden</button></div>`).join('');$$('[data-spk-connect]',out).forEach(b=>b.onclick=async()=>{try{const bank=rows[Number(b.dataset.spkConnect)];await begin(bank.name)}catch(err){toast(err.message,'error')}})}catch(err){out.innerHTML=`<div class="empty">${escapeHTML(err.message)}</div>`}};$('[data-cancel]').onclick=closeModal})}
  async function handleCallback(){const u=new URL(location.href),code=u.searchParams.get('code'),state=u.searchParams.get('state'),expected=sessionStorage.getItem('finanzplan:sparkasse:state');if(!code||!expected)return false;if(state&&expected!==state)throw new Error('Sparkassen-State stimmt nicht überein');const j=await req('/api/banking/exchange',{method:'POST',body:{code,state:state||expected}});const c=conf();c.sessionReady=true;c.accounts=j.accounts||[];c.bankName=j.bank||sessionStorage.getItem('finanzplan:sparkasse:bank')||'Sparkasse';c.lastAuthorizedAt=new Date().toISOString();sessionStorage.removeItem('finanzplan:sparkasse:state');sessionStorage.removeItem('finanzplan:sparkasse:bank');history.replaceState({},'',location.pathname);saveData(`${c.bankName} erfolgreich verbunden`);return true}
  function ensureLocalAccount(bankRows=[]){const c=conf(),selected=data.accounts?.find(a=>a.id===c.localAccountId);if(selected)return selected;if((data.accounts||[]).length===1&&!data.accounts[0].source){c.localAccountId=data.accounts[0].id;data.accounts[0].source='sparkasse';return data.accounts[0]}const dates=(bankRows||[]).map(t=>FinanceLib.normalizeDate(t.date)).filter(Boolean).sort(),first=dates[0]||localISO(new Date());let d=FinanceLib.parseISO(first)||new Date();d.setDate(d.getDate()-1);const account={id:uid('acc'),name:`${c.bankName||'Sparkasse'} Girokonto`,type:'checking',openingBalance:0,openingDate:localISO(d),includeNetWorth:true,spendable:true,source:'sparkasse'};data.accounts.push(account);c.localAccountId=account.id;return account}
  function txFromBank(t){const c=conf(),amount=Math.abs(num(t.amount)),type=t.direction==='credit'?'income':'expense',accountId=c.localAccountId||data.accounts?.[0]?.id||'',title=t.merchant||t.title||t.remittance||t.bankCodeDescription||`${c.bankName||'Sparkasse'} Umsatz`,note=t.remittance||t.reference||'',mcc=globalThis.FinanzCategoryIntelligence?.normalizeMcc?.(t.mcc)||String(t.mcc||''),bankCode=String(t.bankCode||''),bankSubCode=String(t.bankSubCode||''),bankCodeDescription=String(t.bankCodeDescription||'');const smart=globalThis.FinanzCategoryIntelligence?.categorizeTransaction?.({title,merchant:t.merchant,note,remittance:t.remittance,reference:t.reference,type,mcc,bankCode,bankSubCode,bankCodeDescription})||null,draft=applyMerchantRule(title,{categoryId:smart?.categoryId||safeFallback(type),accountId,type,merchant:t.merchant||'',note,remittance:t.remittance||'',reference:t.reference||'',mcc,bankCode,bankSubCode,bankCodeDescription}),merchant=draft.merchant||smart?.merchant||globalThis.FinanzIntelligence?.canonicalMerchant?.(t.merchant||title)||t.merchant||'',categoryId=data.categories.find(x=>x.id===draft.categoryId)?.id||safeFallback(type),tx={id:uid('tx'),date:FinanceLib.normalizeDate(t.date)||localISO(new Date()),title,merchant,sourceMerchant:t.merchant||'',amount,type,categoryId,accountId:draft.accountId||accountId,memberId:data.members?.[0]?.id||'',status:'paid',note,tags:['bank','sparkasse'],source:'sparkasse',bankName:c.bankName||'Sparkasse',externalId:t.id||t.reference||'',bankReference:t.reference||'',mcc,bankCode,bankSubCode,bankCodeDescription,categorySource:draft.categorySource||smart?.source||'fallback',categoryConfidence:Number(draft.categoryConfidence??smart?.confidence??0),categoryReason:draft.categoryReason||smart?.reason||''};tx.fingerprint=transactionFingerprint(tx);return tx}
  function identity(t){const raw=t?.sourceMerchant||t?.merchant||t?.title||'';return FinanceLib.normalizeText(globalThis.FinanzCategoryIntelligence?.merchantAlias?.(raw)||globalThis.FinanzIntelligence?.canonicalMerchant?.(raw)||raw)}
  function signature(t){return [FinanceLib.normalizeDate(t?.date)||'',Math.round(Math.abs(num(t?.amount))*100),t?.type||(t?.direction==='credit'?'income':'expense'),identity(t),t?.accountId||conf().localAccountId||''].join('|')}
  function enrich(existing,fresh){let changed=false;for(const k of ['mcc','sourceMerchant','bankReference','bankCode','bankSubCode','bankCodeDescription','bankName'])if(fresh[k]&&existing[k]!==fresh[k]){existing[k]=fresh[k];changed=true}if(!existing.note&&fresh.note){existing.note=fresh.note;changed=true}if(existing.categorySource!=='manual'&&existing.categoryLocked!==true){const smart=globalThis.FinanzCategoryIntelligence?.categorizeTransaction?.({title:existing.title||fresh.title,merchant:existing.sourceMerchant||fresh.sourceMerchant||existing.merchant,note:existing.note||fresh.note,remittance:existing.note||fresh.note,reference:existing.bankReference||fresh.bankReference||existing.externalId||fresh.externalId,type:existing.type||fresh.type,mcc:existing.mcc||fresh.mcc,bankCode:existing.bankCode||fresh.bankCode,bankSubCode:existing.bankSubCode||fresh.bankSubCode,bankCodeDescription:existing.bankCodeDescription||fresh.bankCodeDescription});if(smart?.categoryId&&(existing.categoryId!==smart.categoryId||existing.merchant!==smart.merchant||existing.categorySource!==smart.source)){existing.categoryId=smart.categoryId;existing.merchant=smart.merchant||existing.merchant;existing.categorySource=smart.source;existing.categoryConfidence=smart.confidence;existing.categoryReason=smart.reason;changed=true}}const fp=transactionFingerprint(existing);if(existing.fingerprint!==fp){existing.fingerprint=fp;changed=true}return changed}
  function mergeRows(rows=[]){const local=(data.transactions||[]).filter(sourceKey);let added=0,enriched=0;for(const tx of rows){let existing=tx.externalId?local.find(x=>x.externalId===tx.externalId):null;if(!existing)existing=local.find(x=>signature(x)===signature(tx));if(existing){if(enrich(existing,tx))enriched++;continue}const manualDup=(data.transactions||[]).find(x=>!sourceKey(x)&&transactionFingerprint(x)===tx.fingerprint);if(manualDup)continue;data.transactions.push(tx);local.push(tx);added++}return {added,enriched}}
  async function sync({days=180,reconcile=true}={}){const c=conf(),householdId=data.integrations?.cloud?.householdId||'';if(!householdId)throw new Error('Kein Cloud-Haushalt gewählt');if(!c.bankName){const st=await status();if(!st.ready)throw new Error('Sparkasse ist noch nicht verbunden')}const qs=new URLSearchParams({days:String(Math.max(1,Math.min(730,days))),householdId,bank:c.bankName}),j=await req(`/api/banking/sync?${qs}`),bankRows=j.transactions||[];c.bankName=j.bank||c.bankName||'Sparkasse';ensureLocalAccount(bankRows);const rows=bankRows.map(txFromBank),merged=mergeRows(rows),recategorized=globalThis.FinanzCategoryIntelligence?.reclassifyImportedTransactions?.({onlySuspicious:false})||0;if(reconcile&&Number.isFinite(Number(j.balance))&&typeof reconcileAccount==='function')try{reconcileAccount(c.localAccountId,Number(j.balance),localISO(new Date()),`${c.bankName} PSD2-Abgleich`,false)}catch(e){console.warn(e)}c.lastSync=new Date().toISOString();c.lastBalance=j.balance;c.sessionReady=true;detectSubscriptionSuggestions?.();saveData(`${c.bankName}: ${merged.added} neu, ${merged.enriched} aktualisiert, ${recategorized} neu kategorisiert`);return {...merged,recategorized,total:rows.length,balance:j.balance,bank:c.bankName}}
  window.FinanzSparkasse={conf,status,institutions,begin,openConnect,handleCallback,sync,txFromBank,ensureLocalAccount,sourceKey,version:'1.0.0'};
})();
