/* SYNDIKAT_V54_VISUAL_EXPANSION_BEGIN */
(function SYNDIKAT_V54_VISUAL_EXPANSION(){
  const STORY={"1":"./assets/story-01.svg","2":"./assets/story-02.svg","3":"./assets/story-03.svg","4":"./assets/story-04.svg","5":"./assets/story-05.svg","6":"./assets/story-06.svg","7":"./assets/story-07.svg","8":"./assets/story-08.svg","9":"./assets/story-09.svg","10":"./assets/story-10.svg","11":"./assets/story-11.svg","12":"./assets/story-12.svg","13":"./assets/story-13.svg","14":"./assets/story-14.svg","15":"./assets/story-15.svg","16":"./assets/story-16.svg","17":"./assets/story-17.svg","18":"./assets/story-18.svg","19":"./assets/story-19.svg","20":"./assets/story-20.svg"};
  const EVENTS={"blackout":"./assets/event-blackout.svg","tourism":"./assets/event-tourism.svg","scandal":"./assets/event-scandal.svg","dockstrike":"./assets/event-dockstrike.svg"};
  const CRIME_ART={"machine":"./assets/crime-machine.svg","mug":"./assets/crime-mug.svg","car":"./assets/crime-car.svg","bar":"./assets/crime-bar.svg","bank":"./assets/crime-bank.svg"};
  const DIPLOMACY={"tribute":"./assets/diplomacy-tribute.svg","venture":"./assets/diplomacy-venture.svg","swap":"./assets/diplomacy-swap.svg","betray":"./assets/diplomacy-betray.svg"};
  const ENDGAME={"legit":"./assets/endgame-legit.svg","politics":"./assets/endgame-politics.svg","war":"./assets/endgame-war.svg"};
  const PRISON={"appeal":"./assets/prison-appeal.svg","guardbribe":"./assets/prison-bribe.svg","network":"./assets/prison-network.svg","contraband":"./assets/prison-contraband.svg","tunnel":"./assets/prison-tunnel.svg","delegate":"./assets/prison-delegate.svg","escape":"./assets/prison-escape.svg"};
  const COURT={"fight":"./assets/court-fight.svg","deal":"./assets/court-deal.svg","corrupt":"./assets/court-corrupt.svg"};
  const SPECIALIZATION={"lowprofile":"./assets/spec-lowprofile.svg","highroller":"./assets/spec-highroller.svg","discreet":"./assets/spec-discreet.svg","premium":"./assets/spec-premium.svg","lounge":"./assets/spec-lounge.svg","speakeasy":"./assets/spec-speakeasy.svg","sportsbook":"./assets/spec-sportsbook.svg","bookmaking":"./assets/spec-bookmaking.svg","family":"./assets/spec-family.svg","night":"./assets/spec-night.svg","vip":"./assets/spec-vip.svg","backroom":"./assets/spec-backroom.svg","elite":"./assets/spec-elite.svg","discretion":"./assets/spec-discretion.svg","resort":"./assets/spec-resort.svg","highstakes":"./assets/spec-highstakes.svg","luxuryhotel":"./assets/spec-luxuryhotel.svg","conference":"./assets/spec-conference.svg","legit":"./assets/spec-legit.svg","shells":"./assets/spec-shells.svg"};
  const PROTECTION={"Kiosk":"./assets/protection-kiosk.svg","Friseursalon":"./assets/protection-friseursalon.svg","Späti":"./assets/protection-spati.svg","Taxi-Zentrale":"./assets/protection-taxi-zentrale.svg","Werkstatt":"./assets/protection-werkstatt.svg","Pfandleihe":"./assets/protection-pfandleihe.svg","Gemüsehändler":"./assets/protection-gemusehandler.svg","Nachtcafé":"./assets/protection-nachtcafe.svg","Lagerbetrieb":"./assets/protection-lagerbetrieb.svg","Billardsalon":"./assets/protection-billardsalon.svg","Schneiderei":"./assets/protection-schneiderei.svg","Tabakladen":"./assets/protection-tabakladen.svg"};
  const ACHIEVEMENT={"Erstes Standbein":"./assets/achievement-first_biz.svg","Die Familie":"./assets/achievement-crew.svg","Millionär":"./assets/achievement-million.svg","Großkapital":"./assets/achievement-ten_million.svg","Unser Viertel":"./assets/achievement-district.svg","Stadtmacht":"./assets/achievement-three_districts.svg","Saubere Arbeit":"./assets/achievement-operations.svg","Unantastbar":"./assets/achievement-untouchable.svg","Rechte Hand":"./assets/achievement-underboss.svg","Das Syndikat":"./assets/achievement-syndicate.svg"};
  const PERSON={"Alessio Marchetti":"./assets/person-alessio-marchetti.svg","Bianca Serra":"./assets/person-bianca-serra.svg","Matteo Ricci":"./assets/person-matteo-ricci.svg","Clara Venturi":"./assets/person-clara-venturi.svg","Paolo Gallo":"./assets/person-paolo-gallo.svg","Francesca Neri":"./assets/person-francesca-neri.svg","Stefano Riva":"./assets/person-stefano-riva.svg","Lucia Ferraro":"./assets/person-lucia-ferraro.svg","Bruno Amato":"./assets/person-bruno-amato.svg","Rosa Mancini":"./assets/person-rosa-mancini.svg","Gabriel Esposito":"./assets/person-gabriel-esposito.svg","Nina Lombardi":"./assets/person-nina-lombardi.svg","Tomaso Greco":"./assets/person-tomaso-greco.svg","Adriana Vitale":"./assets/person-adriana-vitale.svg","Renato Leone":"./assets/person-renato-leone.svg","Camilla De Santis":"./assets/person-camilla-de-santis.svg","Emilio Caruso":"./assets/person-emilio-caruso.svg","Vera Romano":"./assets/person-vera-romano.svg","Silvio Morelli":"./assets/person-silvio-morelli.svg","Anita Bianchi":"./assets/person-anita-bianchi.svg","Massimo Fontana":"./assets/person-massimo-fontana.svg","Greta Costa":"./assets/person-greta-costa.svg","Dante Rizzo":"./assets/person-dante-rizzo.svg","Lea Conti":"./assets/person-lea-conti.svg"};
  const ENDINGS={"empire":"./assets/ending-empire.svg","shadow":"./assets/ending-shadow.svg","crown":"./assets/ending-crown.svg","family":"./assets/ending-family.svg"};
  const EXTRA_NAMES=["Alessio Marchetti","Bianca Serra","Matteo Ricci","Clara Venturi","Paolo Gallo","Francesca Neri","Stefano Riva","Lucia Ferraro","Bruno Amato","Rosa Mancini","Gabriel Esposito","Nina Lombardi","Tomaso Greco","Adriana Vitale","Renato Leone","Camilla De Santis","Emilio Caruso","Vera Romano","Silvio Morelli","Anita Bianchi","Massimo Fontana","Greta Costa","Dante Rizzo","Lea Conti"];
  if(typeof STAFF_NAMES!=='undefined'){for(const n of EXTRA_NAMES)if(!STAFF_NAMES.includes(n))STAFF_NAMES.push(n);}
  const story=window.SyndikatVisualStory&&window.SyndikatVisualStory.story;
  if(story)for(const ch of story){const src=STORY[String(ch.chapter)];if(src)ch.image=src;}
  const style=document.createElement('style');
  style.textContent='.vx-thumb{width:112px;height:78px;object-fit:cover;border-radius:10px;border:1px solid rgba(213,179,107,.35);flex:0 0 auto;margin-right:.8rem}.crime-card>.vx-thumb{width:100%;height:118px;margin:0 0 .75rem 0}.achievement>.vx-ach{width:100%;aspect-ratio:16/9;object-fit:cover;border-radius:10px;margin-bottom:.6rem;filter:saturate(.9)}.achievement.locked>.vx-ach{filter:grayscale(1) brightness(.55)}.vx-wide{width:100%;max-height:210px;object-fit:cover;border-radius:12px;margin-bottom:.85rem;border:1px solid rgba(213,179,107,.28)}.dialog-option{align-items:center}.v44-site-panel>.vx-wide{border-radius:0;margin:0 0 .75rem 0}';
  document.head.appendChild(style);
  function putImg(host,src,cls){if(!host||!src)return null;cls=cls||'vx-thumb';let img=host.querySelector('img.'+cls);if(!img){img=document.createElement('img');img.className=cls;img.alt='';host.insertBefore(img,host.firstChild);}if(img.getAttribute('src')!==src)img.src=src;return img;}
  function current(){try{return typeof currentPlayer==='function'?currentPlayer():null}catch(_){return null}}
  function decorate(){
    document.querySelectorAll('#crimeGrid .crime-thumb').forEach(img=>img.remove());
    const p=current();
    if(p){const ev=p.deepEvent||(typeof state!=='undefined'&&state&&state.cityEvent);const eventImg=document.querySelector('.deep-event-card img');if(ev&&eventImg&&EVENTS[ev.id])eventImg.src=EVENTS[ev.id];}
    document.querySelectorAll('#crimeGrid .crime-card').forEach(function(card,i){const prisonBtn=card.querySelector('[data-prison-final]');if(prisonBtn){putImg(card,PRISON[prisonBtn.dataset.prisonFinal],'vx-thumb');return;}const c=(typeof CRIMES!=='undefined'&&CRIMES[i])?CRIMES[i]:null;if(c&&CRIME_ART[c.id])putImg(card,CRIME_ART[c.id],'vx-thumb');});
    document.querySelectorAll('[data-dd]').forEach(function(btn){putImg(btn.closest('.dialog-option'),DIPLOMACY[btn.dataset.dd]);});
    document.querySelectorAll('[data-final-choice]').forEach(function(btn){putImg(btn.closest('.dialog-option'),ENDGAME[btn.dataset.finalChoice]);});
    document.querySelectorAll('[data-court]').forEach(function(btn){putImg(btn.closest('.dialog-option'),COURT[btn.dataset.court]);});
    document.querySelectorAll('[data-path]').forEach(function(btn){putImg(btn.closest('.dialog-option'),SPECIALIZATION[btn.dataset.path]);});
    document.querySelectorAll('[data-pressure]').forEach(function(btn){if(!p)return;const c=(p.protectionContracts||[]).find(function(x){return x.id===btn.dataset.pressure});if(!c)return;const key=Object.keys(PROTECTION).find(function(k){return String(c.name||'').startsWith(k)});if(key)putImg(btn.closest('.dialog-option'),PROTECTION[key]);});
    document.querySelectorAll('.achievement-grid .achievement').forEach(function(card){const txt=(card.querySelector('strong')&&card.querySelector('strong').textContent)||'';const key=Object.keys(ACHIEVEMENT).find(function(k){return txt.includes(k)});if(key)putImg(card,ACHIEVEMENT[key],'vx-ach');});
    const prisonHero=document.querySelector('.prison-visual img');if(prisonHero)prisonHero.src='./assets/prison-cell.svg';
    const root=document.querySelector('#dialogContent .dialog-wrap');
    if(root){const heading=(root.querySelector('h2')&&root.querySelector('h2').textContent)||'';const banner=root.querySelector('.dialog-visual-banner img');if(banner&&heading.includes('Gerichtsakte'))banner.src='./assets/court-hearing.svg';if(banner&&p&&p.finalCrisis&&(heading.includes('Endgame')||heading.includes('Stadt schlägt zurück')||heading.includes('Stadt reagiert'))){const src=ENDGAME[p.finalCrisis.choice];if(src)banner.src=src;}if(heading.includes('Gerichtsakte')){root.querySelectorAll('.dialog-list .dialog-option').forEach(function(row){if(!row.querySelector('[data-court]'))putImg(row,'./assets/court-archive.svg');});}}
  }
  const previousRenderStaff=renderStaff;
  renderStaff=function(){previousRenderStaff();const p=current();if(p){document.querySelectorAll('#staffGrid [data-staff-person]').forEach(function(btn){const person=(p.staffRoster||[]).find(function(x){return x.id===btn.dataset.staffPerson});if(!person||!PERSON[person.name])return;const card=btn.closest('.person-card');if(!card)return;const img=card.querySelector('.person-portrait');if(img)img.src=PERSON[person.name];});}decorate();};
  const previousOpenStaffPerson=openStaffPerson;
  openStaffPerson=function(id){previousOpenStaffPerson(id);const p=current();const person=p&&(p.staffRoster||[]).find(function(x){return x.id===id});if(person&&PERSON[person.name]){const root=document.querySelector('#dialogContent .dialog-wrap');const img=root&&root.querySelector('.dialog-person-hero');if(img)img.src=PERSON[person.name];}decorate();};
  const previousBusinessDialog=openBusinessDialog;
  openBusinessDialog=function(id){previousBusinessDialog(id);const p=current();const b=p&&(p.businesses||[]).find(function(x){return x.id===id});if(b&&b.specialization&&SPECIALIZATION[b.specialization]){const panel=document.querySelector('#dialogContent .v44-site-panel');if(panel)putImg(panel,SPECIALIZATION[b.specialization],'vx-wide');}decorate();};
  const previousGameOver=showGameOver;
  showGameOver=function(){previousGameOver();const p=(typeof state!=='undefined'&&state&&state.players)?state.players.find(function(x){return x.id===state.winnerId}):null;if(!p)return;const key=(p.story&&p.story.flags&&p.story.flags.ending)||(p.finalCrisis&&p.finalCrisis.choice==='legit'?'empire':p.finalCrisis&&p.finalCrisis.choice==='politics'?'shadow':p.finalCrisis&&p.finalCrisis.choice==='war'?'crown':'family');const img=document.querySelector('#dialogContent .ending-card img');if(img&&ENDINGS[key])img.src=ENDINGS[key];decorate();};
  let scheduled=false;const observer=new MutationObserver(function(){if(scheduled)return;scheduled=true;queueMicrotask(function(){scheduled=false;decorate();});});
  if(document.body)observer.observe(document.body,{childList:true,subtree:true});else document.addEventListener('DOMContentLoaded',function(){observer.observe(document.body,{childList:true,subtree:true});decorate();},{once:true});
  setTimeout(decorate,0);
  window.SyndikatVisualExpansion={story:STORY,events:EVENTS,crimes:CRIME_ART,diplomacy:DIPLOMACY,endgame:ENDGAME,prison:PRISON,court:COURT,specializations:SPECIALIZATION,protection:PROTECTION,achievements:ACHIEVEMENT,people:PERSON,endings:ENDINGS};
})();
/* SYNDIKAT_V54_VISUAL_EXPANSION_END */
