'use strict';

function esc(value) {
  return String(value ?? '').replace(/[&<>"']/gu, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
}

function shell({ title, content, config, warning = '' }) {
  const email = config.contactEmail ? `<a href="mailto:${esc(config.contactEmail)}">${esc(config.contactEmail)}</a>` : '<strong>Noch nicht konfiguriert – LEGAL_CONTACT_EMAIL bei Render ergänzen.</strong>';
  return `<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#070914"><title>${esc(title)} – QuizTime</title><link rel="icon" href="/icons/ahnsen-quiz.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/app.css"><link rel="stylesheet" href="/legal.css"></head><body class="app-body legal-body"><main class="legal-shell" id="mainContent"><header class="legal-header"><a class="app-brand" href="/"><div class="app-logo">Q</div><div class="app-brand-copy"><strong>QuizTime</strong><span>Rechtliches & Datenschutz</span></div></a><a class="btn ghost small" href="/">← Startseite</a></header>${warning ? `<div class="legal-warning">${esc(warning)}</div>` : ''}<section class="legal-hero"><span class="app-kicker">Stand ${esc(config.privacyVersion)}</span><h1>${esc(title)}</h1><p>Verantwortlicher: ${esc(config.operator.name)}, ${esc(config.operator.street)}, ${esc(config.operator.postalCode)} ${esc(config.operator.city)} · ${email}</p></section><nav class="legal-nav"><a href="/legal#impressum">Impressum</a><a href="/legal#datenschutz">Datenschutz</a><a href="/legal#nutzung">Nutzungsbedingungen</a><a href="/legal#kinder">Kinder & Eltern</a><a href="/account">Daten verwalten</a></nav>${content}<footer class="legal-footer"><a href="/">QuizTime</a><a href="/account">Kontocenter</a><a href="/legal#datenschutz">Datenschutz</a><span>Version ${esc(config.appVersion)}</span></footer></main><script src="/app.js"></script></body></html>`;
}

function legalDocument(config) {
  const contact = config.contactEmail ? esc(config.contactEmail) : 'LEGAL_CONTACT_EMAIL muss noch eingerichtet werden';
  const warning = config.contactConfigured ? '' : 'Die Anschrift ist eingetragen. Für ein vollständiges Impressum fehlt noch eine öffentlich erreichbare Kontakt-E-Mail.';
  const content = `<section id="impressum" class="legal-card"><span class="eyebrow">Anbieterkennzeichnung</span><h2>Impressum</h2><h3>Angaben zum Diensteanbieter</h3><p>${esc(config.operator.name)}<br>${esc(config.operator.street)}<br>${esc(config.operator.postalCode)} ${esc(config.operator.city)}<br>${esc(config.operator.country)}</p><h3>Kontakt</h3><p>E-Mail: ${contact}</p><p>QuizTime wird als digitaler Quizdienst betrieben. Weitere Register-, Steuer- oder Aufsichtsangaben werden ergänzt, soweit sie für die tatsächliche Rechts- oder Unternehmensform erforderlich sind.</p></section>
<section id="datenschutz" class="legal-card"><span class="eyebrow">Informationen zum Datenschutz</span><h2>Datenschutzerklärung</h2><h3>1. Verantwortlicher</h3><p>${esc(config.operator.name)}, ${esc(config.operator.street)}, ${esc(config.operator.postalCode)} ${esc(config.operator.city)}. Kontakt: ${contact}.</p><h3>2. Verarbeitete Daten</h3><p>QuizTime verarbeitet insbesondere Profilname, E-Mail-Adresse, Passwort-Hash, Kontostatus, Spielstände, Antworten, Punkte, Ligen, Freundschaften, Einladungen, Turnier- und Eventteilnahmen, technische Sicherheitsereignisse sowie freiwillige Einstellungen. Passwörter werden nicht im Klartext gespeichert.</p><h3>3. Zwecke</h3><p>Die Daten werden für Konten, Spielmodi, Wiederverbindung, Missbrauchsprävention, Moderation, gewünschte Benachrichtigungen und technische Fehleranalyse verwendet.</p><h3>4. Dienstleister</h3><p>Je nach Konfiguration können Hosting- und Datenbankanbieter, Brevo oder Resend, ElevenLabs für angeforderte Sprachausgabe sowie GitHub Actions für automatisierte Tests eingesetzt werden.</p><h3>5. Speicherung und Rechte</h3><p>Kontodaten werden grundsätzlich bis zur Löschung des Profils gespeichert, soweit keine gesetzlichen oder begrenzten Sicherheitsgründe entgegenstehen. Betroffene Personen können insbesondere Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit und Widerspruch verlangen. Export und Profil-Löschung stehen im Kontocenter bereit.</p><h3>6. Cookies und lokale Speicherung</h3><p>QuizTime verwendet technisch notwendige Sitzungs-Cookies und lokale Speicherfunktionen für Anmeldung, PWA-Betrieb, Wiederverbindung und gewünschte Einstellungen. Werbe- oder Tracking-Cookies werden in Version 13 nicht eingesetzt.</p></section>
<section id="nutzung" class="legal-card"><span class="eyebrow">Regeln für die Nutzung</span><h2>Nutzungsbedingungen</h2><p>Diese Bedingungen gelten für Solo-, Mehrspieler-, Community-, Liga-, Turnier- und Eventfunktionen. Zugangsdaten sind vertraulich zu behandeln. Mehrfachkonten, automatisierte Antworten, Manipulationen, das Ausnutzen technischer Fehler und Belästigung sind untersagt.</p><p>Verdächtige Ergebnisse können geprüft, korrigiert oder aus Ranglisten entfernt werden. Eine technische Auffälligkeit allein gilt nicht automatisch als Betrugsnachweis. Quizfragen dienen Unterhaltung und Allgemeinbildung und ersetzen keine professionelle medizinische, rechtliche oder finanzielle Beratung.</p><p>Ein unterbrechungsfreier Betrieb kann nicht garantiert werden. Wesentliche Änderungen an diesen Texten erhalten eine neue Version und müssen erneut bestätigt werden.</p></section>
<section id="kinder" class="legal-card"><span class="eyebrow">Altersgerechte Nutzung</span><h2>Kinder, Jugendliche und Eltern</h2><p>QuizTime erhebt kein vollständiges Geburtsdatum. Nutzer geben nur an, ob sie mindestens 16 Jahre alt sind. Bei Nutzern unter 16 Jahren wird eine Bestätigung durch eine erziehungsberechtigte Person per E-Mail angefordert. Bis zur Bestätigung bleiben Community- und Wettbewerbsfunktionen eingeschränkt.</p><p>Profilnamen sollten keine vollständigen Namen, Schulen, Anschriften oder andere sensible Angaben enthalten. Private E-Mail-Adressen werden nicht öffentlich angezeigt.</p></section>
<section class="legal-card"><span class="eyebrow">Selbstverwaltung</span><h2>Daten herunterladen oder löschen</h2><p>Im <a href="/account">Kontocenter</a> kann eine Kopie der gespeicherten Daten als JSON-Datei heruntergeladen werden. Das Profil kann nach Passwort- und Namensbestätigung gelöscht werden.</p><p><strong>Hinweis:</strong> Diese Texte sind technische Vorlagen und sollten vor einer breiten öffentlichen Veröffentlichung individuell rechtlich geprüft werden.</p></section>`;
  return shell({ title: 'Rechtliches, Datenschutz und Nutzungsregeln', content, config, warning });
}

function guardianResult(config, { ok, message }) {
  const content = `<section class="legal-card guardian-result"><div class="legal-result-icon">${ok ? '✓' : '!'}</div><h2>${ok ? 'Zustimmung bestätigt' : 'Bestätigung nicht möglich'}</h2><p>${esc(message)}</p><a class="btn primary" href="/">Zu QuizTime</a></section>`;
  return shell({ title: 'Zustimmung für ein Kinderkonto', content, config });
}

module.exports = { legalDocument, guardianResult, esc };
