import express from 'express';
import cors from 'cors';
import crypto from 'node:crypto';
import webpush from 'web-push';
import {createClient} from '@supabase/supabase-js';

const app=express();
const PORT=Number(process.env.PORT||10000);
const APP_ORIGIN=(process.env.APP_ORIGIN||'https://finanzplan-pwa.onrender.com').replace(/\/$/,'');
const SUPABASE_URL=(process.env.SUPABASE_URL||'').replace(/\/$/,'');
const SUPABASE_SERVICE_ROLE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||'';
const OPENAI_API_KEY=process.env.OPENAI_API_KEY||'';
const OPENAI_MODEL=process.env.OPENAI_MODEL||'gpt-5.6-luna';
const ENABLE_BANKING_APP_ID=process.env.ENABLE_BANKING_APP_ID||'';
const ENABLE_BANKING_PRIVATE_KEY=(process.env.ENABLE_BANKING_PRIVATE_KEY||'').replaceAll('\\n','\n');
const STATE_SECRET=process.env.STATE_SECRET||'';
const CRON_SECRET=process.env.CRON_SECRET||'';
const VAPID_PUBLIC_KEY=process.env.VAPID_PUBLIC_KEY||'';
const VAPID_PRIVATE_KEY=process.env.VAPID_PRIVATE_KEY||'';
const VAPID_SUBJECT=process.env.VAPID_SUBJECT||'mailto:admin@example.invalid';
const supabase=SUPABASE_URL&&SUPABASE_SERVICE_ROLE_KEY?createClient(SUPABASE_URL,SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}}):null;
if(VAPID_PUBLIC_KEY&&VAPID_PRIVATE_KEY)webpush.setVapidDetails(VAPID_SUBJECT,VAPID_PUBLIC_KEY,VAPID_PRIVATE_KEY);

app.disable('x-powered-by');
app.use(cors({origin(origin,cb){if(!origin||origin===APP_ORIGIN||origin.startsWith('http://127.0.0.1:')||origin.startsWith('http://localhost:'))return cb(null,true);cb(new Error('Origin not allowed'))},credentials:false}));
app.use(express.json({limit:'256kb'}));
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Cache-Control','no-store');next()});

const b64url=input=>Buffer.from(input).toString('base64url');
const safeJson=v=>{try{return JSON.parse(v)}catch{return null}};
function signState(payload){if(!STATE_SECRET)throw new Error('STATE_SECRET fehlt');const body=b64url(JSON.stringify(payload)),sig=crypto.createHmac('sha256',STATE_SECRET).update(body).digest('base64url');return `${body}.${sig}`}
function verifyState(token){if(!STATE_SECRET)throw new Error('STATE_SECRET fehlt');const [body,sig]=String(token||'').split('.');if(!body||!sig)throw new Error('Ungültiger State');const expected=crypto.createHmac('sha256',STATE_SECRET).update(body).digest('base64url');if(!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))throw new Error('Ungültiger State');const p=safeJson(Buffer.from(body,'base64url').toString('utf8'));if(!p||p.exp<Date.now())throw new Error('State abgelaufen');return p}
function enableJwt(){if(!ENABLE_BANKING_APP_ID||!ENABLE_BANKING_PRIVATE_KEY)throw new Error('Enable-Banking-Konfiguration fehlt');const now=Math.floor(Date.now()/1000),header=b64url(JSON.stringify({typ:'JWT',alg:'RS256',kid:ENABLE_BANKING_APP_ID})),payload=b64url(JSON.stringify({iss:'enablebanking.com',aud:'api.enablebanking.com',iat:now,exp:now+3600})),unsigned=`${header}.${payload}`,sig=crypto.sign('RSA-SHA256',Buffer.from(unsigned),ENABLE_BANKING_PRIVATE_KEY).toString('base64url');return `${unsigned}.${sig}`}
async function eb(path,{method='GET',body}={}){const r=await fetch(`https://api.enablebanking.com${path}`,{method,headers:{Authorization:`Bearer ${enableJwt()}`,Accept:'application/json',...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined}),text=await r.text(),j=text?safeJson(text):{};if(!r.ok)throw new Error(j?.detail||j?.message||`Enable Banking ${r.status}`);return j}
async function authUser(req,res,next){if(!supabase)return res.status(503).json({error:'Supabase ist noch nicht konfiguriert'});const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token)return res.status(401).json({error:'Anmeldung erforderlich'});const {data,error}=await supabase.auth.getUser(token);if(error||!data?.user)return res.status(401).json({error:'Cloud-Sitzung ungültig'});req.user=data.user;req.accessToken=token;next()}
async function requireMembership(userId,householdId){if(!householdId)throw new Error('householdId fehlt');const {data,error}=await supabase.from('household_members').select('role').eq('household_id',householdId).eq('user_id',userId).maybeSingle();if(error||!data)throw new Error('Kein Zugriff auf diesen Haushalt');return data.role}

app.get('/health',(req,res)=>res.json({ok:true,version:'3.1.0',services:{supabase:!!supabase,enableBanking:!!(ENABLE_BANKING_APP_ID&&ENABLE_BANKING_PRIVATE_KEY),openai:!!OPENAI_API_KEY,push:!!(VAPID_PUBLIC_KEY&&VAPID_PRIVATE_KEY)}}));
app.get('/api/banking/status',(req,res)=>res.json({provider:'enable-banking',bank:'N26',configured:!!(ENABLE_BANKING_APP_ID&&ENABLE_BANKING_PRIVATE_KEY&&supabase&&STATE_SECRET)}));

app.post('/api/banking/n26/start',authUser,async(req,res)=>{try{const {redirectUrl,householdId}=req.body||{};await requireMembership(req.user.id,householdId);const list=await eb('/aspsps?country=DE'),banks=Array.isArray(list)?list:(list.aspsps||list.items||[]),n26=banks.find(b=>/n26/i.test(b.name||b.title||''));if(!n26)throw new Error('N26 wurde bei Enable Banking für DE nicht gefunden');const state=signState({uid:req.user.id,householdId,exp:Date.now()+10*60*1000,nonce:crypto.randomUUID()}),access={valid_until:new Date(Date.now()+90*86400000).toISOString()};const out=await eb('/auth',{method:'POST',body:{access,aspsp:{name:n26.name,country:n26.country||'DE'},state,redirect_url:redirectUrl,psu_type:'personal',language:'de',psu_id:req.user.id}});res.json({url:out.url,state,authorizationId:out.authorization_id})}catch(e){res.status(400).json({error:e.message})}});

app.post('/api/banking/n26/exchange',authUser,async(req,res)=>{try{const {code,state,householdId}=req.body||{},p=verifyState(state);if(p.uid!==req.user.id||p.householdId!==householdId)throw new Error('State gehört nicht zu dieser Sitzung');await requireMembership(req.user.id,householdId);const out=await eb('/sessions',{method:'POST',body:{code}}),accounts=out.accounts||[];const row={user_id:req.user.id,household_id:householdId,provider:'enable-banking',bank:'N26',session_id:out.session_id,accounts,authorized_at:new Date().toISOString(),valid_until:out.access?.valid_until||null};const {error}=await supabase.from('bank_sessions').upsert(row,{onConflict:'user_id,household_id,provider'});if(error)throw error;res.json({ok:true,accounts,validUntil:row.valid_until})}catch(e){res.status(400).json({error:e.message})}});

function normalizedBankTx(t){const amount=Math.abs(Number(t.transaction_amount?.amount||0)),direction=t.credit_debit_indicator==='CRDT'?'credit':'debit',merchant=direction==='debit'?(t.creditor?.name||''):(t.debtor?.name||''),remittance=Array.isArray(t.remittance_information)?t.remittance_information.join(' · '):(t.remittance_information||t.note||'');return {id:t.transaction_id||t.entry_reference||t.reference_number||crypto.randomUUID(),date:t.booking_date||t.transaction_date||t.value_date,amount,direction,merchant,title:merchant||remittance||t.bank_transaction_code?.description||'N26 Umsatz',remittance,reference:t.reference_number||t.entry_reference||'',status:t.status||'BOOK'}}
async function fetchAllTransactions(accountId,days){const from=new Date(Date.now()-days*86400000).toISOString().slice(0,10),to=new Date().toISOString().slice(0,10),all=[];let key='';for(let i=0;i<10;i++){const qs=new URLSearchParams({date_from:from,date_to:to,transaction_status:'BOOK'});if(key)qs.set('continuation_key',key);const page=await eb(`/accounts/${encodeURIComponent(accountId)}/transactions?${qs}`);all.push(...(page.transactions||[]));key=page.continuation_key||'';if(!key)break}return all}
async function accountBalance(accountId){const b=await eb(`/accounts/${encodeURIComponent(accountId)}/balances`),rows=b.balances||[],pick=rows.find(x=>['CLAV','ITAV','CLBD','ITBD'].includes(x.balance_type))||rows[0];return pick?Number(pick.balance_amount?.amount):null}
app.get('/api/banking/n26/sync',authUser,async(req,res)=>{try{const days=Math.max(1,Math.min(730,Number(req.query.days||180))),householdId=String(req.query.householdId||req.headers['x-household-id']||'');let q=supabase.from('bank_sessions').select('*').eq('user_id',req.user.id).eq('provider','enable-banking').eq('bank','N26');if(householdId)q=q.eq('household_id',householdId);const {data:row,error}=await q.order('authorized_at',{ascending:false}).limit(1).maybeSingle();if(error||!row)throw new Error('Keine N26-Sitzung gespeichert');await requireMembership(req.user.id,row.household_id);const transactions=[];let balance=null;for(const a of row.accounts||[]){const id=a.uid;if(!id)continue;transactions.push(...(await fetchAllTransactions(id,days)).map(normalizedBankTx));if(balance===null)balance=await accountBalance(id)}res.json({transactions,balance,currency:'EUR',authorizedAt:row.authorized_at,validUntil:row.valid_until})}catch(e){res.status(400).json({error:e.message})}});

app.post('/api/ai/analyze',authUser,async(req,res)=>{try{if(!OPENAI_API_KEY)throw new Error('OPENAI_API_KEY ist noch nicht konfiguriert');const question=String(req.body?.question||'').slice(0,1500),context=req.body?.context;if(!question||!context)throw new Error('Frage oder Finanzkontext fehlt');const payload={model:OPENAI_MODEL,store:false,reasoning:{effort:'none'},text:{verbosity:'low'},instructions:'Du bist ein vorsichtiger deutscher Finanz-Erklärassistent. Alle Zahlen im bereitgestellten JSON wurden von einer deterministischen Finanzengine berechnet und sind verbindlich. Rechne Kontostände nicht neu und erfinde keine Werte. Erkläre Ursachen, Trends, Risiken und Handlungsoptionen klar. Keine Garantieversprechen und keine individuelle Anlageberatung.',input:`Frage: ${question}\nFinanzdaten (aggregiert): ${JSON.stringify(context)}`};const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(payload)}),j=await r.json();if(!r.ok)throw new Error(j?.error?.message||`OpenAI ${r.status}`);const text=(j.output||[]).flatMap(x=>x.content||[]).filter(x=>x.type==='output_text').map(x=>x.text).join('\n').trim();res.json({text,model:j.model,usage:j.usage||null})}catch(e){res.status(400).json({error:e.message})}});

app.get('/api/push/public-key',(req,res)=>res.json({publicKey:VAPID_PUBLIC_KEY||''}));
app.post('/api/push/subscribe',authUser,async(req,res)=>{try{if(!supabase)throw new Error('Supabase fehlt');const {householdId,subscription,deviceName}=req.body||{};await requireMembership(req.user.id,householdId);if(!subscription?.endpoint)throw new Error('Push-Subscription fehlt');const {error}=await supabase.from('push_subscriptions').upsert({user_id:req.user.id,household_id:householdId,endpoint:subscription.endpoint,subscription,device_name:String(deviceName||'Gerät').slice(0,80),updated_at:new Date().toISOString()},{onConflict:'endpoint'});if(error)throw error;res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/push/test',authUser,async(req,res)=>{try{if(!VAPID_PUBLIC_KEY)throw new Error('Web Push ist noch nicht konfiguriert');const {data:subs,error}=await supabase.from('push_subscriptions').select('*').eq('user_id',req.user.id);if(error)throw error;let sent=0;for(const s of subs||[]){try{await webpush.sendNotification(s.subscription,JSON.stringify({title:'Finanzplan',body:'Push funktioniert.',url:APP_ORIGIN}));sent++}catch(err){if([404,410].includes(err.statusCode))await supabase.from('push_subscriptions').delete().eq('endpoint',s.endpoint)}}res.json({sent})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/push/dispatch',async(req,res)=>{try{if(!CRON_SECRET||req.headers.authorization!==`Bearer ${CRON_SECRET}`)return res.status(401).json({error:'Unauthorized'});if(!VAPID_PUBLIC_KEY||!supabase)throw new Error('Push/Supabase nicht konfiguriert');const now=new Date().toISOString(),{data:jobs,error}=await supabase.from('push_jobs').select('*').eq('sent',false).lte('due_at',now).limit(200);if(error)throw error;let sent=0;for(const job of jobs||[]){const {data:subs}=await supabase.from('push_subscriptions').select('*').eq('household_id',job.household_id);for(const s of subs||[]){try{await webpush.sendNotification(s.subscription,JSON.stringify({title:job.title||'Finanzplan',body:job.body||'',url:job.url||APP_ORIGIN,tag:job.tag||job.id}));sent++}catch(err){if([404,410].includes(err.statusCode))await supabase.from('push_subscriptions').delete().eq('endpoint',s.endpoint)}}await supabase.from('push_jobs').update({sent:true,sent_at:new Date().toISOString()}).eq('id',job.id)}res.json({jobs:jobs?.length||0,sent})}catch(e){res.status(400).json({error:e.message})}});

app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'Interner Serverfehler'})});
if(process.env.NODE_ENV!=='test')app.listen(PORT,()=>console.log(`Finanzplan API v3.1 listening on ${PORT}`));
export {app,signState,verifyState,normalizedBankTx};
